### ISSUE TITLE
Allow a nicer way to run for a single framework

### ISSUE THREAD

**Issue by PWKad** [krausest/js-framework-benchmark#10]
The benchmarks seem to take a *really* long time to run, it would be nice if there was a way to pass an argument in to the mvn command to signal only running for a single framework.  Right now I am just using comments to block the others from running so it's doable would just be a nice to have.  Thanks for putting this together by the way cool stuff.

**Comment by krausest** [comment]
Maybe you want to take a look at the webdriver-ts directory.
You can choose frameworks or benchmarks now quite easily like that:
npm run selenium -- --framework ang,bobril --benchmark 01_, 02_
Runs angular 1, angular 2 and bobril for the 01_run1k and 02_replace1k benchmark.

**Comment by PWKad** [comment]
Oh cool didn't realize I ended up commenting out the other ones and that worked but your solution sounds better thanks!
