### ISSUE TITLE
React 18 beta

### ISSUE THREAD

**Issue by LifeIsStrange** [krausest/js-framework-benchmark#1002]
It would be nice to add a react 18 beta entry.
I know it's not officially stable yet but I'm very curious about the "automatic batching" improvement and it's been a year since react 17

**Comment by oleggrishechkin** [comment]
Hi, @LifeIsStrange.
In my local tests react18 with concurrent mode (createRoot) slightly slower than react17. Especially in "clear rows".
I think that "automatic batching" doesn't improve performance at all in this benchmark, even react17 batch all updates as well as react18 in most cases.

**Comment by LifeIsStrange** [comment]
for posterity I was refering to those improvements:
https://github.com/reactwg/react-18/discussions/21
Thanks for reporting :) Well it's unfortunate to hear react doesn't improve on this benchmark, could it be that react 18 would be faster than 17, when concurrent mode is disabled?

**Comment by oleggrishechkin** [comment]
The main problem with react is a diff algorithm. Swap rows has terrible performance and move react to the end of results list. With true state management we can improve selecting a row and partial update performance - all other tests should be the same for all state managers (but they can add some overhead).

In my tests I update only rows that needed directly (forceUpdate with useReducer) and it's the fastest solution for react, but useless (bad dx).

But I really waiting for react18 release!

**Comment by krausest** [comment]
Here's a look at react's performance for rc3 of version 18: 
![Screenshot from 2022-03-22 20-19-03](https://user-images.githubusercontent.com/3374055/159559344-68b9c9e7-9cab-4974-af2f-4c0c95fe6fd9.png)
I didn't commit the code,iIt's just the react-hooks implementation with react and react-dom@rc.

**Comment by Sparkenstein** [comment]
v18 is stable now :D 
any plan to merge this? I would recommend keeping both v17 and 18 since v18  is entirely different algorithm and it also gives features like Server rendered components etc.

**Comment by ryansolid** [comment]
I believe all merging has been halted while trying to figure out what in the world is happening here: https://github.com/krausest/js-framework-benchmark/issues/1020. I think might have landed on the new test setup now.

**Comment by krausest** [comment]
Right - I first had to solve that nasty #1020 
React 18 has been merged.
