### ISSUE TITLE
vanillajs-keyed "replace all rows" baseline is wrong

### ISSUE THREAD

**Issue by leeoniya** [krausest/js-framework-benchmark#103]
@krausest 

vanillajs-keyed doesnt actually replace rows for "replace all rows", which is why it's so fast while other keyed implementations are slower. at least for the keyed version, it needs to do the correct thing (which should clock in at slightly faster than the kivi impl)

i made a DOM-instrumented version of of vanillajs-keyed [1] [2]. you can watch the console to see a summary of DOM ops performed for any action.

feel free to use my DOMInstr lib (it's MIT) to check what the other implementations do when porting to keyed versions.

[1] https://rawgit.com/leeoniya/js-framework-benchmark/vanillajs-keyed-instrumented/vanillajs-keyed/index.html
[2] https://github.com/leeoniya/js-framework-benchmark/commit/8f1acaa5b91550e8e221f8cd5c05186545fa772a

**Comment by krausest** [comment]
Thanks. Fixed in 93c57f70ca00119e060037fcedeff8840dd28306.
