### ISSUE TITLE
Could you add gzipped file sizes?

### ISSUE THREAD

**Issue by rotaercz** [krausest/js-framework-benchmark#1041]
It would be nice to know what the approximate payload is.

**Comment by fabiospampinato** [comment]
That could be interesting also because not all libraries will scale the same, mangled ones will have a lower compression ratio.

**Comment by lukechu10** [comment]
Also wasm libraries tend to have a higher compression ratio.

**Comment by riderx** [comment]
Any news on that ? the size is very important for me to choose

**Comment by krausest** [comment]
Tracking this issue in #1340
