### ISSUE TITLE
Filtering tables via query parameters

### ISSUE THREAD

**Issue by fabiospampinato** [krausest/js-framework-benchmark#1048]
It'd be pretty handy to be able to load the table with only a specific set of frameworks enabled via URL query parameters.

I tend to always compare the same ones, and having a quick way to open the table for them would be nice, clicking buttons and finding those frameworks in the huge list of supported ones is a bit slow.

**Comment by krausest** [comment]
Here's a first implementation for that:
The copy button copies the current state to the clipboard and the URL hash.
The paste button reads the JSON state from the clipboard.
Loading the page with a hash initialises the table with that state. 
https://krausest.github.io/js-framework-benchmark/2022/table_chrome_103_state.html

It should be possible to add the hash automatically when selection changes. But I'm not sure if this would be helpful. My use case is that I have new results on localhost and the published results on the server and I want to get the same selection state on both. The approach with the clipboard would be easier for me in that case.

**Comment by fabiospampinato** [comment]
It seems to work great, thanks!
