### ISSUE TITLE
Exploring adding warm up runs in the "clear rows" benchmark

### ISSUE THREAD

**Issue by fabiospampinato** [krausest/js-framework-benchmark#1056]
I was taking a closer look at the "clear rows" benchmark, and I'm not sure how representative it is of real world performance. It feels like something that only matters in dynamic applications, where it doesn't really matter how long it took to cleanup the first time, but how long it takes on average, and to better measure that I think some warmup runs should be added to the test.

Locally I'm seeing wildly different numbers at startup and after the engine has got a chance to optimize things, for inherently dynamic benchmarks like this one IMO some warmup runs should be added to make them more useful.

**Comment by krausest** [comment]
I played a bit with adding a warm up for create 1,000 rows and clear rows. In both cases I added five cycles of create 1,000 and clear rows (for the the clear rows with an additional final create 1,000 rows). Then the benchmark runs after the warm up.
Results are here:
https://krausest.github.io/js-framework-benchmark/2022/table_chrome_103_warmup.html


<img width="413" alt="Bildschirmfoto 2022-06-28 um 19 53 00" src="https://user-images.githubusercontent.com/3374055/176249928-0cd2f6b4-2957-4fab-9c65-833dcdbf884e.png">

As I wrote I'm pretty unhappy about the current create 1,000 rows results. The results have a (too) high variance. Warming up helps that benchmark a lot and the variance is much lower. Thus I suggest replacing the old create 1,000 rows benchmark with the new version with the warmup. The boxplot shows the difference in a nice way:
<img width="1127" alt="Bildschirmfoto 2022-06-28 um 19 51 49" src="https://user-images.githubusercontent.com/3374055/176250922-15198294-9795-4c92-8425-78a429cec771.png">

For clear rows the effect looks much smaller:
<img width="1133" alt="Bildschirmfoto 2022-06-28 um 19 52 24" src="https://user-images.githubusercontent.com/3374055/176253950-244d9f6e-163d-412f-bec7-df2d0d02a96c.png">
I'm not a big fan of focusing only on peak performance (most users would expect the first run to be fast too) and thus I think I'd rather not add the warmup for clear rows. 
 @fabiospampinato I suppose the numbers you saw were quite different.  What did you observe?

Here are (at least most) frameworks with remarkable behaviour regarding the warmup:
<img width="1190" alt="Bildschirmfoto 2022-06-28 um 20 47 39" src="https://user-images.githubusercontent.com/3374055/176259261-18ab0a82-2dc0-4ab2-aa79-580cc219a0b5.png">
Some frameworks are indeed a bit or even quite a lot slower for the first run. Oldskull, miso and stdweb are notable outliers that get slower after warm up (ping @alexeyoganezov @dmjio @Pauan)!

**Comment by krausest** [comment]
Update: I ran the benchmark again for the three implementations that got slower with the warmup and I'm no longer sure about miso. This time it was quicker.
<img width="358" alt="Bildschirmfoto 2022-06-28 um 21 02 01" src="https://user-images.githubusercontent.com/3374055/176261777-5444f938-b71f-4677-bb80-7f6effb86dfe.png">
But variance is very high for miso in both cases:
<img width="294" alt="Bildschirmfoto 2022-06-28 um 21 04 39" src="https://user-images.githubusercontent.com/3374055/176262656-bafbacf3-5db9-491b-9799-c7b1bb882e06.png">

**Comment by fabiospampinato** [comment]
Awesome, thanks for the investigation!

IMO if it makes sense to add warm ups to "create rows" it should make sense to add them to "clear rows" too, in mostly static applications there is still going to be an initial creation, so I guess measuring that is useful for those kind of applications, but an initial disposal just doesn't really exist, if a significant chunk of the app gets disposed it's most probably because the app is very dynamic, and a significant chunk of it will probably be disposed of again and again multiple times in the future, hence, imo, how long it took the first time matters less and less.

Locally I was seeing the amount of time it took to cleanup the reactivity graph to be about ~20% of the total time on the first run, but going down to ~3% after a bunch of runs, maybe I did more than 5 warm up runs, I'm not sure. According to your screenshot I see the overhead over vanilla going down from ~19% to ~6%, which seems about what I was expecting, maybe I have a bit of overhead in the rest of the code that removes nodes from the DOM too, I should look into that.

**Comment by Pauan** [comment]
@krausest I can't think of any reason why warming up would make it slower. Looking at those graphs, stdweb still seems quite close, so maybe it's just statistical noise?

I think it's useful to include both the cold and warm results, because the cold results are for the initial page load, but the warm results are for dynamic SPAs which change after the page is loaded.

P.S. stdweb isn't maintained anymore, the last commit was in 2019, and for the most part stdweb has been replaced with wasm-bindgen

**Comment by fabiospampinato** [comment]
> @krausest I can't think of any reason why warming up would make it slower. Looking at those graphs, stdweb still seems quite close, so maybe it's just statistical noise?

If it's measurably slower multiple times with the warm ups I think it's probably not noise, the only think that I can think about is that the browser maybe optimizes something, but then it has to de-optimize it later on when some of the assumptions it made didn't hold up, maybe that's slower than just not optimizing , I'm not sure.

> I think it's useful to include both the cold and warm results, because the cold results are for the initial page load

During the initial page load I wouldn't expect a meaningful percentage of the app to be disposed already though 🤔 especially if the website is not app-like.

**Comment by krausest** [comment]
See #1050. All but one benchmark use now a warmup:
https://krausest.github.io/js-framework-benchmark/2022/table_chrome_103_mem10k_2.html
