### ISSUE TITLE
Switch to User Timing API

### ISSUE THREAD

**Issue by coderitual** [krausest/js-framework-benchmark#106]
I think the good idea would be to switch to User Timing API instead using `performance.now`. With `performance.mark` you can only mark timestamps without much impact on test and after all tests have passed `performance.measure` should be used to calculate.

References: 
https://www.html5rocks.com/en/tutorials/webperformance/usertiming/
https://developer.mozilla.org/en-US/docs/Web/API/User_Timing_API

**Comment by krausest** [comment]
The real measurement happens through webdriver-ts that uses chrome's timeline and extracts pretty exact numbers. The console logging is just a hack and thus I don't think it's worth putting much effort into. What benefit would we gain from that?

**Comment by leeoniya** [comment]
or...we could simplify all implementations by removing the timers from userland completely :)

**Comment by krausest** [comment]
That would at least sound plausible...

**Comment by coderitual** [comment]
@krausest @leeoniya Ok, didn't know about webdriver measurement. So the only reason to change it, is to promote good practice. Otherwise you can close it.
