### ISSUE TITLE
Updated infernojs to v1.1.1

### ISSUE THREAD

**Issue by renanol** [krausest/js-framework-benchmark#108]
https://github.com/infernojs/inferno/releases/tag/1.1.1

**Comment by krausest** [comment]
@trueadm 
I updated to 1.2, but ran into two smaller problems:
I can't build with webpack -p. It fails with the following error:
```
ERROR in main.js from UglifyJs
    SyntaxError: Unexpected token name «i», expected punc «;» [./~/babel-plugin-inferno/lib/index.js:34,0]
```
This happened also for older versions and thus the build-prod didn't invoke uglifyjs, but used an alias in webpack to include the minified dist js from inferno. 
But this now reports an error:
```
> webpack -d -c webpack.config.js

Hash: 4d8694fed9f10f1e81f4
Version: webpack 1.14.0
Child
    Hash: 4d8694fed9f10f1e81f4
    Version: webpack 1.14.0
    Time: 926ms
          Asset    Size  Chunks             Chunk Names
        main.js  129 kB       0  [emitted]  main
    main.js.map  147 kB       0  [emitted]  main
       [0] multi main 40 bytes {0} [built]
       [6] ./webpack.config.js 803 bytes {0} [built]
        + 10 hidden modules

    ERROR in ./~/inferno-vnode-flags/inferno-vnode-flags.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /Users/stefan/Source/Javascript/js-framework-benchmark/inferno-v1.2.0/node_modules/inferno/dist/inferno.js/dist/inferno-vnode-flags.node in /Users/stefan/Source/Javascript/js-framework-benchmark/inferno-v1.2.0/node_modules/inferno-vnode-flags
     @ ./~/inferno-vnode-flags/inferno-vnode-flags.js 1:17-65
```
Removing the alias resolves that problem too, but now the resulting javascript file is quite big. Any idea?

**Comment by trueadm** [comment]
@krausest I updated Inferno a few weeks ago: https://github.com/trueadm/js-framework-benchmark

It's a bit out-of-date now, but that might be a better starting point? Sorry, I'm on the move atm, maybe @hauven can help if he's around

**Comment by krausest** [comment]
@trueadm 
Thanks for the pointer. I compared it to your version and found that babel-plugin-inferno makes the difference. I tried to use 1.5.0, which caused the problems above, and went back to 1.4.0. With that version I can use the minified js files again. I suppose it's okay to use 1.4.0 with inferno 1.2.0?

**Comment by trueadm** [comment]
@krausest In theory that should be fine, my implementation should have also used keys too. I see they haven't been added though?

**Comment by krausest** [comment]
@trueadm 
You're right. Currently I have a non-keyed impl only, but I'll add the keyed the next few days...
