### ISSUE TITLE
sub-optimal "append rows to large table" in vanillajs (keyed and non-keyed)

### ISSUE THREAD

**Issue by leeoniya** [krausest/js-framework-benchmark#110]
@krausest kivi and inferno score non-trivially better than vanillajs in "append rows to large table" for both keyed and non-keyed impls. something to look into.

**Comment by krausest** [comment]
Directly appending the tr to the table is faster than using document.createDocumentFragment() - fixed now.

**Comment by leeoniya** [comment]
🎉 

yeah, `createDocumentFragement` optimizations are soooo 2012.
