### ISSUE TITLE
Add support for qwik framework

### ISSUE THREAD

**Issue by kiuKisas** [krausest/js-framework-benchmark#1101]
[qwik](https://github.com/BuilderIO/qwik) seems promising, I'm curious to see how it perform

**Comment by ryansolid** [comment]
I have an implementation ready to go. I was just waiting for an ok from the team. I will double-check with them and get it submitted.

**Comment by ryansolid** [comment]
Looks like they launched beta. I tried to update and it didn't quite work I will follow up with @manucorporat.

**Comment by ryansolid** [comment]
I've opened an issue on their repo: https://github.com/BuilderIO/qwik/issues/1404

**Comment by alkeryn** [comment]
hey @ryansolid i know it may be early but as of rn how does your qwik benchmark compares to solid and svelte ? :)

**Comment by danielrdrigues** [comment]
it's available?

**Comment by mi4uu** [comment]
any update?

**Comment by ryansolid** [comment]
Your best bet is to just follow up on the issue in their repo: https://github.com/BuilderIO/qwik/issues/1404.

When they hadn't touched this I was willing to submit, but now that their maintainers have versions of this benchmark I'm going to leave it to them to submit.

**Comment by md-owes** [comment]
I am joining the waiting list as well

**Comment by krausest** [comment]
There's now PR #1447 and maybe someone can help. Currently serving from our server doesn't work yet.
