### ISSUE TITLE
4x CPU throttling for remove row

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1104]
Remove row was a bit odd for chrome 105 on my MacBook Air (high variance). It looked better on my MacBook Pro:
https://krausest.github.io/js-framework-benchmark/current.html
I added a 4x CPU throttling and this is the result:
https://krausest.github.io/js-framework-benchmark/2022/table_chrome_105_remove4x.html

Overall I don't see a big difference. Dioxus and elm benefit from 4x throttling. I think we'll go with the 4x throttling for future runs. 
Any opinions?

**Comment by ryansolid** [comment]
It seems fine and definitely less variation. Looks like all the libraries that got hit the worst in 105 now are back in a comparable place to where they were before.
