### ISSUE TITLE
consider adding bundle size and parse/init time metrics

### ISSUE THREAD

**Issue by leeoniya** [krausest/js-framework-benchmark#111]
probably not too difficult, but really useful.

**Comment by krausest** [comment]
The latter is on my TODO list, but I'm afraid the former will turn into a webpack vs. rollup and closure vs. uglifyjs debate.

**Comment by leeoniya** [comment]
i'm not so sure about that.

why does this benchmark suite require its own webpack wrapper? aren't the impls already required to provide a build that can be run in the browser? is it just a layer for ensuring uniform output naming/semantics?

as a followup, if they're required to provide a minified/runnable bundle (or one that can be built via their respective `package.json`), who cares what they used to get there? let them go have that debate with their own tooling.

**Comment by krausest** [comment]
I've added a benchmark that tries to measure startup time. It measures duration from navigationStart until painting finished. I compared the measurement with performance.timing.loadEventEnd - performance.timing.navigationStart and it seems reasonable.

I was surprised that this makes the table more colorful ;-). 

It's the last line in the CPU [table](https://rawgit.com/krausest/js-framework-benchmark/c9b86ae72fa91b675514363fb207010c7bd3fe93/webdriver-ts/table.html).

As long as startup time varies that much I don't consider investigating CPU or network throttling. 

I'm looking forward to a uglify vs. closure and rollup vs. webpack battle...

**Comment by leeoniya** [comment]
nice, this is a good addition.

> I'm looking forward to a uglify vs. closure and rollup vs. webpack battle...

as stated earlier, i think the choice of tooling is pretty irrelevant. and we can already make a metric for final html + bundle size.

**Comment by gheoan** [comment]
@krausest Is the startup time metric influenced by bundle size? If that is the case then bundle size should be added as a separate metric.

**Comment by krausest** [comment]
@gheoan I'm currently not considering this though it might be interesting. Some of the frameworks do not create nice bundles, e.g. polymer. Thus measuring the size would mean getting the data from the chrome network logs. I won't invest in doing that (I find the startup interesting enough) but if you want to contribute a PR...

**Comment by leeoniya** [comment]
@krausest  i've been doing a lot of testing lately and i'm finding that the startup metric is very inconsistent and weighted strongly enough to influence the overall average rather unfairly for its high variability. i think part of the problem may be the loading of a large external stylesheet and how its processing is deferred based on system load, etc.

it would be worth investigating how startup time correlates with bundle size and maybe just rely on the bundle size for consistency.

i see bottom-line numbers affected as much as +/-3% between bench runs of the same thing.

**Comment by leeoniya** [comment]
is it possible to run the startup test by refreshing the page without cache rather than restarting the whole browser? i think that will help a lot.

**Comment by krausest** [comment]
Maybe #187 helps a bit - it allows you to interactively filter and sort the benchmarks in many ways.
Variance of the startup benchmark doesn't look too problematic to me - do you get a similar std dev or much higher? 
I could take a look to run in non-cached mode. The easiest way to achieve this seems to be the inkognito mode - might that cause any other negative side effect? 
I'll take a look at it the next days - but I plan to release the round 6 of the benchmark first.

**Comment by eavichay** [comment]
How is the overall score calculated? Can this may be changed in the interactive results page? Assuming one wants to give priority to 10K in-list swaps and other prioritize new 10K. Is this possible?

**Comment by krausest** [comment]
Thanks to lighthouse and #330 we can close this one.
