### ISSUE TITLE
Add Qwik to Benchmark

### ISSUE THREAD

**Issue by kaiqueaguilar** [krausest/js-framework-benchmark#1111]
The Qwik framework came up with a different proposal from the others and promises to be the most performant.
Official site: https://qwik.builder.io/

**Comment by aclueless** [comment]
See #1101

**Comment by ryansolid** [comment]
To be fair. Qwik's benefit won't show in this benchmark. This isn't where they are optimized. I think they definitely should be included, but need to keep expectations in a reasonable place.

**Comment by ryansolid** [comment]
I've opened an issue on their repo: https://github.com/BuilderIO/qwik/issues/1404
