### ISSUE TITLE
Run tests on device browsers?

### ISSUE THREAD

**Issue by perqa** [krausest/js-framework-benchmark#1112]
If one wanted to run the set of tests on a real device browser rather than headless Chrome, would that be possible somehow? 
I would like to be able to navigate to a web site with any device browser, and run all tests on different device/browser combos.
Is this at all possible (or meaningful) with the current source code as base, and which architectural changes would be needed if it is?

**Comment by krausest** [comment]
Actually I don't think this would easily be possible.
Puppeteer or any other benchmark driver would need to run chrome remotely on the device. 
Those might be the steps towards such a solution:
- Find out how to get chrome performance data from the device. It might be possible to connect the chrome dev tools on a mobile device (unless it has an apple on its back side).
- Check if chrome can be launched remotely or if a single instance has to be started manually. The latter could be a problem for stability and variance.
