### ISSUE TITLE
binding.scala doesn't build on windows

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#112]
Works on OSX, but fails on windows (see #91).
<img width="859" alt="bildschirmfoto 2017-01-14 um 22 37 40" src="https://cloud.githubusercontent.com/assets/3374055/21958240/1f95bf96-daaa-11e6-87b5-9caea592f6de.png">

**Comment by krausest** [comment]
`npm install sbt-bin` fails with the message above. 

31370 warn Error: EPERM: operation not permitted, lstat 'C:\Source\v1\binding.scala-v10.0.1\node_modules\glob-base\node_modules'
31370 warn  { Error: EPERM: operation not permitted, lstat 'C:\Source\v1\binding.scala-v10.0.1\node_modules\glob-base\node_modules'
31370 warn   errno: -4048,
31370 warn   code: 'EPERM',
31370 warn   syscall: 'lstat',
31370 warn   path: 'C:\\Source\\v1\\binding.scala-v10.0.1\\node_modules\\glob-base\\node_modules' }
31371 verbose Please try running this command again as root/Administrator.
31372 verbose stack Error: sbt-bin@0.1.1 postinstall: `node install.js`
31372 verbose stack Exit status 1
31372 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
31372 verbose stack     at emitTwo (events.js:106:13)
31372 verbose stack     at EventEmitter.emit (events.js:191:7)
31372 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
31372 verbose stack     at emitTwo (events.js:106:13)
31372 verbose stack     at ChildProcess.emit (events.js:191:7)
31372 verbose stack     at maybeClose (internal/child_process.js:885:16)
31372 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by krausest** [comment]
@Atry Any idea how to fix this (it also fails for an admin cmd on windows)

**Comment by Atry** [comment]
Binding.scala's benchmark is built from [sbt](http://www.scala-sbt.org/), which is wrapped as a npm package by [sbt-bin](https://www.npmjs.com/package/sbt-bin), which did not support Windows.

I have created a pull request for sbt-bin to solve this problem

**Comment by krausest** [comment]
Thanks! Tested in the windows VM and it works fine!
