### ISSUE TITLE
Quick links to each framework's repository and benchmark implementation

### ISSUE THREAD

**Issue by fabiospampinato** [krausest/js-framework-benchmark#1141]
It'd be useful to have links somewhere in the table, for each framework, one pointing to their repository and one pointing to their benchmark implementation.

The reasons being that if a result looks good on the table that's only half the picture, if the benchmark implementation is crazy then users should be much less interested in using it, and if both the result and the implementation look good then it'd be interesting to read more about a framework and jump to its repository.

**Comment by krausest** [comment]
I added a way to handle both requirements. The text doesn't win any price for it's design, maybe I find the time for a nice icon.
The frameworkHomeURL still has to be added for all frameworks except react.
We should start with that after #1139 is merged to avoid conflicts.
