### ISSUE TITLE
Cleaning up for Christmas

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1146]
https://open.spotify.com/track/4NLNaPIqMMrYBUrC7101gg?si=329d44113c3a4826

Keyed Frameworks that seem inactive > 1 year:

- 1more @Freak613 :seedling:
- ~~callbag-jsx and callbag-jsx-list @loreanvictor~~
- choo @douglasduteil @rahulcs :seedling:
- domdiff @WebReflection :seedling:
- doohtml @hman61 
- dyo @thysultan
- ganic @yuanoook
- heresy @WebReflection :seedling:
- hullo @arturkulig :seedling:
- ~~hyperHTML~~
- ~~isotope @areknawo~~
- lighterhtml @WebReflection :seedling:
- neverland @WebReflection :seedling:
- petit-dom @yelouafi
- react-easy-state @solkimicreb
- ~~reaml @utkarshkukreti~~
- skruv @SahAssar  :seedling:
- vidom @dfilatov 

Please let me know if we should make an exception and not retire an implementation.

Some of the bigger frameworks seem to be inactive for more that a year:
- backbone.marionette  @paulfalgout :seedling:
- knockout @rkalasky :seedling:

Should we consider them dead?

BTW I'm not asking about the non-keyed implementations. They will be removed if no updates within the last year happened. Those are:
- crui
- Datum
- fidan
- neow
- moon
- simi
- vanilla-dom-framework

**Comment by paulfalgout** [comment]
Hmm well we had planned to move to `marionette` and remove the `backbone` dependency.  A lot of that got derailed during some departures during covid.   I believe I added the alpha here.  Then interestingly backbone was revived a bit. 
`backbone.marionette` is complete AFAIK outside of any security alert and would be superseded by `marionette` if/when there's progress made.  The library is perhaps surprisingly still in use so I don't consider it dead, but it certainly isn't overly active.  I doubt people are looking up benchmarks on it.  However if marionette development gets going again I'd certainly continue to test it against this library.  Whichever.

**Comment by arturkulig** [comment]
`hullo` yes, for both tests

**Comment by loreanvictor** [comment]
sure thing, I am not planning on further development of `callbag-jsx` with any substantial changes, and it also has a minuscule user base so I can just refer to my own fork for whomever wants to run the benchmark for themselves.

**Comment by Freak613** [comment]
1more is on pause, but I'm planning to continue development. I'd keep it for representation, as one of examples of VDOM diffing + template literals.

**Comment by areknawo** [comment]
Sounds good, I've stopped the development of `Isotope`, since I've discovered Solid.js. :)

**Comment by WebReflection** [comment]
FYI my lib are still maintained and working … there’s a difference between zero activity and done. No bugs means done and, unless deprecated on either the repo or the npm registry, there’s no reason to drop these libraries. hyperHTML is in maintaining mode so maybe that’s ok, the rest simply works …. It’s like removing vanilla js test because no changes happened in years … I don’t get this metric.

**Comment by krausest** [comment]
@WebReflection It's perfectly fine to keep your frameworks if they are still maintained.  Most dead frameworks so far died without announcement. The metric might not be perfect, but it's a good indication to start asking whether it's actually dead.

**Comment by WebReflection** [comment]
@krausest you can remove hyperHTML as it's "*legacy*" compared to others and not interesting in results ... I will try to bring in *udomdiff* which is *domdiff* successor but until that please keep domdiff around, thanks! Others might be also replaced by *udomsay* but these are hooks alternatives (heresy, neverland, lighterhtml) so thanks for keeping these around for the time being.

**Comment by utkarshkukreti** [comment]
@krausest Reaml is not maintained anymore, you can remove both reaml-react and reaml-preact.

**Comment by rkalasky** [comment]
Knockout is certainly still in use across the web, although I doubt any new projects are selecting it as the framework of choice. There is a v4 rewrite underway, but that will be a significant breaking change from v3.

**Comment by douglasduteil** [comment]
I don't know you @rahulcs but I'm pinging @tornqvist and @yoshuawuyts for the @choojs case. I'm not monitoring it nowadays.

**Comment by hman61** [comment]
I no longer see doohtml on the current results. What is the reason?

https://krausest.github.io/js-framework-benchmark/current.html

**Comment by hman61** [comment]
The last pull request was on *Nov 7, 2022*, why is that considered no
activity?
https://github.com/krausest/js-framework-benchmark/pull/1129

**Comment by krausest** [comment]
@hman61 My metric to check for activity didn't work for doohtml, since it's not installed via npm. I'm sorry and I'll restore doohtml soon.
Do you consider publishing doohtml on NPM?

**Comment by hman61** [comment]
Yes, I’m definitely going to eventually publish it to npm, but I’m not
doing it until I decouple the data store, so that it can work with any
popular data store.

**Comment by hman61** [comment]
Can you send me the reason why the latest DooHTML was not merge?

- Henrik Javen
