### ISSUE TITLE
Support for full-stack Rust framework?

### ISSUE THREAD

**Issue by saru-tora** [krausest/js-framework-benchmark#1149]
Can this test a Rust framework that starts rendering in the server like Qwik?

**Comment by ryansolid** [comment]
All the tests are client side updates.. other than some initial load numbers from lighthouse. But given those are static hosted and served, you aren't really going to see any benefit.

When Qwik is added to this benchmark it will be a client only implementation like the others I imagine.

**Comment by saru-tora** [comment]
I see. Thanks for the answer.
