### ISSUE TITLE
consider running benchmark with CPU/net throttling

### ISSUE THREAD

**Issue by leeoniya** [krausest/js-framework-benchmark#115]
@krausest 

Now that the benchmark has been split into keyed/unkeyed, both tables are largely green. They're green in part due to the relatively high specs of the machine on which these benches run. This performance of your Mac is sufficient not to break the the 16ms frame boundary in many cases.

This situation is not great because mobile phones - even modern ones - are *much* slower...and they account for 50% of web traffic today. Rather than re-scaling the colorization, I propose reducing the max workload (maybe 10k rows -> 5k rows) but running the bench with Chrome's 3x CPU throttling and maybe network throttling at Good 3G that's representative of mobile performance. These changes would help de-greenify the tables and help better assess mobile overhead in real life.

FWIW, in my experience Chrome's throttling can in fact be tweaked to be representative of actual perf i get on my 5 year old, not-so-fast device in 3G. [1]

This should probably wait till after Round 5, which i assume is coming soon.

[1] http://www.gsmarena.com/htc_evo_4g_lte-4665.php

**Comment by krausest** [comment]
Sounds great - but I have little to no idea how to achieve this. Though both options are easily available in chrome, I haven't found a way to use them in chromedriver.
It seems that network throttling was introduced in chromedriver, but no one knows how to use it:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=984
Any ideas? (E.g. using BrowserMob Proxy could be an alternative for network throttling, but for CPU throttling it might be harder).

**Comment by leeoniya** [comment]
huh, that's unfortunate. i think CPU throttling is really the more interesting aspect. the network throttle results can be inferred pretty well from just comparing bundle sizes.

> but for CPU throttling it might be harder)

you can run Prime95 for 30min to get it toasty or take a screwdriver to your cpu :rofl:

**Comment by krausest** [comment]
see #111
