### ISSUE TITLE
Trouble testing

### ISSUE THREAD

**Issue by saru-tora** [krausest/js-framework-benchmark#1187]
I've written an implementation, but I'm having trouble testing it. It looks like the test uses Chrome, which I don't have (on Linux). If the implementation works on Firefox, can I submit it anyway?

**Comment by krausest** [comment]
I can take a look at it, but it should be possible to install chrome on linux or run the benchmark with the —chromeBinary option pointing to a chromium binary (though I admit I haven‘t tried that options for a long time).

**Comment by saru-tora** [comment]
It passed the benchmark by pointing it to a chromium binary, but I can't seem to make the isKeyed script do the same.

**Comment by krausest** [comment]
The following command in webdriver-ts should works on OSX and should work on linux too:
```
npm run isKeyed -- --chromeBinary /Applications/Google\ Chrome\ Dev.app/Contents/MacOS/Google\ Chrome\ Dev
```

**Comment by saru-tora** [comment]
It worked.
