### ISSUE TITLE
Doc: run npm ci in server

### ISSUE THREAD

**Issue by peter-jerry-ye** [krausest/js-framework-benchmark#1207]
Hello,

I'm just trying to start up the project following the step by step instructions. However, I find this part may need some extra instructions.

> Install global dependencies This installs just a few top level dependencies for the building the frameworks and a local web server.
> `npm ci`
> We start the local web server in the root directory
> `npm start`

It would seem that one should also run `npm ci` in the `server` directory to get `express` installed.

**Comment by krausest** [comment]
Sorry, I added a postinstall script that runs `npm install` in the server folder. So running `npm ci` in the main should fix it.
(if not please run `npm install` in the server directory)
