### ISSUE TITLE
Simplify terser configuration

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1215]
As discussed in #1214 the complex terser configuration has no positive impact on performance. 

I'd like to move to a minimal configuration since it turned out I had to modify a lot of configuration files (remove cache:true) for no performance benefit. 

After adjusting the configuration results should be compared to the last published ones to make sure that it indeed has no impact.

**Comment by fabiospampinato** [comment]
A bit unrelated, but switching to esbuild for minification should dramatically lower compilation times (like [100x faster minification](https://github.com/privatenumber/minification-benchmarks) potentially), with probably little or no impacts on performance also.

**Comment by krausest** [comment]
Cleaned up config for webpack and rollup..

@fabiospampinato Not sure if I want to go into that direction. Updating to node 18 was quite painful and I feel I'm getting too old to have fun fiddling with config files.
