### ISSUE TITLE
Update Inferno to 1.2.2

### ISSUE THREAD

**Issue by Sharlaan** [krausest/js-framework-benchmark#122]
Apparently guys at Inferno managed to boost createElement() by 50%

Might be interesting to bench it ?

**Comment by thysultan** [comment]
@Sharlaan The current implementation uses JSX that translates to `VNode()` function calls which is faster than `createElement()`.

**Comment by krausest** [comment]
Time passes quickly. I'm updating to 1.3.0-rc3. Seems like defaultValue={{func: deleteFunc, id}} works no more. Does anyone know if onClick={linkEvent(id, deleteFunc)} is the best solution?

**Comment by krausest** [comment]
That way I removed the event delegation. Might be a bit slower, but fairer in comparison to react and angular.
