### ISSUE TITLE
Transpose table as vertical scrolling is easier than horizontal

### ISSUE THREAD

**Issue by eugenesvk** [krausest/js-framework-benchmark#1220]
Currently most of the information is hidden in the horizontal dimension (very few rows, a lot of columns)
But scrolling vertically is easier, so it would be better to have a long vertical table with row=framework and column=action

**Comment by krausest** [comment]
Thanks, but I'm not going to transpose the tables. 
Scrolling on my mac works actually equally good for both horizontal and vertical direction 😄
