### ISSUE TITLE
Adding warm-up runs to "append rows to large table"

### ISSUE THREAD

**Issue by fabiospampinato** [krausest/js-framework-benchmark#1222]
Apparently all main tests have warm-up runs, except for "append rows to large table", maybe some should be added for that too?

Cold performance of JS seems too unpredictable, and potentially wildly different from hot performance, to be a good measure.

**Comment by krausest** [comment]
I took at a look at it. To my surprise the benchmark lied about appending to a table with 10,000 rows. Ever since running with puppeteer it appended to 1,000 rows.
I added a warmup loop for create/clear, that should warmup the framework enough such that add performs well also.

**Comment by krausest** [comment]
Results now include a warmup for append rows.
I haven't seen a case with a large improvement, imba is even way slower with the warmup (@somebee just in case you want to take a look...). 
Append rows took 92.5 msecs for imba with warmup and 52.4 without warmup.
Doz also took a bit hit (+14 msecs).
