### ISSUE TITLE
Combine result tables

### ISSUE THREAD

**Issue by benmccann** [krausest/js-framework-benchmark#1228]
The DOM, startup metrics, and memory allocation tables are separate. However, results are sorted for all three based purely based on the DOM results. I think this has the effect of giving very little weight to the startup and memory allocation tests when viewing the results. If we were to combine the three tables into one, then we could have a geometric mean row at the bottom acting as a total which takes into account tests from all categories and gives a more holistic overview.

Note that by combining tables, we don't have to lose the separation that is currently present. We can still insert a divider/header row that acts to group rows ([example](https://www.ag-grid.com/angular-data-grid/grouping-group-rows/)). And we could still have a geometric mean per group if desired (i.e. one for DOM, startup, and memory).

The keyed and non-keyed tables probably have to remain separate since they have different columns / frameworks.

**Comment by krausest** [comment]
I'm afraid currently I'm not planning to calculate an overall score. I think the main value of this benchmark is CPU time and I'm not sure how to weight between the tree aspects.
