### ISSUE TITLE
"ready memory" for blazor-wasm seems incorrect.

### ISSUE THREAD

**Issue by TrieBr** [krausest/js-framework-benchmark#1231]
[Memory footprint](https://krausest.github.io/js-framework-benchmark/2023/table_chrome_112.0.5615.49.html#eyJmcmFtZXdvcmtzIjpbImtleWVkL2JsYXpvci13YXNtIiwia2V5ZWQvYmxhem9yLXdhc20tYW90Iiwibm9uLWtleWVkL2FwcHJ1biIsIm5vbi1rZXllZC9hcnQiLCJub24ta2V5ZWQvYXVyZWxpYSIsIm5vbi1rZXllZC9iZGMiLCJub24ta2V5ZWQvYmluZGluZy5zY2FsYSIsIm5vbi1rZXllZC9kZWxvcmVhbiIsIm5vbi1rZXllZC9kb21kaWZmIiwibm9uLWtleWVkL2RvbXZtIiwibm9uLWtleWVkL2Rvb2h0bWwiLCJub24ta2V5ZWQvZG96Iiwibm9uLWtleWVkL2VmLWpzIiwibm9uLWtleWVkL2VsbSIsIm5vbi1rZXllZC9lbmRvcnBoaW4iLCJub24ta2V5ZWQvZnJlIiwibm9uLWtleWVkL2d5cm9uIiwibm9uLWtleWVkL2hhbG9nZW4iLCJub24ta2V5ZWQvaGVyZXN5Iiwibm9uLWtleWVkL2h1bGxvIiwibm9uLWtleWVkL2h5ZHJvLWpzIiwibm9uLWtleWVkL2luY3JfZG9tIiwibm9uLWtleWVkL2luZmVybm8iLCJub24ta2V5ZWQvbGlnaHRlcmh0bWwiLCJub24ta2V5ZWQvbGl0Iiwibm9uLWtleWVkL2xpdC1odG1sIiwibm9uLWtleWVkL2xpdGVyYWxqcyIsIm5vbi1rZXllZC9tYXF1ZXR0ZSIsIm5vbi1rZXllZC9taWthZG8iLCJub24ta2V5ZWQvbWltYmwiLCJub24ta2V5ZWQvbWlzbyIsIm5vbi1rZXllZC9tb2d3YWkiLCJub24ta2V5ZWQvbmV2ZXJsYW5kIiwibm9uLWtleWVkL3BldGl0ZS12dWUiLCJub24ta2V5ZWQvcmFjdGl2ZSIsIm5vbi1rZXllZC9yZWFjdCIsIm5vbi1rZXllZC9yZWRvbSIsIm5vbi1rZXllZC9yZWZsZXgtZG9tIiwibm9uLWtleWVkL3Jpb3QiLCJub24ta2V5ZWQvc2FuIiwibm9uLWtleWVkL3NhdXJvbiIsIm5vbi1rZXllZC9zY2FybGV0cy1mcmFtZSIsIm5vbi1rZXllZC9zZWVkIiwibm9uLWtleWVkL3NpZnJyIiwibm9uLWtleWVkL3NsaW0tanMiLCJub24ta2V5ZWQvc2xpbmdqcyIsIm5vbi1rZXllZC9zdGR3ZWIiLCJub24ta2V5ZWQvc3ZlbHRlIiwibm9uLWtleWVkL3Vkb21zYXktZXN4Iiwibm9uLWtleWVkL3VodG1sIiwibm9uLWtleWVkL3VpNS13ZWJjb21wb25lbnRzIiwibm9uLWtleWVkL3ZhbmlsbGFqcyIsIm5vbi1rZXllZC92YW5pbGxhanMtMSIsIm5vbi1rZXllZC92dWUiXSwiYmVuY2htYXJrcyI6WyIyMV9yZWFkeS1tZW1vcnkiLCIzNF9zdGFydHVwLXRvdGFsYnl0ZXMiXSwiZGlzcGxheU1vZGUiOjEsImNhdGVnb3JpZXMiOlsxLDIsMyw0LDVdfQ==) for blazor-wasm seems incorrect. I use blazor-wasm (.NET 6) in production and the memory footprint for a moderately complex page is ~100MB according to chrome. I'm unclear how it's measured at over 500MB on page load in the benchmark. 

When I open the published code in chrome, the chrome task manager shows the page using 70MB and goes to 386MB after adding 10,000 rows. 

```bash
#optional
dotnet tool install --global dotnet-serve

git clone https://github.com/krausest/js-framework-benchmark.git
cd js-framework-benchmark/frameworks/keyed/blazor-wasm/bundeled-dist/wwwroot/
dotnet-serve -o 
```

Can someone clarify how this benchmark framework is measuring over 500MB for blazor-wasm?

I tested this on Macbook 2020 M1

**Comment by krausest** [comment]
blazor-wasm and blazor-wasm-aot are the only implementations that report ready memory more than 7 MB. 500MB look indeed irritatingly high.
As discussed in https://github.com/krausest/js-framework-benchmark/issues/1050#issuecomment-1172715942 I'm using measureUserAgentSpecificMemory. One can also run that command in the console:
```
await performance.measureUserAgentSpecificMemory()
{breakdown: Array(4), bytes: 541066405}
```
So this answers how I make up the result, but I think it's fair to ask if that number makes any sense...
If I find the time I'll open an issue for chrome.

**Comment by krausest** [comment]
I checked the other two ways to measure:
The CDP command `Runtime.getHeapUsage` returns `{ usedSize: 1957320, totalSize: 3883008 }` and `Performance.getMetrics` also `{...,     { name: 'JSHeapUsedSize', value: 1957320 }, { name: 'JSHeapTotalSize', value: 3883008 }, ... }`

**Comment by TrieBr** [comment]
I found that `await performance.measureUserAgentSpecificMemory()` does indeed output `540460110` bytes and `performance.memory. totalJSHeapSize` is `542141397` but I'm unclear why this differs so drastically from chrome's task manager and my OS (OS X) which still shows ~30MB.

Also in chrome devTools,  the "Memory" tab shows a 2.8MB VM instance, but after snapshotting it shows over 500MB mostly coming from a single JSArrayBufferData with what looks like a wasm function table. This seems like a potential bug in how chrome measures memory usage for wasm.

**Comment by krausest** [comment]
There'a a line
`
var INITIAL_MEMORY = Module["INITIAL_MEMORY"] || 536870912;
`
in dotnet.6.0.1.6ltooml0de.js. I don't know blazor well enough, but could it be that it indeed allocates such a large buffer on startup?

**Comment by TrieBr** [comment]
I upgraded to .NET 7.0 locally and the issue appears to be fixed.

**Comment by krausest** [comment]
Updating to blazor 7 results in lower values.
The line I mentioned above now is for blazor-wasm
```
var INITIAL_MEMORY = Module["INITIAL_MEMORY"] || 16777216;
```
and for blazor-wasm-aot 
```
var INITIAL_MEMORY = Module["INITIAL_MEMORY"] || 134217728;
```
and the memory benchmarks reports 36.8 MB and 130.9 MB.

Currently it looks to me like blazor is actually allocating that much memory for WASM and the reported memory usage seems correct.

**Comment by TrieBr** [comment]
Related: dotnet/runtime/pull/80849
