### ISSUE TITLE
Showing JS-only, Browser-only, and JS+Browser measurements

### ISSUE THREAD

**Issue by fabiospampinato** [krausest/js-framework-benchmark#1233]
As I understand it tests like "create many rows" measure the entire change, not just how long it took for the javascript to execute, but also how long it took for style recalculations, layout recalculations, and painting.

If that's the case It'd be interesting to be able to see results under 3 different filters, browser-only measurements (to check if the implementation has abnormal layout recalculations for example), javascript-only measurements (to check how much work the framework is actually doing, which assuming everything else is normal is largely what actually matters in the benchmark), and combined view where everything is taken into account.

The more practical motivation is that I think I might know how to half the amount of javascript work that is needed in some unkeyed tests (maybe some keyed tests also, depending on the exact definition one is using), but if the number displayed is dwarfed by style/layout/paint calculations it will seem like not much, even though it's actually pretty significant.

**Comment by leeoniya** [comment]
i've been championing this for a while, along with reducing 16x slowdown to maybe 4x, and reducing the DOM size. even very heavy apps, like Slack consistently stay well below 10k dom nodes, while this bench generates 88k for the "create 10k rows + append 1k" metric.

see https://github.com/krausest/js-framework-benchmark/issues/403#issuecomment-393156221

**Comment by fabiospampinato** [comment]
Potentially if the purpose of the slowdown is to make some tests weigh more than they otherwise would on the average the slowdown could just be deleted and the result could be multiplied by some constant number, I guess it should achieve the same result, perhaps lowering the amount of time it takes to run the benchmark also? I'm not exactly sure how the slowdown is implemented in Chrome also, it may be more reliable just to multiply the normal result by some constant.

80k+ nodes is kind of absurd, though I think the point of that test is more see how the framework scales, and perhaps to magnify small problems that might exist at lower numbers but go unnoticed. We could probably just switch to 100 rows base case and 1000 rows "worst" case without losing too much information. Maybe that'd be good if it makes the benchmark significantly cheaper to run.

**Comment by unmeimusu** [comment]
hello, my I ask about Imba framework benchmark test?, since Imba use compiler (to simplify the code syntax) to JS as an output same as some framework did like Svelte, please help me get new test result here, thanks.

**Comment by krausest** [comment]
I investigated measuring JS script duration only. The idea is to compute it as the delta of `page.metrics().ScriptDuration`for puppeteer and the CDP command for `Performance.getMetrics`(https://github.com/krausest/js-framework-benchmark/blob/13f27779220c2577420da056c8ef9a1317405161/webdriver-ts/src/forkedBenchmarkRunnerPuppeteer.ts#L133) since I haven't found a way to extract this directly from the traces.

Here's an example for alpine and create rows. The total duration is 99 and the JS script duration 59 msecs. The test driver reports 104 msecs and 62.5 msecs respectively, which sounds plausible.
<img width="685" alt="alpine" src="https://user-images.githubusercontent.com/3374055/236549199-24b1c4ed-4354-4601-ab8b-73aea8f371d1.png">
Same for voby is an example for a total duration of 43.15 and a JS script duration of 5 msecs. The test driver reports 41.4 msecs for the total duration and 4.9 msecs for the script duration, which also sounds good.
<img width="847" alt="voby" src="https://user-images.githubusercontent.com/3374055/236549211-a995ca71-1e7d-4903-af8d-6ebae246da24.png">
Here's a comparison for some frameworks that seem plausible.

<img width="437" alt="Bildschirmfoto 2023-05-05 um 9 17 55 PM" src="https://user-images.githubusercontent.com/3374055/236550332-eb5bbab2-6f0c-4818-9de5-0742841eb09d.png">

I did this for all frameworks during the chrome 113 run, but some results are just too good to believe and must be investigated:
<img width="1219" alt="Bildschirmfoto 2023-05-05 um 9 20 57 PM" src="https://user-images.githubusercontent.com/3374055/236550909-8c08f498-dcac-4c35-ad62-c2e4cb3c75bd.png">
(Values reported as 0.0 are reported as zero due to rounding, not by actually having a duration of 0)

**Comment by krausest** [comment]
For ember I'd expect ~28 msecs:
<img width="465" alt="Bildschirmfoto 2023-05-05 um 9 29 34 PM" src="https://user-images.githubusercontent.com/3374055/236552411-56c373d8-b526-443d-859e-398b3f546dc2.png">

**Comment by leeoniya** [comment]
great to see some progress!

i would also make sure to include any gc cost in this if it's not part of "script" already. i've seen it under "system" in chrome's profiler.

**Comment by ClassicOldSong** [comment]
One opinion: how the script manipulates DOM still counts. One framework takes much less time scripting but with much more duplicated DOM operations, while one other may take some more time scripting but significantly less time with DOM operations. These values can be measured separately, but must be calculated together.

**Comment by fabiospampinato** [comment]
To give higher cost to inefficient DOM operations one just add 10 mutation observers on the page or something like that, those things are _slow_.

Problem is ~everybody uses .appendChild because it's faster for no good reason, _when measured in isolation_, while .append is faster if there are any mutation observer on the page, potentially faster by a huge amount.

**Comment by ClassicOldSong** [comment]
That's still not a very good solution to simulate slow repaint/reflows. When moving empty text nodes around, it's costing almost nothing if there's no mutation observers, but with multiple observers added, it's adding unrealistic costs to these originally cheap operations.

**Comment by leeoniya** [comment]
> One opinion: how the script manipulates DOM still counts.

agreed. this whole js/gc-only measurement exercise only makes sense for frameworks that already do near-optimal DOM ops with identical repaint/reflow costs.

however, there could be a different approach here.

instead of trying to measure script exrcution, why dont we measure the fastest possible restyle/reflow/paint and simply subtract this from the totals. that will hopefully cover all cases, including frameworks that do duplicate/inefficient dom ops.

**Comment by leeoniya** [comment]
here's another interesting project: https://github.com/yamiteru/isitfast

**Comment by ClassicOldSong** [comment]
> instead of trying to measure script execution directly, why dont we measure the fastest possible restyle+reflow+paint and simply subtract this from the totals. that will hopefully cover all cases, including frameworks that do duplicate/inefficient dom ops.

That's an interesting idea, but it's hard to determine what is the fastest possible time. We have multiple different implementations with different pros and cons, different approach may have different limitations from each other. It's very hard to find an even ground for these measures.

**Comment by leeoniya** [comment]
> We have multiple different implementations with different pros and cons

this benchmark does not attempt to pick the fastest framework in all categories. there will likely never be any implementation that has 1.00 across the board. each metric is ranked in isolation, which makes the proposed approach conisistent with how it already works.

**Comment by leeoniya** [comment]
i'm not sure if script-only is a good metric. i do think that "everything except baseline reflow+restlyle+repaint" is what we need. the difference for swap total vs only-js does not capture the extra ~110ms of DOM/GC inefficiency in the latter:

![image](https://user-images.githubusercontent.com/43234/236927868-83581316-5a72-4c8e-9491-646272ce31e9.png)

vs js-only:

![image](https://user-images.githubusercontent.com/43234/236928076-debd9f31-b47b-4f98-bc27-e2c3193dd329.png)

**Comment by ClassicOldSong** [comment]
As the author of ef.js, I lost my first place of swap rows in only-js, that's not good 😈

Kidding, but I agree that GC time should be taken account into scripting.

And still, what baseline should we take for reflow+restlyle+repaint?

**Comment by leeoniya** [comment]
> And still, what baseline should we take for reflow+restlyle+repaint?

whatever implementation is fastest in reflow+restlyle+repaint for each metric.

**Comment by krausest** [comment]
I came back to that issue. We have an established way to compute total duration (end of paint - start of click). I created a way to measure JS duration (sum of the duration of all events that are   "EventDispatch",  "EvaluateScript",  "v8.evaluateModule",  "FunctionCall",  "TimerFire",  "FireIdleCallback",  "FireAnimationFrame",  "RunMicrotasks",  "V8.Execute"). This gives the table above. And it seems to be close to what chrome displays as scripting.

If Browser-ony meant total duration minus js duration results get odd. Miso is fastest for create 1k with 56 msecs total duration, 23 msecs js duration (giving 33 msecs browser only), whilst vanillajs has 39 msecs total duration and 2 msecs js duration which gives 39 msecs browser only. Sorted by create 1 k the table looks like that:
![Screenshot 2023-11-25 at 10 38 55 AM](https://github.com/krausest/js-framework-benchmark/assets/3374055/3f75dc46-9397-4b3d-b35b-1d7688b850d0)

It seems to make little sense for create 1,000 rows. Some benchmarks are a little more interesting like remove row:
![Screenshot 2023-11-25 at 6 47 15 PM](https://github.com/krausest/js-framework-benchmark/assets/3374055/cc961070-0041-408f-b5c3-374c5ad96bba)

Maybe it makes more sense to compute the lengths of all painting and layout intervals as a third factor? 

The current results table lets one play with the three options.

**Comment by krausest** [comment]
I added a "only render duration" selection. It computes the duration as the sum of all intervals for the   "UpdateLayoutTree",   "Layout",  "Commit",  "Paint",  "Layerize",  "PrePaint" events.

I haven't had the time to do a big quality check yet, so please take the results with a grain of salt.

**Comment by krausest** [comment]
I ran a check that total time >= script time + paint time. That assertion holds for most runs, except 21 traces (openui is causing 15 of those for replace rows. All other cases are below 1 msec difference, so they don't matter much). The trace looks like that:
![Screenshot 2023-11-26 at 11 20 45 AM](https://github.com/krausest/js-framework-benchmark/assets/3374055/3bbbe6e5-dbfe-4558-8070-c9fb7c035cee)
My interval logic computes:
total duration=45.898 
script duration=23.182 
paint duration=32.722
Those numbers look right, but sum script + paint is misleading though.

**Comment by krausest** [comment]
The result table allows to choose total duration, only JS duration and render duration.
