### ISSUE TITLE
± 95% confidence interval

### ISSUE THREAD

**Issue by eirnym** [krausest/js-framework-benchmark#1255]
I understand what does mean "95% confidence interval" or "5% measure error".

As `±` implies, value could be positive or negative, could you please, explain what does  "negative confidence interval" mean?

If it was used incorrectly, please, use a correct message

**Comment by krausest** [comment]
± 5 doesn't mean that 5 can be either positive or negative.
The 95% confidence interval is given by the mean and goes from mean - value to mean + value.
