### ISSUE TITLE
Updating current.html

### ISSUE THREAD

**Issue by fabiospampinato** [krausest/js-framework-benchmark#1260]
The current.html table seems to show results from a few updates ago.

**Comment by krausest** [comment]
Sorry, I think I don‘t see the issue. current.html shows the same numbers as the official 113 run and arrowjs is included (the last merged PR)
![IMG_0099](https://user-images.githubusercontent.com/3374055/236732080-fa408ff0-0f70-49a1-a349-c76af1389afa.jpeg)
Do you see the same numbers? If so where‘s the problem? Or are you getting a cached version?

**Comment by fabiospampinato** [comment]
Ah sorry for some reason I thought I had submitted a PR for v0.50 of Voby 🤣 my bad!
