### ISSUE TITLE
Add Rivets.js

### ISSUE THREAD

**Issue by NunoCruzSW** [krausest/js-framework-benchmark#127]

**Comment by krausest** [comment]
Interested in submitting a PR?

**Comment by bel3atar** [comment]
What about svelte and moon?

**Comment by krausest** [comment]
Svelte is already there. I'm currently preparing the next round. If you're interested I'm looking forward to receiving a pull request for moon and rivets.js, but won't add them myself otherwise.

**Comment by krausest** [comment]
Rivets has been added in #347. Sadly rivets seem to be non-keyed only.
