### ISSUE TITLE
svelte4 is release, it's time to add it to compare benchmark

### ISSUE THREAD

**Issue by athxx** [krausest/js-framework-benchmark#1276]
svelte4 has already been released, Svelte 4 is now available, offering smaller and faster code hydration for better performance. I think it's time to put Svelte v4 on the benchmark test.

Svelte 4 reduces the Svelte package size by nearly 75%, from 10.6MB to 2.8MB, translating to less waiting on npm install. This will be especially noticeable for users of the Svelte REPL, users with limited connectivity, and users loading the [learn.svelte.dev](https://learn.svelte.dev/tutorial/welcome-to-svelte) interactive learning experience for the first time, the Svelte team said.

**Comment by maxmilton** [comment]
There's already an existing PR; https://github.com/krausest/js-framework-benchmark/pull/1274
