### ISSUE TITLE
Why are the Official results and Snapshot of the results inconsistent?

### ISSUE THREAD

**Issue by maomincoding** [krausest/js-framework-benchmark#1294]
Why are the Official results and the Snapshot of the results inconsistent? The Snapshot of the results will be earlier than the Official results. Is it true that Official results need more stringent testing before there is a deviation in time?

**Comment by aclueless** [comment]
Copied from https://krausest.github.io/js-framework-benchmark/current.html

> Warning: These results are preliminary - use with caution (they may e.g. be from different browser versions).

and from README:

> The current snapshot that may not have the same quality (i.e. results might be for mixed browser versions, number of runs per benchmark may vary)

Snapshot contains results from many different runs at different times. Each run just for a small number of frameworks ([this commit](https://github.com/krausest/js-framework-benchmark/commit/2cc5baae54eff7bc2e95cc94d2075bda4b068cfa) just run benchmark for vue, svelte, lwc, solid and add metron). The browser on the benchmark machine may get updated to a new version before merging (and running the benchmark) of the waiting PRs.

Official results guarantee all frameworks run on the same version of browser, and all with the same arguments....

**Comment by maomincoding** [comment]
Thanks.
