### ISSUE TITLE
Element not found leads to benchmarks not being run

### ISSUE THREAD

**Issue by sanleesa** [krausest/js-framework-benchmark#1309]
I encountered this error for a lot of frameworks. I may have missed a setup step but I can't figure it out. I really do apologise if this is a dumb question.
`initBenchmark
checkElementExists element pierce/#run not found
checkElementExists element pierce/#run not found
checkElementExists element pierce/#run not found
checkElementExists element pierce/#run not found
checkElementExists element pierce/#run not found
checkElementExists element pierce/#run not found
checkElementExists element pierce/#run not found
checkElementExists element pierce/#run not found
checkElementExists element pierce/#run not found
checkElementExists element pierce/#run not found
checkElementExists waited 7147 but no luck`
Thank you for your time

**Comment by krausest** [comment]
If it happens for many framework, something isn't right with the server or the frameworks haven't been built. Can you check whether opening them in the browser works?
http://localhost:8080/frameworks/keyed/react/index.html
Some use another URI according to package.json like
http://localhost:8080/frameworks/keyed/angular/dist/angular/index.html

**Comment by sanleesa** [comment]
Hello, I looked into the build folder for Chrome 114. It seems that the zip file I downloaded was corrupted in some way. I downloaded the build zip again and unzipped it. Now, everything works fine. Thank you.

**Comment by sanleesa** [comment]
Hello, I looked into the build folder for Chrome 114. It seems that the zip file I downloaded was corrupted in some way. I downloaded the build zip again and unzipped it. Now, everything works fine. Thank you.
