### ISSUE TITLE
React is much faster with esbuild than with webpack

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1315]
PR #1292 changed the react build process from webpack to esbuild and have no significant code change.
It turned out that react is much faster with esbuild.
I had to take a closer look and run both versions in parallel.
The Italian flag below shows the comparison view and every benchmark is significantly faster for esbuild
<img width="336" alt="Screenshot 2023-07-20 at 8 48 25 PM" src="https://github.com/krausest/js-framework-benchmark/assets/3374055/bb9d83ab-6946-4135-9d66-58dceccae9ec">

**Comment by krausest** [comment]
Can also be seen when looking at the performance tab:
<img width="1111" alt="Screenshot 2023-07-20 at 8 55 34 PM" src="https://github.com/krausest/js-framework-benchmark/assets/3374055/c8a829b7-1e79-4526-9451-1914359fd6a5">
Seems to be mostly due to different scripting duration.

**Comment by krausest** [comment]
The difference as seen by a boxplot for create rows - impressive...
<img width="474" alt="Screenshot 2023-07-20 at 8 59 14 PM" src="https://github.com/krausest/js-framework-benchmark/assets/3374055/d40959f2-7b28-416e-b452-7a1a68626780">

**Comment by krausest** [comment]
Same for react-hooks:
<img width="315" alt="Screenshot 2023-07-20 at 9 16 33 PM" src="https://github.com/krausest/js-framework-benchmark/assets/3374055/8dc6a93c-264d-4ed0-a35f-971afdd9c3fc">
No difference here. Really strange. Select row is on the level of react-esbuild at least.

**Comment by krausest** [comment]
I tried for other react implementations that are a bit slow for select row. esbuild doesn't help them.
<img width="620" alt="Screenshot 2023-07-20 at 10 18 31 PM" src="https://github.com/krausest/js-framework-benchmark/assets/3374055/043e6858-f1c8-47de-b70e-643f6200efc1">

**Comment by ged-odoo** [comment]
This is interesting. does anyone have an explanation? Maybe it could be that esbuild or webpack wraps some code in a closure?

**Comment by eneajaho** [comment]
> This is interesting. does anyone have an explanation? Maybe it could be that esbuild or webpack wraps some code in a closure?

Looks like Angular benefits from it too: https://github.com/krausest/js-framework-benchmark/pull/1357
