### ISSUE TITLE
Add AngularDart

### ISSUE THREAD

**Issue by tristancaron** [krausest/js-framework-benchmark#134]
Hello,

I've been working on a Dart version of the benchmarks, but I was not able to run selenium with it. 

I think I could be interesting to add it.

![capture d ecran 2017-02-23 a 23 01 24](https://cloud.githubusercontent.com/assets/9624669/23281077/06dba2fe-fa1c-11e6-9e95-93a75491e1ee.png)

**Comment by krausest** [comment]
If you send me a PR I can take a look at it and try to fix it when I'm back from holidays.

**Comment by tristancaron** [comment]
Ok I will work on it. Thank you, and enjoy your holidays 👍

**Comment by krausest** [comment]
Closing this issue. You can send me (even an unfinished) PR..
