### ISSUE TITLE
Vue2.6 has many more users than vue3, and they may stay in vue2.6 forever, it is recommended to keep the benchmark of vue2

### ISSUE THREAD

**Issue by xxxxue** [krausest/js-framework-benchmark#1346]

**Comment by krausest** [comment]
As far as I know "Vue 2 will reach End of Life (EOL) on December 31st, 2023." (https://v2.vuejs.org/lts/)
So I'd say staying forever isn't an option.

**Comment by xxxxue** [comment]
> As far as I know "Vue 2 will reach End of Life (EOL) on December 31st, 2023." (https://v2.vuejs.org/lts/) So I'd say staying forever isn't an option.

Vue2 and Vue3 are not the same framework, they are not compatible with each other, only have similar names
The past five years have been the fastest growing period for Vue, with many company projects using Vue2,
They may not upgrade to Vue3 in the next 10 years,

**Comment by krausest** [comment]
I can't imagine any company with a it security officer (or with customers that have one) would accept using a framework the reached EOL for a longer time. I don't think there's a need to benchmark frameworks that reached EOL.
