### ISSUE TITLE
replace static index.html

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1364]
Instead of the old statically created index.html it would be much better to create the index.html dynamically via the server.

**Comment by krausest** [comment]
@nakrovati If you want I'd welcome a PR on top of #1342 very much...

**Comment by nakrovati** [comment]
Do you mean to do a build by invocation via URL, like `/ls/create-index`? I'm not quite sure what "dynamically" means in the context of the server.

**Comment by krausest** [comment]
Yes, I'd say "/" and "/index.html" would be great URIs (and would be backward compatible). The index route would reuse the /ls logic to find the frameworks and versions and create the index.html via the templates that currently reside in webdriver-ts.

**Comment by nakrovati** [comment]
Got it, I'll do it soon.

**Comment by nakrovati** [comment]
By the way, I fixed the fastify server, check out the fix.

**Comment by krausest** [comment]
Thanks!
