### ISSUE TITLE
retire docker support

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1367]
I'm currently not using the docker builds anymore, since docker didn't work well on OSX/arm64. This and for security reasons I prefer to build on a VPS and run the benchmark driver locally on my OSX machine.
I think there's a good chance that the docker files are broken meanwhile. They should be removed (including any docker options in the build files).

**Comment by nakrovati** [comment]
Dockerfile is definitely broken as I fixed it over the summer and there were bugs in NVM installation, Node, Rust and many other places. Too bad I forgot to create a PR.
