### ISSUE TITLE
Switching from Webpack to Vite

### ISSUE THREAD

**Issue by nakrovati** [krausest/js-framework-benchmark#1370]
@krausest 

### About the problem

There is a problem with switching to vite. The vite-plugin-singlefile plugin in this case collects `plotly` and `BoxPlotTable` into one 2mb file.
I manually split everything into chunks using vite and added via the `inlinePattern` property in vite-plugin-singlefile, but it seems this plugin doesn't work together with `manualChunks`.

The output is:
- Either leave webpack, but lose acceleration from 10s to 0.5s for `dev` and from 40s to 10s for `build`. And the possibility of simple integration with million.js. 
- Or generate 1 big HTML file for 2mb.
- Or we don't build everything in one file and output files as is, but without `dev` server it will be impossible to view `table.html` (because of cors).

### How can we fix it

You can change the logic of the site a bit:
- For `/[year]/*` give them as they are shared by vite (now it seems exactly the same, only built with webpack)
- For `/current.html`, build one big HTML file (which I will reduce later by replacing plotly with D3), or build by default vite in `current` directories, which can be accessed by `/current/` route.

### SSG site build

You could also do an SSG site. Store the results of new benchmarks in `.json` and use Astro.js in SSG mode to generate a page for each benchmark. For old benchmarks you can make a redirect, if there are no `.json` files with results, and if there are, do the same for them. Then you can build the whole site at once from Vite, without worrying about manual creation of chunks and directory structure on the server. You can also set up GitHub Actions to automatically deploy the site to GitHub Pages when you publish a new release.

P.S: I'm getting a new 16-inch laptop soon, so I'll be able to move the site to Astro (+ react or svelte).

**Comment by leeoniya** [comment]
i would be willing to implement something atop the 50kb uPlot ;)

i have most of the code done already in a demo: https://leeoniya.github.io/uPlot/demos/box-whisker.html

**Comment by nakrovati** [comment]
Wow, 50kb. I would rewrite everything to it, just along with the complete webdriver-ts-results rework.

**Comment by leeoniya** [comment]
heh, not too much [1] :rofl:, but it's pretty straightforward.

[1] https://github.com/leeoniya/uPlot/tree/master/docs

**Comment by nakrovati** [comment]
Really simple. I want to decide about migrating to vite first, and then replace plotly and wait for my laptop to arrive to work properly.

@leeoniya By the way, kudos to you for the fuzzy library, I met it at work.
