### ISSUE TITLE
failure building any frameworks on fresh clone

### ISSUE THREAD

**Issue by sethp** [krausest/js-framework-benchmark#1387]
# What I did:

1. `git clone https://github.com/krausest/js-framework-benchmark.git`
2. Per the README, `npm ci && npm start` at the root
3. `npm run build-prod`

# What I saw:

An immediate failure on the first framework `keyed/1more`, indicating that `npm ci` was being run without a resolved `package-lock.json`:

```
> js-framework-benchmark@1.0.0 build-prod
> node rebuild-all.js --ci

ARGS { _: [], ci: true, '$0': 'rebuild-all.js' } ci true restartWith 
Building framework: { name: '1more', type: 'keyed' }
Deleted: yarn-lock,dist,elm-stuff,bower_components,node_modules,output,package-lock.json
npm ci
npm ERR! code EUSAGE
npm ERR! 
npm ERR! The `npm ci` command can only install with an existing package-lock.json or
npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
npm ERR! later to generate a package-lock.json file, then try again.
npm ERR! 
npm ERR! Clean install a project
npm ERR! 
npm ERR! Usage:
npm ERR! npm ci
npm ERR! 
npm ERR! Options:
npm ERR! [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
npm ERR! [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
npm ERR! [--strict-peer-deps] [--foreground-scripts] [--ignore-scripts] [--no-audit]
npm ERR! [--no-bin-links] [--no-fund] [--dry-run]
npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
npm ERR! 
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR! 
npm ERR! Run "npm help ci" for more info

npm ERR! A complete log of this run can be found in: /home/seth/.npm/_logs/2023-09-30T14_40_12_365Z-debug-0.log
node:internal/errors:865
  const err = new Error(message);
              ^

Error: Command failed: npm ci
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at runCommand (file:///home/seth/Code/src/github.com/krausest/js-framework-benchmark/rebuild-all.js:79:3)
    at buildFramework (file:///home/seth/Code/src/github.com/krausest/js-framework-benchmark/rebuild-all.js:120:3)
    at buildFrameworks (file:///home/seth/Code/src/github.com/krausest/js-framework-benchmark/rebuild-all.js:135:5)
    at file:///home/seth/Code/src/github.com/krausest/js-framework-benchmark/rebuild-all.js:141:1
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:308:24)
    at async loadESM (node:internal/process/esm_loader:42:7) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1543150,
  stdout: null,
  stderr: null
}

Node.js v20.6.1
```

# versions, thoughts, vibes

I'm not sure if it matters, but here's some potentially relevant collected versions of things:

```bash
$ node --version
v20.6.1
$ npm --version
10.1.0
$ git --no-pager log --oneline -1 HEAD
4e087978 (HEAD -> master, origin/master, origin/HEAD) add alins, rezact
$ uname -a
Linux box 6.5.5-1-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Sep 23 12:48:15 UTC 2023 x86_64 GNU/Linux
```

I noticed that the `rebuild-all.js` script is currently deleting the package-lock.json on purpose: https://github.com/krausest/js-framework-benchmark/blob/4e087978da0f851d5e1aee42e727b562bd7b145e/rebuild-all.js#L50

I'm not very familiar with the `npm` tool, would you help me understand the intent of deleting the `package-lock.json` there before running `npm ci`? I tried inverting the logic to be `!useCi` and then `npm run build-prod` seems to make more progress, but I have the sense that I'm looking at something different than y'all's usual flow.

**Comment by krausest** [comment]
Ah, sorry. Looks like this happened due to a recent refactoring.
Please restore the  package-lock.json in 1-more:
`git restore frameworks/keyed/1more/package-lock.json`
I added in the README, that after `npm ci` one has to run `npm run install-server` then `npm start`.

I fixed the build script and your diagnosis was absolutely right. Please update the build files via `git pull`.

I haven't tried building with node 20. It might be that installing with v20 fails for some frameworks, currently the node LTS version 18.x is recommended.

**Comment by krausest** [comment]
Just tried again. Building with node v20.8.0 worked.
