### ISSUE TITLE
Incorrect selection functionality: mikado

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1407]
xania was found in #1379 to handle select rows incorrectly. It selects the new row, but keeps the old rows selected. The correct functionality is that at most one row may be selected.

mikado is also affected from this issue. @ts-thomas can you please fix it? For the meantime I'll move mikado into the broken-frameworks directory.

I'll keep chrome 118 results back until next week such that you have a chance to fix it.

**Comment by krausest** [comment]
Seems only the keyed version is affected, non-keyed looks good.

**Comment by ts-thomas** [comment]
Thanks for the hint. Your are absolutely right, it was my mistake, I overseen this part:

```js
.route("select", target => view.refresh(view.selected = view.index(target)));
```
it just refreshes one single index. It also needs to refresh the old index like:

```js
// ...
.route("select", target =>{ view.selected = view.index(target); view.refresh(old_index, view); view.refresh(new_index, view) });
```

I will commit a fix for this. Also there is a new generation of Mikado in the pipeline, probabaly I will replace the whole test to the new version in one step.

**Comment by krausest** [comment]
Fixed in new version.
