### ISSUE TITLE
Chrome 118 results are delayed

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1411]
Chrome 118 results will take a few more days. I had to split keyed and non-keyed to keep the runtime duration acceptable. Sadly I noticed that four implementations had a bug in the row selection code. I think it's fair to wait a few days for a fix rather than exclude them from the results.

Anyway here are preliminary results for the keyed frameworks:
https://krausest.github.io/js-framework-benchmark/2023/table_chrome_118_preliminary.html

This will be the first results with the new duration computation logic as described on https://github.com/krausest/js-framework-benchmark/wiki/How-the-duration-is-measured

**Comment by maomincoding** [comment]
Looking forward to it very much！
