### ISSUE TITLE
non-keyed/fre is broken

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1426]
Test create 10,000 rows suddenly fails for non-keyed/fre. I thought the test driver had an issue, but it doesn't. Fre doesn't create 10,000 rows!

![Screenshot 2023-10-16 at 9 23 30 PM](https://github.com/krausest/js-framework-benchmark/assets/3374055/632f2200-bd0d-4302-b863-9600c7952606)
![Screenshot 2023-10-16 at 9 23 44 PM](https://github.com/krausest/js-framework-benchmark/assets/3374055/ba42a2b7-dcd7-454b-a58a-8d160455ff5c)

The implementation was moved to broken-frameworks/non-keyed

@yisar Can you take a look at it, please?

**Comment by yisar** [comment]
I'm sorry, I'm currently busy with my studies and it's difficult for me to have time to update the code of fre. You can delete the fre first and resubmit it when I have time.
