### ISSUE TITLE
Add marko.js

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#147]
Marko sounds interesting - I should add that...

**Comment by krausest** [comment]
@psteeleidem: I added a first implementation of marko. Do you think you might find the time to check whether the implementation doesn't work against marko?

I found marko to be very straight forward to implement. The only issues I had was making it work as a keyed implementation (the id of the row should be used and I ended up with key='${item.id}') and I would have hoped to find a clear explanation how rerendering is triggered (the current implementation rerenders by assigning a new array to the state - is that the recommended way?)
The first results are [here](https://rawgit.com/krausest/js-framework-benchmark/18bf49bcc640a1a944d4e81633e88488d54919ce/webdriver-ts/table.html).

**Comment by patrick-steele-idem** [comment]
/cc @mlrawlings @austinkelleher 

Thanks for working on the first pass at adding Marko, @krausest. This is something we have been planning on working on. After a quick glance, I do see some things that I would like to change. We'll try to send a PR sometime this week.

**Comment by krausest** [comment]
Thanks - closed by #152.
