### ISSUE TITLE
Aurelia package.json uses rimraf without installing it

### ISSUE THREAD

**Issue by qm3ster** [krausest/js-framework-benchmark#150]
`/aurelia-v1.1.0/package.json` has `"clean:dist": "rimraf dist"` in scripts but doesn't install it.
Not a PR because not sure if it should go in dependencies or devDependencies.

**Comment by krausest** [comment]
You're right - I've added it explicitly in 1d503e17eee3b9c832ec0e2d78fa4a7b6c7f8ec6. But it should have worked anyways. Did you run into problems with it? 
```npm ls rimraf
js-framework-benchmark/aurelia-v1.1.0
└─┬ karma@1.5.0
  ├─┬ chokidar@1.6.1
  │ └─┬ fsevents@1.1.1
  │   └─┬ node-pre-gyp@0.6.33
  │     └── rimraf@2.5.4
  └── rimraf@2.6.1
```

**Comment by qm3ster** [comment]
I didn't have it installed globally, and the root build-prod failed on aurelia.

**Comment by krausest** [comment]
Some questions such that I understand the issue better: rimraf is a dependency of karma and should be installed in aurelia-v1.1.0/node_modules/rimraf (and it is on my machine)
Did you see that folder there? If so why wouldn't it run from package.json?

**Comment by qm3ster** [comment]
Even if I do `npm run build-prod` inside `cd aurelia-v1.1.0/` it doesn't work in https://github.com/krausest/js-framework-benchmark/commit/09d0d371824c4608e8bb0f8f6acdd2324520d137.
However if I `rm -rf node_modules/ && npm install` inside `cd aurelia-v1.1.0/`, even `yarn run build-prod` starts working. Really confusing.
I am using npm 4.4.4 and yarn 0.21.3

**Comment by krausest** [comment]
Ok - I found something could be https://github.com/yarnpkg/yarn/issues/760
If installed with yarn rimraf was installed in aurelia-v1.1.0/node_modules, but no link in .bin was created (but in node_modules/karma/node_modules/.bin).
Installing with npm works fine - it creates the executable in .bin for transitive dependencies.
Anyways it should work now.

**Comment by qm3ster** [comment]
Seems like that is exactly what's happening.
Maybe they are not supporting this feature for political reasons, since the idiomatic way is to have a direct dependency if your script needs it. They are also known to optimize at the expense of compatibility, for example when `yarn clean` includes nuking all .yaml files in `node_modules`, since they expect all 'decent' packages to bundle default options in and not use a parser by default at runtime.
