### ISSUE TITLE
Please add jQuery if just for completion 

### ISSUE THREAD

**Issue by rotaercz** [krausest/js-framework-benchmark#1504]
I noticed there's no jQuery in the benchmark. It would be awesome to see from a historical standpoint on how much frameworks have improved in terms of performance compared to old grandfather jQuery.

**Comment by leeoniya** [comment]
https://github.com/krausest/js-framework-benchmark/issues/126#issuecomment-280425089

**Comment by krausest** [comment]
We had that discussion. It makes little sense to add minimal wrappers over dom opertations, there's already vanillajs.
