### ISSUE TITLE
.NET 8 Released

### ISSUE THREAD

**Issue by zahirtezcan-bugs** [krausest/js-framework-benchmark#1509]
This is a reminder and may very well be ignored :)

.NET 8 is [released last week](https://github.com/dotnet/core/blob/v8.0.0/release-notes/8.0/8.0.0/8.0.0.md?WT.mc_id=dotnet-35129-website), there seem to be improvements in [Blazor](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?view=aspnetcore-8.0) and [Native AoT](https://devblogs.microsoft.com/dotnet/announcing-asp-net-core-in-dotnet-8/#asp-net-core-support-for-native-aot) side of things. You may want to update the related benchmarks.

**Comment by birkskyum** [comment]
@zahirtezcan-bugs , you can see in #1511 that there was some improvements.
