### ISSUE TITLE
doohtml should be flagged #801

### ISSUE THREAD

**Issue by ts-thomas** [krausest/js-framework-benchmark#1563]
https://github.com/krausest/js-framework-benchmark/blob/master/frameworks/keyed/doohtml-dom/js/Main.class.js#L35
https://github.com/krausest/js-framework-benchmark/blob/master/frameworks/keyed/doohtml/js/Main.class.js#L38

**Comment by ts-thomas** [comment]
@krausest 
This implementation should be moved into "broken frameworks":
https://github.com/krausest/js-framework-benchmark/blob/master/frameworks/keyed/doohtml/js/Main.class.js#L40
https://github.com/krausest/js-framework-benchmark/blob/master/frameworks/keyed/doohtml/js/Main.class.js#L94
https://github.com/krausest/js-framework-benchmark/blob/master/frameworks/keyed/doohtml/js/Main.class.js#L100
https://github.com/krausest/js-framework-benchmark/blob/master/frameworks/keyed/doohtml/js/Main.class.js#L110
https://github.com/krausest/js-framework-benchmark/blob/master/frameworks/keyed/doohtml/js/Main.class.js#L118

Its not comparable and also cannot called "library" or "framework". I can't understand why it is listed. Where is the Leonie guy when he is needed?

**Comment by ts-thomas** [comment]
I don't have any issues opened as long. It it just not that important, it is just a matter of reliability of this benchmark ;)

**Comment by enzoaicardi** [comment]
I'm agree doohtml & doohtml-dom (and every doo.*) should be archived, removed or tagged as broken.
1 year after i don't know why it is still listed...

**Comment by krausest** [comment]
I guess @hman61 has good arguments why doohtml should be kept in here.
