### ISSUE TITLE
The test "total kilobyte weight" might not cover assets cached by service worker

### ISSUE THREAD

**Issue by ts-thomas** [krausest/js-framework-benchmark#1568]
I just recognize a result of 142.1 (1.00) for the library "anansi" in the category "total kilobyte weight". 
This library uses service worker here: https://github.com/krausest/js-framework-benchmark/blob/master/frameworks/keyed/anansi/js-framework-wasm/main.js#L5
And here the service worker asset cache will be filled: https://github.com/krausest/js-framework-benchmark/blob/master/frameworks/keyed/anansi/js-framework-wasm/sw.js#L3

It looks like the test don't cover those assets?

**Comment by krausest** [comment]
Yes, it seems like lighthouse allows caching. This is why I introduced the transferred Size table. Here I prevent caching (and I can reason about the reported values). See #1340 for more information.
I guess it's time to retire that lighthouse metric in the next official results.

**Comment by ts-thomas** [comment]
Thanks a lot 👍
