### ISSUE TITLE
hydro-js is broken

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#1586]
@Krutsch I had to move hydro-js to the broken-frameworks folder.
Suddenly it stopped working an prints the following error on the console:
![Screenshot 2024-01-26 at 5 22 21 PM](https://github.com/krausest/js-framework-benchmark/assets/3374055/ba4e5fde-80be-48d9-a83d-53dae2b52aff)
I tried to install the strict version from package.json, but it didn't help either.

**Comment by Krutsch** [comment]
Thanks for letting me know!
I will have a look later and will open a PR then.
