### ISSUE TITLE
Add "Fresh" web framework.

### ISSUE THREAD

**Issue by JamesClarke7283** [krausest/js-framework-benchmark#1606]
I would be curious to see how well the ['Fresh'](https://fresh.deno.dev/) web framework runs, against your benchmarks.
It uses the islands architecture and runs on the Deno, JS runtime.

Most comprehensive web framework benchmarks ever! thanks, keep up the good work.

**Comment by birkskyum** [comment]
@JamesClarke7283 , you can evaluate the performance of Fresh by looking up the entries for Preact. Fresh uses Preact for client side reactivity, so it would give the same score.
