### ISSUE TITLE
add "no-op" redraw timings

### ISSUE THREAD

**Issue by leeoniya** [krausest/js-framework-benchmark#163]
@krausest it may be useful to have a metric for simply exercising the libs without any resulting dom mutations.

basically, what does it cost to do a no-op redraw of 10k rows? this would force a vtree rebuild, diff/patch and reconciliation passes. it may turn out that the numbers directly track the current results, but alternatively may help to reveal whether any slowness is the result sub-optimal dom ops or in the libs' internals.

thoughts?

**Comment by localvoid** [comment]
And how KVO libs should behave in this scenario?

**Comment by leeoniya** [comment]
i imagine they would come out well ahead, as they should.

**Comment by localvoid** [comment]
So, then it would be fair to use sCU in vdom implementations to track changes, and no-op scenario won't measure anything.

**Comment by leeoniya** [comment]
many impls already use some form of sCU (including ivi i think [1]).

sCU can make a no-op redraw basically free if the store is deeply-immutable and the view layer can take advantage of this by doing a cheap `===` diff with sufficient granularity. for instance, domvm's current impl has no top-level diff and does not rely on the store being immutable. i do get your point though. i could easily rewrite the store to act in an immutable way from top to bottom and take advantage of this to have a "free" redraw after a trivial top-level `===` diff.

[1] https://github.com/krausest/js-framework-benchmark/blob/master/ivi-v0.5.0/src/main.js#L125

**Comment by krausest** [comment]
I'm not yet convinced I should add that (and I have no idea how to do it in a meaningful way for all frameworks with their different store paradigms...). The duration should be short enough to prevent a reliable measurement.
Isn't the select row benchmark a good enough approximation for a no-op? It's easy to spot the frameworks that are doing too much work in that case.

**Comment by leeoniya** [comment]
> Isn't the select row benchmark a good enough approximation

yep, makes sense.
