### ISSUE TITLE
How can I add a new framework?

### ISSUE THREAD

**Issue by kavoos** [krausest/js-framework-benchmark#165]
Hi, 
Maybe it's not really an issue, but I just wondering how I can add a new framework in order to have its result as well?

**Comment by leeoniya** [comment]
https://github.com/krausest/js-framework-benchmark#how-to-contribute

**Comment by krausest** [comment]
@kavoos Please let me know if the steps @leeoniya  mentioned are unclear or something essential is missing (A PR for the README would be nice in that case).

**Comment by kavoos** [comment]
@krausest thanks, I'll try it first and let you know. Would you please how could I contact you just in case? this is my email: kavoos.boloorchi@gmail.com 
Please send me a blank email if you don't want to put it here.

**Comment by krausest** [comment]
@kavoos Simply open an issue in that case.

**Comment by kavoos** [comment]
@krausest , Just a small question. what is that number after each +/-? 
for example Angular-v1.6.1 has  
> 254.72  +/- 5.59 (1.96)

for creation of 1000 rows. What does "5.59" mean?

**Comment by leeoniya** [comment]
each benchmark runs several times. the blmain number is the average duration in ms and +/- is the variance (or error margin/tolerance)
