### ISSUE TITLE
Feature request: page size 50|1000

### ISSUE THREAD

**Issue by whittet** [krausest/js-framework-benchmark#1671]
Hi, congrats on Chrome 124 release!

Current page size is good for academic papers. Could you please run this benchmark for page size 50? A drop down picking the report size would be awesome. For now, 50 and 1000. In my opinion 50 or 1000 is sufficient, since business apps can implement this using paging, and/or virual paging for large data-sets. I'm curious if the reason React has such a high adoption is it is fast-enough and keeps context switching extremely low. Your tool is useful for furthering the future of these web stacks, but could also be useful for tech leadership to decide their day-to-day with this addition.

**Comment by krausest** [comment]
Sorry, I see no simple way to parametrize those values, but I suppose most frameworks would simply perform fast enough for 50 rows. Keep in mind that real applications might have more complex components in their 50 rows so maybe we're closer in terms of total count to those 1,000 rows...
