### ISSUE TITLE
Add newest version of inferno (3.1.0) I think

### ISSUE THREAD

**Issue by dessalines** [krausest/js-framework-benchmark#169]
https://github.com/infernojs/inferno

**Comment by krausest** [comment]
Updated in 8b614acd292d59eac3554a9c7c3fae821208cc3a.
Results are [here](https://rawgit.com/krausest/js-framework-benchmark/8b614acd292d59eac3554a9c7c3fae821208cc3a/webdriver-ts/table.html). I'm not sure if the difference to 1.6 is significant.
