### ISSUE TITLE
Vanilla version can be faster (maybe a lot)

### ISSUE THREAD

**Issue by leeoniya** [krausest/js-framework-benchmark#17]
Hi @krausest 

Here are some notes on boosting the vanilla impl.

get/setAttribute is slow, use node properties when available:

```
setAttribute("class") -> .className
elem.getAttribute("data-id") -> elem.dataset.id
elem.setAttribute("data-id") -> elem.dataset.id
```
```
elem.innerText -> elem.textContent (when creating) (wont boost perf, but is a better practice)
...and use elem.firstChild.nodeValue (when updating)
```

.childNodes is slow; firstChild, lastChild, nextSibling, previousSibling are fast.
```
tr.childNodes[0] -> tr.firstChild
tr.childNodes[1].childNodes[0] -> tr.firstChild.nextSibling.firstChild
```
```
removeAllRows() -> tbody.textContent = ""
```

createDocumentFragment is no longer necessary in modern browsers [1], it's actually slower than plain appendChild and insertBefore

the vanilla version uses event delegation, while many implementations instead attach 1000's of onclick handlers, this is not an apples-to-apples comparison, especially when the libs allow for event delegation (many do).

also, I noticed the vanilla version does not maintain the row highlight (is present) during mutations/appending, etc.

/$0.02

[1] https://github.com/trueadm/inferno/issues/223#issuecomment-224120028

**Comment by krausest** [comment]
Created a VanillaJS2 version in the repository where I tried to add your suggestions. I'll run it later and publish the results.

Row highlighting is fixed. The highlight should only be removed for clear, when deleting the highlighted row and when clicking on a create button.

You're right about the delegation vs. direct attachment. This benchmark can only validate if the framework's choice is good for large tables and thus will prefer delegation (but that doesn't make react the fastest ;-).

**Comment by krausest** [comment]
Preliminary results are [here](https://cdn.rawgit.com/krausest/js-framework-benchmark/f7e3f9336c8b20bea2f2073f8814dee7022bd3bf/webdriver-java/table_update.html)
