### ISSUE TITLE
Hotwire

### ISSUE THREAD

**Issue by kaznovac** [krausest/js-framework-benchmark#1701]
It would be nice to see Hotwire https://hotwired.dev benchmarked also

**Comment by krausest** [comment]
This benchmark works only for client side rendering, so I guess this request is like #1604.

**Comment by kaznovac** [comment]
the stimulus (part of the hotwire) https://stimulus.hotwired.dev you can create client side model, and implement operations from https://github.com/krausest/js-framework-benchmark/issues/1604#issuecomment-1944620348

but I agree with you this benchmark would probably converge with vanilajs
