### ISSUE TITLE
Verify choo 5 results

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#171]
I updated choo to version 5. [Results](https://rawgit.com/krausest/js-framework-benchmark/2923130afd1f85627ecac49fb9464dfa716fcbe4/webdriver-ts/table.html) are still pretty bad and need verification.

**Comment by krausest** [comment]
@rahulcs 
@yoshuawuyts
May I ask for your help? I'm definitely not confident of my choo-skills to publish those results. Is there some much faster implementation possible?

**Comment by yoshuawuyts** [comment]
I'm a bit tight on time right now; working on doing a whole bunch of
optimizations for choo itself haha - I'll share it in the choo IRC if
someone might want to take a stab at it (:

**Comment by krausest** [comment]
Fixed by #260
