### ISSUE TITLE
Update dio

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#172]
@thysultan 
Dio seems to have changed significantly such that I see little chances for updating it correctly myself. Are you interested in updating dio to the latest version?

**Comment by thysultan** [comment]
Yes, have a working(keyed) version of the new release here [https://rawgit.com/thysultan/dio.js/master/experiment/docs/examples/benchmark.html](https://rawgit.com/thysultan/dio.js/master/experiment/docs/examples/benchmark.html) Will send a PR in the coming days when i release.

**Comment by krausest** [comment]
Thanks - has been merged!
