### ISSUE TITLE
Update Vue version to 3.5

### ISSUE THREAD

**Issue by sreeharsha-rav** [krausest/js-framework-benchmark#1742]
Update for Vue 3.5 introduces significant changes in performance which would be interesting to check on the JS benchmarks.

> In 3.5, Vue's reactivity system has undergone another major refactor that achieves better performance and significantly improved memory usage (-56%) with no behavior changes. The refactor also resolves stale computed values and memory issues caused by hanging computeds during SSR.
> In addition, 3.5 also optimizes reactivity tracking for large, deeply reactive arrays, making such operations up to 10x faster in some cases.

**Comment by krausest** [comment]
Did that. I'm afraid I can't see much of an improvement for this benchmark:
<img width="320" src="https://github.com/user-attachments/assets/eccd1d7f-017e-4c75-84ee-aeb015871a73">
