### ISSUE TITLE
Add horizontal scrollbar to the website

### ISSUE THREAD

**Issue by aminya** [krausest/js-framework-benchmark#1746]
The website doesn't have a horizontal scrollbar anymore. How can I browse the slow frameworks?
https://krausest.github.io/js-framework-benchmark/2024/table_chrome_129.0.6668.58.html

**Comment by krausest** [comment]
It should be possible to scroll the tables horizontally (by touchpad or using the cursor after you clicked into the table). If it doesn't work please provide more details (OS, Browser).

**Comment by aminya** [comment]
I am on a desktop, so I don't have a touchpad. Is there a scrollbar I can use with a mouse? It doesn't show for me.

Linux, Edge

**Comment by krausest** [comment]
Checked on windows: There's a visible scrollbar. It's below the transferred size table, since all three tables are scrolled at once.
![Screenshot 2024-09-21 091353](https://github.com/user-attachments/assets/bc77106d-40c3-4fb3-ae64-295d5016d7cc)

**Comment by aminya** [comment]
For me the scrollbar is shown at the bottom of the last table, which is out of the screen

**Comment by krausest** [comment]
Does https://krausest.github.io/js-framework-benchmark/current.html work better for you?
The correct version should start with the text "Warning: These results are preliminary ", not that you are looking at a cached version.
