### ISSUE TITLE
NaN% and broken compare

### ISSUE THREAD

**Issue by yuri0sh** [krausest/js-framework-benchmark#1749]
Example table: https://krausest.github.io/js-framework-benchmark/2024/table_chrome_129.0.6668.58.html
When any framework is selected for comparison, the comparison metric is sometimes displayed as NaN%, also leading to the framework showing as "significantly slower" than itself (red instead of white)

Present on nearly all official benchmark pages, including the latest

<img width="426" alt="Screenshot 2024-10-01 at 15 39 55" src="https://github.com/user-attachments/assets/ad4e6b9f-bd2d-45de-9ff5-ea77a5e161bb">

**Comment by yuri0sh** [comment]
https://github.com/krausest/js-framework-benchmark/blob/3d0af4e7930160386e59a9617d94682facf25bc5/webdriver-ts-results/src/Common.ts#L504

standardDeviation on sets of size 1 is `undefined`, which then coalesces to zero before being divided by.

**Comment by krausest** [comment]
Thanks for reporting. I never noticed that, but the comparison only works for CPU results. 
I cherry picked your PR.
