### ISSUE TITLE
Update ractive

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#177]
Updating Ractive 0.8.9 -> 0.8.12
* Keyed works fine :white_check_mark:
* Non-keyed has a major issue: After deleting the first row, all remaining rows are labeled "1000". The non-keyed remove(idx) seems to confuse ractive. The keyed remove works as expected. :heavy_exclamation_mark:

Updating Ractive.edge :white_check_mark:
* I get a parse error for class-danger="{{~/selected === .id}}". Changing to class="{{selected === .id ? 'danger' : ''}}" fixed it.

**Comment by krausest** [comment]
@evs-chris Can you help? Is there a way to fix the non-keyed version or should we remove it?

**Comment by evs-chris** [comment]
:+1: I'll take a look at it and open a PR.
