### ISSUE TITLE
Update to angular 19 ? 

### ISSUE THREAD

**Issue by ngiakhanh96** [krausest/js-framework-benchmark#1786]
Can we update to angular 19 ?

**Comment by krausest** [comment]
Yeah, I plan to do so the next days

**Comment by krausest** [comment]
Here are my results (left new keyed results, right old keyed results).
<img width="877" alt="Bildschirmfoto 2024-12-10 um 19 35 15" src="https://github.com/user-attachments/assets/7536f6c8-453e-427d-bb10-e6175f2cf64a">
It was an incremental run where vanillajs and vanillajs-3 also scored a bit slower (0.3-0.4) than in the full run. So I'd say there's little to no change for the update.
Seems like provideExperimentalZonelessChangeDetection worsens performance in this benchmark though it helps with the transferred size.
