### ISSUE TITLE
Revive Svelte v4

### ISSUE THREAD

**Issue by webJose** [krausest/js-framework-benchmark#1806]
Hello!  These benchmarks are great, thanks!

How about reviving Svelte v4?  I'm dying to see how Svelte v5 compares to its predecessor.  I see Svelte Classic there, but it is being "upgraded" under the hood by v5.

**Comment by krausest** [comment]
No way 😄 I'm currently on a mission to update all versions. I can't afford keeping old versions around.

You can look at an comparison here:
https://github.com/krausest/js-framework-benchmark/pull/1494

**Comment by webJose** [comment]
Bro!  You're so mean to me! Haha.  Ok, I guess, but it's on you that I'll be sad for like 3 weeks straight.

Cheers.
