### ISSUE TITLE
Create a nicer result table

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#187]
Sorting, Filtering and switching between keyed and non-keyed would be nice.

**Comment by krausest** [comment]
First version is here for testing: 
https://rawgit.com/krausest/js-framework-benchmark/7ca95f7f707f4cbab8a2713092cad6c8cc65c247/webdriver-ts-results/result.html

**Comment by thysultan** [comment]
@krausest How does the rounding work? up/down, i.e before it might be something like 1.16, now 1.1 or 1.2?

**Comment by krausest** [comment]
Numbers should be converted to string with toFixed, which does the rounding. 1.16 should thus become 1.2. Did you spot something strange in the table?
I decided to reduce precision as the second decimal figure tends to vary between runs. This creates an image of precision that doesn't hold.

**Comment by thysultan** [comment]
Nothing strange, though it would be nice to have the un-rounded number in there in some way, maybe within `<small></small>` text.

**Comment by solkimicreb** [comment]
I think it is much needed and very welcome change :+1: . A few notes:

- It would nice to move the vanilla to be always the last or first item in the table (rest is perfect in ABC order).

- I think the final result (at the bottom of the table) should keep the old precision (does it deviate that much between runs?) and the sub results could use the reduced precision.

**Comment by thysultan** [comment]
> It would nice to move the vanilla to be always the last or first item in the table (rest is perfect in ABC order).

@solkimicreb I think this is already taken into account with the ability to sort the table by any of the row names(click)

**Comment by solkimicreb** [comment]
Thats true, I missed that ):

**Comment by krausest** [comment]
The geometric mean now has two decimals [again](https://rawgit.com/krausest/js-framework-benchmark/b965939f9a76f7975756c1a229f5618a6e5b989e/webdriver-ts-results/table.html).
