### ISSUE TITLE
A review for compare with framework (t-test) would be good

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#196]
The [new](https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html) result table has a compare frameworks feature. 
Would be nice if someone reviewed the [code](https://github.com/krausest/js-framework-benchmark/blob/2abf9e409f15f6f1fff980a98beb9912e608abd0/webdriver-ts-results/src/Common.tsx#!L216-L240) for the statistical test.

**Comment by Charles6666** [comment]
Yes this simple need to be off look like this☡

**Comment by brodybits** [comment]
> Would be nice if someone reviewed the [code](https://github.com/krausest/js-framework-benchmark/blob/2abf9e409f15f6f1fff980a98beb9912e608abd0/webdriver-ts-results/src/Common.tsx#!L216-L240) for the statistical test.

From a quick look I wonder if it would be practical to apply some judicious refactoring?

I wonder if there may be existing packages that can be used to remove a bunch of code from needed maintenance in general?

I wonder if it may be possible to identify some pieces of code that could be turned into reusable packages for the benefit of others?

As I said in #547 I think proper performance benchmarking is not so easy in general (hard to do right). Kudos to @krausest and others for the dedication and hard work on this project!
