### ISSUE TITLE
remove double-negative `nonKeyed: false` boolean trap

### ISSUE THREAD

**Issue by leeoniya** [krausest/js-framework-benchmark#209]
hey @krausest 

would you be opposed to inverting the boolean `nonKeyed` param in common.ts [1] and renaming it to `isKeyed` or similar? it's been bugging me for a good while.

on a related note, it may be a good idea to make all the names match `-keyed`/`-non-keyed` convention rather than leaving off `non-keyed` for some keyed implementations and vice-versa.

[1] https://github.com/krausest/js-framework-benchmark/blob/master/webdriver-ts/src/common.ts#L35

**Comment by krausest** [comment]
The former is no longer not fixed :laughing:
I'll try to rename the benchmarks the next days.

**Comment by leeoniya** [comment]
great!
