### ISSUE TITLE
Simulacra 2.1.5 fails to remove row

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#216]
Simulacra had a ^-version in package.json and resolved to 2.1.5 instead of 2.1.1, which doesn't respond  to remove row.
Circleci failed because of that benchmark 06_remove-one-1k.

**Comment by krausest** [comment]
@daliwali Can you take a look at it?

**Comment by daliwali** [comment]
Thanks for the notice -- I will have a look at it. In the tests and examples removing nodes works fine, so this seems very odd.
