### ISSUE TITLE
Null results 

### ISSUE THREAD

**Issue by jeffersonlcf** [krausest/js-framework-benchmark#224]
I am currently trying to run the single framework with the automated benchmark driver but I am getting null results from each run. What am I missing here?

```
after run  01_run1k 0 vanillajs-keyed
Entry {
  level: Level { name_: 'INFO', value_: 800 },
  message: 'http://localhost:8080/vanillajs-keyed/dist/main.js 0:1047 "add took 220.63999999999987"',
  timestamp: 1501676906215,
  type: '' }
**result [object Object]_01_run1k [ null, { type: 'paint', ts: 0, dur: 0, end: 0 }, null, null ]**
after initialized  01_run1k 0 vanillajs-keyed
after run  01_run1k 0 vanillajs-keyed
```

I believe that this is causing me the following error:

```
Benchmark failed
Writing screenshot error-vanillajs-keyed-30_startup.png
...\js-framework-benchmark\webdriver-ts\node_modules\selenium-webdriver\lib\promise.js:2634
        throw error;
        ^

TypeError: Cannot read property 'ts' of null
    at initBenchmark.then.then.results (...\js-framework-benchmark\webdriver-ts\dist\benchmarkRunner.js:209:77)
    at ManagedPromise.invokeCallback_ (...\js-framework-benchmark\webdriver-ts\node_modules\selenium-webdriver\lib\promise.js:1384:14)

```

Could anyone please help me to debug this problem?

**Comment by krausest** [comment]
That looks pretty strange to me. For some reason it seems like no events were reported by chrome. What chrome version are you using? What locale are you running on?

If you look at the output of [circle ci](https://circleci.com/gh/krausest/js-framework-benchmark/29) npm run check you should see something like that:

result [object Object]_01_run1k [ { type: 'click', ts: 58811927390, dur: 347802, end: 58812275192 },
  { type: 'paint', ts: 58812496598, dur: 3904, end: 58812500502 },
  { type: 'gc', ts: 58812501394, mem: 11.174888610839844 },
  null ]

To look further into your issue set     LOG_DETAILS: true and  LOG_DEBUG: true in webdriver-ts/src/common.ts . Then please run `npm run compile` in webdriver-ts and `npm run selenium -- --framework vanillajs-keyed --benchmark 01_ --count 1 > log.txt` and attach the log.txt file here.

**Comment by jeffersonlcf** [comment]
These are my current configurations:

**Google Chrome:** 59.0.3071.115 (Official Build) (64-bit) (cohort: Stable)
**OS:** Windows
**User Agent:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
**System Locale:** en-us;English (United States)

[log.txt](https://github.com/krausest/js-framework-benchmark/files/1202299/log.txt)

**Comment by krausest** [comment]
Thanks - that's really strange. The real timeline events are missing on your machine. Before the last but two line starting with `results` there should be a few hundred lines like the following:
```
{"message":{"method":"Tracing.dataCollected","params":{"args":{"number":8},"cat":"__metadata","name":"num_cpus","ph":"M","pid":19109,"tid":0,"ts":0}},"webview":"browser"}
{"message":{"method":"Tracing.dataCollected","params":{"args":{"sort_index":-1},"cat":"__metadata","name":"process_sort_index","ph":"M","pid":19109,"tid":19971,"ts":0}},"webview":"browser"}
{"message":{"method":"Tracing.dataCollected","params":{"args":{"name":"GPU Process"},"cat":"__metadata","name":"process_name","ph":"M","pid":19109,"tid":19971,"ts":0}},"webview":"browser"}

```
In webdriver-ts/src/benchmarkRunner.ts in the function initBenchmark the timeline events are cleared via a clearLogs call. This causes all the DISCARDED lines in your row, which looks ok.
But apparently in runBenchmark there's no new data from chrome's timeline available. To be honest: I have no clue why.
Maybe you can try to insert a `.then(() => driver.sleep(10000))` before `.then(() => readLogs(driver))` in
https://github.com/krausest/js-framework-benchmark/blob/5d09bc3faf517dac898f3c95d6ba9263dbc61e85/webdriver-ts/src/benchmarkRunner.ts#L140
This would wait 10 seconds before reading the chrome timeline (if it works you might reduce the sleep amount). Does that change anything?

**Comment by krausest** [comment]
Could it somehow be that you're using chromedriver >= 2.29? (maybe there's a global installed versoin)
I got the same behaviour yesterday when I updated chromedriver from 2.28.
So far I've no solution for it yet:
Here's someone with a similar problem:
https://stackoverflow.com/questions/44803636/not-receiving-timeline-data-in-performance-log

**Comment by krausest** [comment]
Here's the issue from chromedriver:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1811&q=&colspec=ID%20Status%20Pri%20Owner%20Summary&start=100

**Comment by jeffersonlcf** [comment]
Hi, @krausest!
Yes, apparently my Chromedriver version was the problem. I had a system environmental variable pointing to an updated version of my Chromedriver (v. 2.31). After I deleted this path and ensured that I was using version 2.28, everything went back to normal.
Thank you!

**Comment by krausest** [comment]
Closing in favour of #232
