### ISSUE TITLE
Incomplete CircleCI configuration

### ISSUE THREAD

**Issue by alexteves** [krausest/js-framework-benchmark#235]
- CI doesn't run on pull requests from forks
- Commit list doesn't show the build status

**Comment by krausest** [comment]
#1 should be fixed
Is #2 "GitHub Status updates"? If so they are set to on by now.

**Comment by alexteves** [comment]
> Is no. 2 "GitHub Status updates"? 
Think so.

Everything seems fixed. I'm closing this issue.
