### ISSUE TITLE
Why does VanillaJS use setTimeout in stopMeasure?

### ISSUE THREAD

**Issue by esprehn** [krausest/js-framework-benchmark#238]
https://github.com/krausest/js-framework-benchmark/blob/26367bcbe364ef6a6cde7cf0400009e617805efb/vanillajs/src/Main.js#L12

This means it's measuring timer clamping and other various things the browser might put in there. What's the benchmark trying to do with this setTimeout? Perhaps there's a better way.

**Comment by localvoid** [comment]
It is for manual testing, benchmark runner doesn't use this numbers.

**Comment by krausest** [comment]
Boris is right (of course). The actual measurement is extracted from the chrome timeline within the test driver. To allow manual tests and some degree of validation of these results there’s an additional client side measurement. To include rendering duration it uses setTimeout such that it should stop after repainting happened. Seems to yield an acceptable approximation.

**Comment by esprehn** [comment]
setTimeout doesn't have anything to do with rendering unfortunately. If you wanted to wait until after rendering you'd need to use requestAnimationFrame.

**Comment by localvoid** [comment]
I don't think that anyone is actually using it to measure anything, so it can be removed. domvm, ivi, etc doesn't have it in their implementations.

**Comment by krausest** [comment]
@esprehn Although it doesnt’t really matter for the purpose of the benchmark I’d like to understand your definitive, but too short answer. I do not want to wait for the next animation frame as that could add up to 16 msecs waiting for the next frame but as soon as updating the DOM and rendering finished. It sounded reasonable to schedule a task in the event loop, some sources say that rendering might be performed before the next task is processed. When I added a console.timeStamp in the timeout callback the chrome timeline showed that mark closely after rendering. (I had a few problems with a early version of aurelia that sometimes took a very long pause before rendering but for the other frameworks at that time it worked consistently well) Could you please elaborate what‘s wrong about these assumptions?

**Comment by localvoid** [comment]
@krausest it is unreliable because timeout can be triggered before rendering. It is one of the reasons why many frameworks in [js-repaint-perfs](https://github.com/mathieuancelin/js-repaint-perfs ) benchmark are getting 2x speedup in "repaint rate" when they become slightly faster, browser just decides to trigger timeout one more time before actual rendering.
