### ISSUE TITLE
ko.utils.arrayPushAll is inefficient when called with an observable array

### ISSUE THREAD

**Issue by mbest** [krausest/js-framework-benchmark#256]
https://github.com/krausest/js-framework-benchmark/blob/c3488d6ba2619c9fa5a47639ecba9e691a822035/knockout-v3.4.1-keyed/src/Main.js#L59

`arrayPushAll` will make 1000 `push` calls, which each update the binding separately. Although one could argue that `arrayPushAll` should work better, this code should use the recommended approach:

    self.add = function () {
        startMeasure("add");
        self.data.push.apply(self.data, buildData(1000));
        stopMeasure();
    };

**Comment by chrisknoll** [comment]
@mbest, not sure if this change had an impact on the results. The 'append 1k rows to large table' test still shows a very strange difference in execution time.  Also, not clear if round 7 included this update, but the PR was merged in october, and Round 7 was published in november, so I'm assuming the change is in round 7.

**Comment by mbest** [comment]
I was wrong on how I read the Knockout code surrounding `arrayPushAll`, which is actually pretty much the same as `push.apply`. Thus the problem is actually deeper in Knockout regarding changes to large arrays. This should become better with Knockout 3.5 (knockout/knockout#2324).
