### ISSUE TITLE
[Suggestion] Convert JS Benchmark to use Javascript instead of Java

### ISSUE THREAD

**Issue by axemclion** [krausest/js-framework-benchmark#27]
Given that most of the code here uses Node, it would be interesting to convert the WebDriver tests that use [Java](https://github.com/krausest/js-framework-benchmark/tree/master/webdriver-java/src/main/java/net/stefankrause) into Node based tests - will remove dependency on Java from this repo.

I have written a [tool] that runs [performance benchmarks](https://web-perf.github.io/) and uses a Node based test suite. If this is something you are ok with, I can send in a Pull request.

**Comment by krausest** [comment]
I thought about converting the tests to JS. But if I wrote them today I'd use typescript due to the comfort of code completion for the webdriver/selenium API. Wouldn't the java dependency stay for selenium?
Or do you suggest replacing extracting the selenium tests with web-perf tests? I tried your browser-perf tool before using selenium but I failed to measure what I wanted...

**Comment by axemclion** [comment]
Technically, you could simply use ChromeDriver as an executable, and completely do away with Java and selenium. Alternatively, you could also use hosted selenium services like Saucelabs to run the tests in a Travis like environment. 

My suggestion was to change all the java code to JavaScript - things like executing the actions, reading the performance numbers, and spitting out the information. 

You mention that browser-perf did not meet your needs - what were the metrics you were interested in ?

**Comment by krausest** [comment]
If we can get rid of selenium I'm very interested!
If you send me the PR I'd love to convert it to Typescript - I hope you don't mind.

**Comment by krausest** [comment]
First draft is committed in webdriver-ts.
It was an important goal to remove all sleeps and run the tests as fast as possible. I used rx.js to tame the async hell. The stale element error were quite hard to get straight.
What do you think? Suggestions for improvements?

**Comment by boussou** [comment]
not working for me.
frankly I never even managed to make the java version work on my machine.

;-(

**Comment by krausest** [comment]
I tweaked the build process just a little. The build works fine on a windows 10 and ubuntu 16.04 vm and webdriver-ts can be run. 

What exactly doesn't work for you?

Here's the checklist:
- node.js is installed and can be invoked (node -v and npm -v)
- java is installed and can be invoked (java -version and javac -version) [needed for webdriver-java and kivi which uses the closure compiler]
- maven is installed and can be invoked (mvn -v) [needed for webdriver-java]
- "npm install" runs without error
- "npm run build" runs without error
- "npm start" starts a local web server
- chrome is installed (http://localhost:8080/vanillajs/ can be opened in chrome and clicking the buttons creates the table). 
- "cd webdriver-ts" and "node dist/Main.js --framework vanillajs" works
- "node makeTable.js" works and creates table.html

**Comment by krausest** [comment]
webdriver-java has been retired
@boussou: Please open a new issue if the tests can't be run.
