### ISSUE TITLE
round 7

### ISSUE THREAD

**Issue by pakastin** [krausest/js-framework-benchmark#276]
Hi! When will we see the round 7? I'd like to see [RE:DOM](https://redom.js.org) included this time 😎

**Comment by krausest** [comment]
I know ;-)
I hope soon - but I'll have to update all frameworks to at least the current minor version...

**Comment by pakastin** [comment]
Ok, no hurries 🙂

**Comment by krausest** [comment]
[Done!](http://www.stefankrause.net/wp/?p=454)

**Comment by pakastin** [comment]
Small thing, but if it’s possible to use `RE:DOM` with all caps, I’d be happy 😎

**Comment by pakastin** [comment]
Doesn’t matter in graphs of course, since `redom` is also the official package name..but at least in the links list..

**Comment by krausest** [comment]
A christmas edition should make people happy, isn‘t it?

**Comment by pakastin** [comment]
I’m really happy, don’t get me wrong! 😉👌

**Comment by pakastin** [comment]
Thank you! ❤️
