### ISSUE TITLE
[Suggestion] Record Framerates in addition to JavaScript execution times

### ISSUE THREAD

**Issue by axemclion** [krausest/js-framework-benchmark#28]
A lot of these frameworks touch the DOM only sparingly and such frameworks should also measure frame rates in addition to just JavaScript execution times. Even if the JavaScript takes a lot of time to run, frameworks could technically stagger it such that the frame rates are not impacted.

Frame Rates can be calculated in the same way Chromium's perf test suite calculates is - using Log entries like `DrawFrame` and `BenchmarkImplStats`. If this is something the project could use, I could send in a pull request with the change.

**Comment by krausest** [comment]
What would your pull request contain? Do you need to put much work into it? If not I'd love to get a PR.
I'm not entirely sure if the benchmark should measure framerates. There's already the dbmon benchmark and it's unclear to me what this benchmark could deliver for an additional benefit over dbmon.
Which action should be benchmarked (and on which table size)?
What's the goal of the benchmark (repaint performance or avoidance of stuttering)?

**Comment by axemclion** [comment]
The PR would basically be about listening for another event `DrawFrame`, and for each test, calculating `# DrawFrame Events / Duration` to calculate frame rate. I wrote the [DBMon tests](https://github.com/web-perf/react-perf) with (results](https://axemclion.cloudant.com/react-perf/_design/site/index.html#/summary?pagename=DBMonster&browser=chrome) for react, ionic, etc. The issue with DBMon is that they only measure one scenario - rapidly drawing rows/columns. Adding frame rates for the tests you have will add additional scenarios. 

The goal would be to see how each of the framework handles jank, and interacts with the DOM. The JavaScript time to draw the rows is not actually the time they are drawn on the screen - primarily because frameworks these days employ techniques like `setTimeout` and `requestAnimationFrame`. Both these calls are optimized such that they appear to be periodic, even if the screen is not yet painted.

**Comment by krausest** [comment]
The benchmarks tries to measure the complete duration from the event to finishing painting (see [http://www.stefankrause.net/wp/?p=218](http://www.stefankrause.net/wp/?p=218) for more information). The console logging is only an approximation. It uses a timer to try to be executed after the repaint happened. There's no guarantee that this works thus I'm using the timeline from chrome to extract the timestamps for the event and the last repaint. This duration is the time the user has to wait for the ui action.
So I think the duration you mentioned is already included. What frame rate could be reported for e.g. create 1,000 rows? It's just one event and (for most frameworks) one repaint.

**Comment by krausest** [comment]
Please reopen if you're still interested.
