### ISSUE TITLE
weird mem bench, "not found"

### ISSUE THREAD

**Issue by leeoniya** [krausest/js-framework-benchmark#287]
Win10, 62.0.3202.89 (Official Build) (64-bit)

it does work, but the way it behaves visually is a fast flicker between create/clear rows.

![mem_bench_odd](https://user-images.githubusercontent.com/43234/32680434-41e58e60-c630-11e7-9762-9df16b2cca55.png)

**Comment by krausest** [comment]
The flickering should be fine - it's 5 times adding the then removing 1,000 rows and repeating the whole process count times. 
The log looks good -  though "not found" might be confusing (fixed in 90b4c3a2aa60810f35c346a8d81fc73868c58706)
