### ISSUE TITLE
Updating react easy state fails

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#290]
When updating to react easy state to react 16.1.0 the rollup build hangs after printing `src/index.jsx → dist/bundle.js...`

**Comment by krausest** [comment]
@solkimicreb Can you take a look at it please? Seems like the rollup build hangs when updating to react v16.

**Comment by solkimicreb** [comment]
It seems to be a general issue with rollup and react v16+. Here is the rollup issue about it: https://github.com/rollup/rollup/issues/1711. I will try to look into it too 🙂

**Comment by krausest** [comment]
I'm planning to do so soon (maybe end of the week). I'll switch to the webpack build from the react-keyed implementation. That would also make it more comparable. Any objections?

**Comment by krausest** [comment]
It's using es5 with webpack now. Contributions for a nice and simple template for a webpack config with babel-preset-env targeting the latest chrome would be very welcome.

**Comment by solkimicreb** [comment]
Perfect, thanks!

**Comment by solkimicreb** [comment]
That is not really doable  until webpack 4. Webpack 3 uses uglifyjs 0.x,
which has no es6 support. So transpiling things down only to the latest
chrome would crush the minification step. This is a bit silly. Webpack 4
will ship with the es6 aware uglifyjs 1.x

**Comment by krausest** [comment]
Ok. I tried for preact - but the solution I came up with doesn't feel right. It's using babel-minify-webpack-plugin but not using the "-p" argument for webpack.

**Comment by solkimicreb** [comment]
Forget it 😀. I forgot that we can use the new uglify as a plugin. I will
do it, but transpiling to es5 is okay for me, to stay fair with the others.

**Comment by solkimicreb** [comment]
Yes, exactly. The new plugin works. The flag will only work with webpack 4

**Comment by krausest** [comment]
Results are strange. Partial update got really very slow with 16.1.0
<img width="495" alt="bildschirmfoto 2017-11-12 um 16 43 05" src="https://user-images.githubusercontent.com/3374055/32700677-a431da58-c7c8-11e7-9763-ff19072cbb12.png">
Any idea why?

**Comment by solkimicreb** [comment]
No idea yet. I will make some perf profiles. Thanks for the info 👍

**Comment by solkimicreb** [comment]
I think I found the root of the issue, React Fiber does not like it when I try to tell it when to update. So I have to give render tasks to the Fiber scheduler instead of calling them with forceUpdate. This requires some changes in the underlying observable library and I don't want to rush it. Feel free to publish the next article in the meantime if it is ready. Thanks for catching this one 🙂
