### ISSUE TITLE
How should CI handle timeouts?

### ISSUE THREAD

**Issue by alexfmpe** [krausest/js-framework-benchmark#292]
Should CI report timeouts as build failure? 
If so, should it stop at the first?
Do we want to auto-notify the author/maintainer in the relevant `package.json`?

One of the [new tests](https://github.com/krausest/js-framework-benchmark/commit/2bc3077c4386382b79786af20d22307bdd041e43#diff-ae11d97d09b8aaaa9926ce9deb15c5f4R240) timeouts at least on Halogen: [build 80](https://circleci.com/gh/krausest/js-framework-benchmark/80)
It might also be hiding a react timeout that appeared out of nowhere on [build 78](https://circleci.com/gh/krausest/js-framework-benchmark/78)

**Comment by krausest** [comment]
I'm closing some older issues that won't get fixed.
