### ISSUE TITLE
Updating petit-dom causes wrong behaviour

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#293]
Updating petit-dom to 0.0.11 causes the following bug:
Click on "create 1,000 rows". Table appears with ids starting with 1.
Click on "create 1,000 rows" again. The second column is updated, but the first column now starts with id 2, which is very odd and causes the test driver to report an error.

**Comment by krausest** [comment]
@yelouafi: Can you take a look at it please? I'll have to disable petit-dom in the mean time.

**Comment by yelouafi** [comment]
Thanks for notifying. Will take a look asap

**Comment by yelouafi** [comment]
I just released a v0.0.12 with the fix. I ran it locally with no error.

Would you like me to create a PR for that?
