### ISSUE TITLE
Swap rows doesn't work correctly for thermite, halogen and pux

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#294]
Click "create 1,000 rows", the swap rows. The id of the rows 5 and 10 remain unchanged, which is wrong.
I'll disable them until the bug is fixed.

**Comment by krausest** [comment]
@thomashoneyman Can you take a look at it please?

**Comment by thomashoneyman** [comment]
See merged fix here:
https://github.com/krausest/js-framework-benchmark/pull/296#issuecomment-343763975
