### ISSUE TITLE
Chromedriver crashes

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#303]
Tried at least 4 times, but test doesn't complete for all frameworks. Errors are like that:
```
(node:25652) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
Benchmark failed { TimeoutError: Waiting testTextContains //tbody/tr[1000]/td[1] 2000
Wait timed out after 60050ms
    at /Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-ts/node_modules/selenium-webdriver/lib/promise.js:2201:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) name: 'TimeoutError', remoteStacktrace: '' }
Writing screenshot error-halogen-v2.1.0-non-keyed-25_run-clear-memory.png
Benchmark failed { TimeoutError: Waiting testElementLocatedById add
Wait timed out after 20091ms
    at /Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-ts/node_modules/selenium-webdriver/lib/promise.js:2201:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) name: 'TimeoutError', remoteStacktrace: '' }
Writing screenshot error-ivi-v0.9.1-keyed-24_run5-memory.png
Benchmark failed { WebDriverError: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.1 x86_64)
    at Object.checkLegacyResponse (/Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-ts/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-ts/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/stefan/Source/Javascript/js-framework-benchmark/webdriver-ts/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) name: 'WebDriverError', remoteStacktrace: '' }
(node:25652) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 663): WebDriverError: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.1 x86_64)
(node:25652) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by krausest** [comment]
I checked twice again.
When chromedriver is initialized like that:
```
    let service = new chrome.ServiceBuilder(args.chromeDriver).build();
    return chrome.Driver.createSession(options, service);
```
I get the "possible EventEmitter memory leak" and it quits with "unable to discover open page".
With the old initialization
```
    return new Builder()
        .forBrowser('chrome')
        .setChromeOptions(options)    
        .build();
```
the test completes and only reports the (correct) timeout errors for halogen, pux and thermite.
I know it doesn't sound plausible, but I ran it often enough to be confident that the new intitalisation is causing the problems.
@alexfmpe Any idea about that?

**Comment by krausest** [comment]
Reverted in ab0c84ee7cd0b33501f6db0776d64c2767e0247b

**Comment by alexfmpe** [comment]
Weird.
Haven't been able to reproduce on Mac OS 10.12 (Sierra) using chrome 61 or 62. 
Does it fail consistently on specific frameworks/tests?

I get the "possible EventEmitter memory leak" warning, but not the "unable to discover open page" error. Also don't see the line:
`(Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.1 x86_64)`

`chromedriver=2.33.506106` in particular seems odd. Shouldn't it be 2.33.2 ?

Tried reverting ab0c84e's revert and running on [circleci](https://circleci.com/gh/alexfmpe/js-framework-benchmark/118).
Still got "memory leak", but not "open page".
Strangely, it hangs on petit-dom, rather than timeout.

**Comment by krausest** [comment]
It failed for seemingly random frameworks after a few hours and restarting with the framework it failed didn't show any problem with that framework. 
I had a success ratio of 0% for the ServiceBuilder and 100% for the old Builder approach for about 4 complete runs for both variants.

**Comment by alexfmpe** [comment]
Sounds like a chromedriver bug, if it fails randomly.
Do we stick to old-Builder for now, or do some kind of
`if args.chromeDriver then ServiceBuilder else Builder`
with a big fat warning on the former?

**Comment by alexfmpe** [comment]
Does this initialization still cause problems after the recent chromedriver bumps?

**Comment by alexfmpe** [comment]
It does indeed - and it's still seemingly random.
Just had the same error on a particular benchmark during the 9th out of the 20 runs of `npm run selenium`.
It doesn't seem like it will go away anytime soon, so I'll look into alternatives.

**Comment by metrophos** [comment]
Hi!
Maybe it helps you by your analyze. I have the same problem on another project. I use protractor and chrome to run tests. Sometimes I get the same error what you have:

> I/direct - Using ChromeDriver directly...
> node_modules/selenium-webdriver/lib/error.js:27
> WebDriverError: unknown error: unable to discover open pages
> (Driver info: chromedriver=2.37.544315, platform=Linux 4.7.3-coreos-r2 x86_64)

I don't know what's wrong but the Protractor framework uses the same way to get the chromedriver instance what you have described above: https://github.com/angular/protractor/blob/f8f490a82d0ed6965248e1f78bd2ac7ca91548d9/lib/driverProviders/direct.ts#L84

**Comment by krausest** [comment]
The workaround mentioned above seems to work. Closing it.

**Comment by dineshrathee12** [comment]
I need to integrate it with node js application. I got the following error

(node:2987) UnhandledPromiseRejectionWarning: WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac),platform=Linux 4.4.0-1075-aws x86_64)
    at Object.checkLegacyResponse (/opt/bitnami/apache2/htdocs/node_modules/selenium-webdriver/lib/error.js:585:15)
    at parseHttpResponse (/opt/bitnami/apache2/htdocs/node_modules/selenium-webdriver/lib/http.js:533:13)
    at Executor.execute (/opt/bitnami/apache2/htdocs/node_modules/selenium-webdriver/lib/http.js:468:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2987) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async f
unction without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2987) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not ha
ndled will terminate the Node.js process with a non-zero exit code.
(node:2987) UnhandledPromiseRejectionWarning: WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac),platform=Linux 4.4.0-1075-aws x86_64)
    at Object.checkLegacyResponse (/opt/bitnami/apache2/htdocs/node_modules/selenium-webdriver/lib/error.js:585:15)
    at parseHttpResponse (/opt/bitnami/apache2/htdocs/node_modules/selenium-webdriver/lib/http.js:533:13)
    at Executor.execute (/opt/bitnami/apache2/htdocs/node_modules/selenium-webdriver/lib/http.js:468:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2987) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async f
unction without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2987) UnhandledPromiseRejectionWarning: WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.26.436382 (70eb799287ce4c2208441fc057053a5b07ceabac),platform=Linux 4.4.0-1075-aws x86_64)
    at Object.checkLegacyResponse (/opt/bitnami/apache2/htdocs/node_modules/selenium-webdriver/lib/error.js:585:15)
    at parseHttpResponse (/opt/bitnami/apache2/htdocs/node_modules/selenium-webdriver/lib/http.js:533:13)
    at Executor.execute (/opt/bitnami/apache2/htdocs/node_modules/selenium-webdriver/lib/http.js:468:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2987) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async f
unction without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
