### ISSUE TITLE
Are non-keyed-only frameworks an anti-pattern?

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#304]
I'm about to advise against using frameworks that support **only** non-keyed updates. 
Integrating 3rd-party libraries, raw dom manipulation or using transitions bears a chance that something doesn't behave correctly and your framework has no support for getting it right. General purpose frameworks should support keyed updates.

What's your opinion?

**Comment by leeoniya** [comment]
sound advice

**Comment by thysultan** [comment]
Loosing state is another major downside of non-keyed updates, mainly in form inputs.

Incorrect animation transitions could equally apply to frameworks that support keyed updates depending on the reconcile heuristics, that is unless the framework in question provides the guarantee of the least number of DOM operations needed to archive a reconciled state.

**Comment by psirenny** [comment]
I personally maintain all of my UI state (animations, deletions, etc.) outside of the framework. Non-keyed is fine for my use case.

**Comment by leeoniya** [comment]
i think the commenting period has officially ended ;)

@krausest close?

**Comment by krausest** [comment]
Hmm - most recent PRs were non-keyed frameworks and this issue isn't good press for them. Thought I'd get more controversy.
