### ISSUE TITLE
use 1/998 for swap rows rather than 4/9

### ISSUE THREAD

**Issue by leeoniya** [krausest/js-framework-benchmark#306]
@krausest 

i did a bit of testing as a followup to https://github.com/krausest/js-framework-benchmark/issues/305#issuecomment-345538990

dunno if you wanna sneak this change into Round 7, but the results are rather revealing:

![swap-rows](https://user-images.githubusercontent.com/43234/33000432-a7a51d6c-cd6d-11e7-91ec-4e5b4a4d8cc8.png)

**Comment by leeoniya** [comment]
the plot thickens...

apparently some libs are micro-optimized only for leading/trailing swapping rather than a more general reconcile algo. so when we switch to 1/998 instead of 0/999, we get to see prettier autumn colors:

![swap-rows2](https://user-images.githubusercontent.com/43234/33002127-b5d7e8ce-cd77-11e7-8fa5-0df5c874b497.png)

**Comment by krausest** [comment]
Will run the swap benchmark and post results this evening.

**Comment by krausest** [comment]
Here they [are](https://rawgit.com/krausest/js-framework-benchmark/9e80ef2cedcd9494756240456481608499e488d9/webdriver-ts/table.html).

**Comment by leeoniya** [comment]
hmm, is `choo v6.5.0-keyed` misclassified?

**Comment by krausest** [comment]
Thanks for spotting it. At least its naming was already correct...
Fixed in ee308dc2ad38688bc6d1ac1c0313c06ed40f21e8
