### ISSUE TITLE
Condition for swap must be checked for all frameworks

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#312]
Since #310 the swap rows benchmark swaps index 1 and 998. The guard condition that enough rows exist must be adjusted for all benchmarks (`if (this.data.length > 10) {` new condition should check for `length > 998`)...

**Comment by leeoniya** [comment]
yay...NOT.

want me to go through them?

**Comment by krausest** [comment]
Thanks, no - I'm already at it. I'm almost halfway through.
