### ISSUE TITLE
Comments on your wordpress blog fail with server error

### ISSUE THREAD

**Issue by eavichay** [krausest/js-framework-benchmark#319]
I'm not sure if this is the right place to post an issue, if not I apologize.
The server returns error "fill in name + email", though the fields are populated.

The POST data ends with `...&Author=Avichay+Eyal&Email=eavichay%40gmail.com&mv=8&mi=57f5b&submit=Add+Comment&comment_post_ID=454&comment_parent=0`

**Comment by krausest** [comment]
Thanks! The theme was not compatible with wordpress 4.9.
Works now again!
