### ISSUE TITLE
Timeout on hyperhtml-majinbuu

### ISSUE THREAD

**Issue by alexfmpe** [krausest/js-framework-benchmark#327]
Happening on [master](https://circleci.com/gh/krausest/js-framework-benchmark/215)
`
after initialized  02_replace1k 0 hyperhtml-v2.1.3-majinbuu-keyed
Benchmark failed { TimeoutError: Waiting testTextContains //tbody/tr[1]/td[1] 5001
`

**Comment by krausest** [comment]
majinbuu was removed in #329
