### ISSUE TITLE
Dedice on interesting Lighthouse metrics

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#330]
@paulirish submitted a PR adding lighthouse creating lots of interesting information for the benchmark startup - thanks Paul!
As an experiment I added them all to the [results table.](https://rawgit.com/krausest/js-framework-benchmark/94bb8d703ace321b1d6305e11c39bc22991ea03a/webdriver-ts-results/table.html)

We should discuss here which rows we want to keep. My preferred metrics are:
* script bootup time 
* total byte weight (though I'm not sure we should mix duration and size in the table and average over both...)

See also #326 for Paul's recommendations.

**Comment by krausest** [comment]
@leeoniya @adamhaile @Bobris @localvoid Looking forward to hearing your opinion.

**Comment by leeoniya** [comment]
some quick observations:

- `estimated input latency` looks useless
- `first meaningful paint` and `first contentful paint` are the same
- `first interactive` and `consistently interactive` are the same
- `onload` looks suspect where `total byte weight` does not match (vidom, elm?)
- marionette's `first meaningful paint` looks wrong - might be the result of rendering a skeleton and placing the script at the bottom. i think this should actually be changed for all impls (put script at bottom - may help bring some things in line)

**Comment by krausest** [comment]
@leeoniya 
> first interactive and consistently interactive are the same
Feared this too, but it's not. hyperapp-v0.16.0-keyed has a small difference!

**Comment by leeoniya** [comment]
> hyperapp-v0.16.0-keyed has a small difference!

i think you mean `first contentful paint` and `first meaningful paint`. a 0.1ms difference in one lib is neither significant nor interesting enough to burden the entire bench runtime. it's very likely just noise.

**Comment by paulirish** [comment]
agree with the above observations. 

I'd suggest Consistently Interactive, script bootup, main thread work cost, and total byte weight (to keep the network costs in the picture).  FMP could also be considered, but I think it's going to deliver the same point as Consistently Interactive too often for it to be called out individually.

**Comment by paulirish** [comment]
it's worth pointing out the dependencies between the above metrics, too.

* CI will be no earlier than FMP.
* `Main thread work cost` includes all `script bootup` time. 

So the most-top level choices here would be `Consistently Interactive` and `main thread work cost`. There will be a correlation between these two but it's possible to have a fast CI even with lots of main thread work; so I think it's good to represent both. 

And yah I do like including `total byte weight`. (And agree bytes and milliseconds shouldn't be averaged together. :)

**Comment by krausest** [comment]
There are [now](https://rawgit.com/krausest/js-framework-benchmark/63fb6233721683ebc876c7ca882650e4699b108d/webdriver-ts-results/table.html) three result tables: Duration, startup and memory.

**Comment by leeoniya** [comment]
looking at the data, paul's advice is spot on. i've opened #334 to reduce the noise.

changing STARTUP_SLEEP_DURATION from 1000 to 0 should likely be re-evaulated too, i think.

**Comment by kaste** [comment]
Just want to mention that 'main thread work cost' is a bit random on my computer.

![image](https://user-images.githubusercontent.com/8558/34060700-180e87d8-e1e5-11e7-8f8c-014b8718b11b.png)

![image](https://user-images.githubusercontent.com/8558/34060687-063e74c8-e1e5-11e7-9ac6-e5c96798f56e.png)

On the left you see vanillajs, in the middle my lib, on the right lit-html.
