### ISSUE TITLE
Feature request: change the test order

### ISSUE THREAD

**Issue by pygy** [krausest/js-framework-benchmark#332]
Currently, the runner runs all the tests of a given framework in a row, then goes to the next framework, etc.

While this may be fine if you have a computer dedicated to the benchmarks, if you're running the tests on your main computer it makes the benchmark very sensitive to background noise. Some process may kick in while a given framework/benchmark pair is running, slowing down several runs and distorting the results and leading to poor reproducibility.

If instead you were cycling through frameworks for each run of every benchmarks, such accidents would be less likely to poison a single benchmark/framework pair.

I understand that this may not be straightforward due to the way the reports are built and logged.

To be clear currently this happens:

```
test1/lib1
test1/lib1

test2/lib1
test2/lib1

test1/lib2
test1/lib2

test2/lib2
test2/lib2
```

I'd suggest doing this instead:

```
test1/lib1
test1/lib2
test1/lib1
test1/lib2

test2/lib1
test2/lib2
test2/lib1
test2/lib2
```

**Comment by leeoniya** [comment]
> Some process may kick in while a given framework/benchmark pair is running, slowing down several runs

how would this change address the problem, though?

there've been a couple times when i didn't notice that some background indexing or anti-malware service was already running before a bench run started, but i've never had one kick on randomly mid-bench. (i guess Windows 10 is smart enough to realize when a pc is not idle, and this bench certainly makes it extremely not idle)

**Comment by pygy** [comment]
> how would this change address the problem, though?

By diluting the error in the results of several frameworks.

```
test1/lib1 slowdown starts
test1/lib1 ...

test2/lib1 ...
test2/lib1 slowdown stops <== lib1 looks worse than it should

test1/lib2
test1/lib2

test2/lib2
test2/lib2
```

vs.

```
test1/lib1 slowdown starts
test1/lib2 ...
test1/lib1 ...
test1/lib2 slowdown ends <== now the penalty is shared by both libs

test2/lib1
test2/lib2
test2/lib1
test2/lib2
```

OS X here, I'm using the benchmark suite to ensure I'm not introducing perf regressions in Mithril and I've had a hard time in getting reproducible runs, at 10 repeats at least.

Each time, I'm running both the baseline (current release) and the git head, and there's a lot of variation, even for the baseline, which makes it hard to do comparisons reliably unless I close every program (including browsers and code editors) which makes benchmarking tedious.

**Comment by leeoniya** [comment]
i suppose it makes sense if you're forced to re-run your baseline every time due to frequent system load fluctuations. you could technically achieve this easily by writing a script that runs the existing metrics sequence via cli for a restricted metric:

```
npm run selenium -- --framework vanilla mithril --benchmark swap
npm run selenium -- --framework vanilla mithril --benchmark create10k
npm run selenium -- --framework vanilla mithril --benchmark create1k-after10k
...
npm run results
```

**Comment by pygy** [comment]
That would still do 10 contiguous runs for each framework. What I'd like to have 

```
npm run selenium -- --framework A B --benchmark swap
```

to interleave the runs. Currenty it does `(A x 10) => (B x 10)`. What I'd like is to have `(A => B) x 10`.

I suppose I could do it manually, gathering the results on the go and generating a final results file myself, but it's going to be tedious.

**Comment by krausest** [comment]
I'm closing some older issues that won't get fixed.
