### ISSUE TITLE
Question about Vue.js testing

### ISSUE THREAD

**Issue by matthew-dean** [krausest/js-framework-benchmark#337]
When you're testing Vue, are you testing pre-compiled components and using just the Vue.runtime.js lib in the performance test (the expected real-world scenario), or are the performance tests using the full vue library and actually parsing in the browser? I hope not the latter, as that wouldn't be a fair test against something like React which is also pre-compiling templates from `.jsx` to `.js`.

**Comment by leeoniya** [comment]
if only this bench was open souce ;)

https://github.com/krausest/js-framework-benchmark/blob/master/vue-v2.5.3-keyed/index.html

the html loads a single `.js` file. it also has a webpack build script. so i'm assuming everything that needs to be compiled, is.

**Comment by matthew-dean** [comment]
Ha, good point. No, you're right. Originally, the `package.json` for Vue exported the full build (parser + runtime) but it appears that's been fixed at some point, so it should only be including the runtime, according to: https://github.com/vuejs/vue/blob/dev/package.json#L5-L6. My bad!
