### ISSUE TITLE
kivi-v0.11.0-alpha3 fails to build

### ISSUE THREAD

**Issue by trueadm** [krausest/js-framework-benchmark#37]
I've had several people ask me why this is: it appears to be a premature merge as `kivi-v0.11.0-alpha3` does not build. @localvoid @krausest 

I've spoken to @localvoid and he knows what the issue is, so hopefully he can make a PR to fix.

**Comment by localvoid** [comment]
Thanks, forgot to lock version in `package.json`

**Comment by trueadm** [comment]
@localvoid awesome :)
