### ISSUE TITLE
preact-compat

### ISSUE THREAD

**Issue by streamich** [krausest/js-framework-benchmark#374]
Would be nice to add `preact-compat`, it could be the same code that React uses.

**Comment by krausest** [comment]
Sorry unless someone submits a PR I'm not going to add it. Performance between preact and react isn't that easy to compare. Take a look at the following picture. It's easy to say that surplus is faster than react. But for preact things are more complex. As can be seen by the red boxes preact is indeed significantly slower than react for three benchmarks and only in one benchmark faster than react. But in this case much faster, so much that preact leads on the geometric average.
<img width="359" alt="bildschirmfoto 2018-05-10 um 10 46 04" src="https://user-images.githubusercontent.com/3374055/39860935-5f2088ac-543f-11e8-9501-827b87bfda2c.png">
If you leave out swap rows react is faster:
<img width="367" alt="bildschirmfoto 2018-05-10 um 10 49 11" src="https://user-images.githubusercontent.com/3374055/39861198-294c2d66-5440-11e8-9628-44141f2953ef.png">
So unless preact becomes faster than react I'm not interested in adding preact-compat.
