### ISSUE TITLE
CPU usage rises for test runner on windows

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#378]
The CPU consumption of the testrunner rises to about 100% after a short time on windows (does not happen on OSX).
Removing the --no-sandbox option in benchmarkRunner.ts removes that effect.
Needs to be further analyzed.

**Comment by Alexander-Taran** [comment]
reverting my remark on adding .close(). I missed one spot. It does work for me now.

**Comment by krausest** [comment]
As an additional measure I'm now forking the chromedriver process.
