### ISSUE TITLE
Add build times into the benchmarks

### ISSUE THREAD

**Issue by trueadm** [krausest/js-framework-benchmark#38]
Let's face it – long build times suck. They affect CI and CD builds with automated tests/builds and effect local build times too. I feel it's important to emphasise this in the benchmarks as it's a HUGELY important metric in any job where engineering of software is important.

**Comment by localvoid** [comment]
I am pretty sure that almost all libraries in this benchmark work with all popular tools for frontend development (babel, buble, gcc, uglify, rollup, webpack, browserify, etc). And build time will HUGELY depend on the tools you'll choose to develop this simple benchmark application.

It is better to add javascript size, it is a much more important metric than build time, or even better to measure bootsrap time (js parsing, etc).

**Comment by trueadm** [comment]
@localvoid Choice and quality of tools for build is just as important as choice of tools to create the app. Any software business will tell you this. JS parsing time is far more important than JavaScript size to many too – depending on the platform you're building for. With features such as AppCache, ServiceWorkers and modern browser caching – given on a gzipped bundle isn't likely to be a big a problem as many people make out. 

People rave about having a 5kb gzipped library, only to have 500kb of app code compared to others who have a 30kb gzipped library and 200kb of app code that does exactly the same thing.

For me initial parse time (let's ignore the silly lazy v8 hack going around too – I believe the v8 team are busy addressing that problem) and having a sane build time are very important factors. If it takes 2 minutes to build a JS production bundle for my app, when it only prints out a list of rows and a few buttons – that's an area that needs addressing IMO.

**Comment by hbfs** [comment]
Why not both?

I added `time npm run build` and it gave me a rough time for each build which was helpful. Sizes would also be good.

`du` on the build product shows the uncompressed sizes. Enabling the chrome network internals in and summing up the resources shows what the end user has to load from the network (gzip) size as well as time for initial loading and parsing. 

A lot of these frameworks+app are >1MB (with compressed) which is ridiculous, especially when tested on mobile.

**Comment by krausest** [comment]
I'm closing the issue. I won't try to benchmark development tools in any way in this benchmark. The addition of startup duration gives an impression of file size due to parsing and compiling.
