### ISSUE TITLE
Collecting ideas: Make maintenance less painful

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#400]
This is (going to be) a collections of ideas how to simplify maintenance. Feel free to add your opinions or ideas - I promise to listen.

1. Store the version number in a property in package.json. 
Use that information to create the list of frameworks and versions in common.ts
Optional even not specify the version itself, but the name of the npm package that carries the version.
Remove the version prefix for all folders. Instead allow temporary folders if needed e.g. for beta versions.

Gains: No more moving directories, adjusting common.ts.
Risks: Higher chance, that the declared version and the actual installed version don't match. 
Moving the directory means node_modules is empty and thus it's pretty safe that the correct version was used for the build.

3. Drop support for frameworks where the last version update was more than a year ago.
tsers would be one candidate.

4. Allow only keyed or non-keyed submission. (non-keyed is a stigma).

**Comment by krausest** [comment]
Now here's the plan:

The first step is that every directory in framework package.json must carry some information:
The directory must be named -non-keyed and -keyed. It's obvious what information that yields.
The package.json must contain the following property:
js-framework-benchmark: {
  frameworkVersionFromPackage | frameworkVersion, 
  customURL?, 
  useShadowRoot?,
}
Example for angular:
  "js-framework-benchmark": {
    "frameworkVersionFromPackage": "@angular/core"
  }
frameworkVersionFromPackage simplifies version determination by using the version of the named npm package. It uses package-lock.json to find out the version for the given package name. This is also a good check that the desired version is actually installed and used in the benchmark.
For some frameworks or framework combination that doesn't make sense and thus a frameworkVersion can be specified as as string.
The custom url can be used if needed and useShadowRoot defaults to false. Both work similar to the old values in common.ts, but customURL is now without the framework directory name.

The second step is to remove the benchmark list from common.ts and build that list from the information above dynamically.

The third step is to drop versions from the directory names.

**Comment by leeoniya** [comment]
sounds sane.

another option is to drop keyed and non-keyed from the names and add another dir layer either /frameworks/keyed/domvm or /frameworks/domvm/keyed.

is the plan for the benchmark runner to splice in the version number into the `framework` property of the result jsons ahead of the trailing `keyed` or `non-keyed`?

**Comment by adamhaile** [comment]
I liked the xor on keyed/non-keyed, if that's still part of the plans.

I might suggest moving that data out of the filename and having a `keyed: boolean` flag in the package.json section.

**Comment by krausest** [comment]
Allowing multiple versions is a must, but could be easy (just take two directories like angular and angular-beta). 
Naming and assigning a version is a bit less handy for combinations like react + react-easy-state.

I'll consider separating the frameworks into a keyed or non-keyed folder as that would make computing the desired results name trivial. I think I prefer that to adding a keyed flag to the package.json.
But before finally deciding I need to take a look at @leeoniya's new results-ui.

**Comment by krausest** [comment]
Step 1-3 are done now.
I'm still creating result file names according to the old scheme. Both webdriver-results-ts and result-ui appear to work.
Known defects:

- [ ]  Can't choose to run only keyed or non-keyed version of framework for all --framework options

**Comment by krausest** [comment]
Any preference for how to specify that only the keyed or non-keyed version should be run for a framework?
Option 1: `npm run nonKeyed -- --framework vanillajs --non-keyed`. Drawback: Can't run keyed for framework a and non-keyed for framework b in the same call.
Option 2: `npm run nonKeyed -- --framework vanillajs:keyed`. 
I think I prefer option 1, syntax of option 2 looks to unexpected.

**Comment by leeoniya** [comment]
> Can't run keyed for framework a and non-keyed for framework b in the same call.

can't see this ever being an real issue, but then again i'm generally against comparing keyed to non-keyed.

that being said, i actually prefer option 2 but maybe with an option to set the default and avoid setting it on each framework also via `--all-keyed` and `--all-non-keyed`.

another route is to go with option 1 but allow both switches simultaneously: `--keyed` and `--non-keyed`

**Comment by krausest** [comment]
I took option 3. From the directory name, the keyed/non-keyed info and the version I'm building a fullNameWithKeyedAndVersion like marionette-v4.0.0-beta.1-keyed or marko-v4.5.6-keyed. The --framework option now compares against this full name (while it still allows partial names like react which runs all implementations whose fullNameWithKeyedAndVersion contains react). Seemed like the least painful option.

**Comment by krausest** [comment]
There's now a `npm run update` task in webdriver-ts. It tries to check all packages specified in frameworkVersionFromPackage (separated by colons) for non-patch versions.
It also prints a warning for all packages that can't be updated that way.

**Comment by krausest** [comment]
Apart from one small issue I'm happy with the result:  For the webdriver bench runner naming is framework-(non-)keyed-version and for the update script it's the directory name (non-)keyed/framework.
