### ISSUE TITLE
Apprun is not keyed for replace rows

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#437]
@yysun Apprun is much faster than the rest for replace rows. As it turns out it isn't really keyed for that case (create 1,000 rows, set background of a row in dev-tools of a row to red, create 1,000 rows. In a keyed implementation that red row must be removed, in apprun it stays.)
The mutation observer in nonKeyed.ts reports 1,000 removed and added TRs, which is typical for keyed implementations, but it doesn't remove a specific row from the table (e.g. the second row).
I've adjusted the nonKeyed.ts check program.

Could you please suggest what to do? Is a fix possible for apprun? Otherwise I'd have to remove the implementation and keep only the non-keyed version.

**Comment by yysun** [comment]
I have fixed the issue and release AppRun v1.15.1. Can you try the new version? 
Tested it using the method of setting the background row. It works.
https://yysun.github.io/apprun/#benchmark

**Comment by krausest** [comment]
Thanks - works as it should. Results have been [updated](https://www.rawgit.com/krausest/js-framework-benchmark/513f38cca89e7e9bd212cc028fb0f938f02dd25f/webdriver-ts-results/table.html) with apprun 1.15.2.
