### ISSUE TITLE
`npm run nonKeyed` is confusing

### ISSUE THREAD

**Issue by leeoniya** [krausest/js-framework-benchmark#440]
`npm run nonKeyed` is a really confusing name for something that asserts whether something is keyed or not.. any of the following would be clearer: `keyedTest`, `checkKeyed`,`assertKeyed`,`isKeyed`

my vote goes to `isKeyed`

**Comment by leeoniya** [comment]
i suppose while we're on this topic, `npm run selenium` is probably vetter off as `npm run bench`

**Comment by krausest** [comment]
You're right. I kept the old names transitionally.
