### ISSUE TITLE
Will you be interested in my in-depth comparisons between mobx & redux?

### ISSUE THREAD

**Issue by lyonlai** [krausest/js-framework-benchmark#45]
Hi, @krausest . I've done these in branch [benchmark/mobx-vs-redux](https://github.com/lyonlai/js-framework-benchmark/tree/benchmark/mobx-vs-redux) my fork. 8 more columns have been added to the result table. Don't know if you would like a PR for this, as it might goes too much detail into inferno & react, which's a little bit off the intention of this repo.

New comparisons.

* inferno v0.7.26-mobX-v2.4.4
* inferno v0.7.26-redux-v3.5.2
* inferno v0.7.26-redux-v3.5.2-immutable-js-v3.8.1
* inferno v0.7.26-redux-v3.5.2-immutable-js-v3.8.1-pure-render-mixin-15.3.0

* react v15.3.0-mobX-v2.4.2
* react v15.3.0-redux-v3.5.2
* react v15.3.0-redux-v3.5.2-immutable-js-v3.8.1
* react v15.3.0-redux-v3.5.2-immutable-js-v3.8.1-pure-render-mixin

**Comment by krausest** [comment]
What's your conclusion? Seems like neither inferno nor react benefit from mobX/redux for this benchmark.

**Comment by lyonlai** [comment]
You are right. mobX/redux are actually extra layer on top of inferno and react so they won't do any good for the benchmarks. But they are the libraries people will use along with inferno/redux. This is more to see which flux implementation is more efficient under this benchmark. 

The result for mobX vs redux is different when they are used under inferno and react. I've attached it with this comment.

When used under react, mobX is slightly faster than redux (with immutable + pure-render-mixin case) in the following cases:

* partial update
* select row
* swap rows
* remove rows
* append rows to large table

When it comes to inferno, mobX seems to be slightly slower than redux (with immutable + pure-render-mixin case).

![screencapture-localhost-8080-webdriver-ts-table-html-1473809254910](https://cloud.githubusercontent.com/assets/1623058/18495147/d4e0baec-7a5e-11e6-983d-d807f3cf39c1.png)

**Comment by krausest** [comment]
Thought about it for a while ;-) and decided to add redux + immutable.js + pure render mixin version to the list of benchmarks, since redux is quite popular, and this version is the fastest redux version and it's interesting to see that immutable.js doesn't cost much. Results are [here](https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts/table.html).
