### ISSUE TITLE
Select Row and Swap Rows are too fast

### ISSUE THREAD

**Issue by ruphin** [krausest/js-framework-benchmark#451]
I've been using this benchmark suite for a while now to do performance testing, and one thing I found is that the `select row` and `swap row` tests are simply too fast. The problem is that the performance of these tests is heavily impacted by the timing of the test in relation to the browser's frame rate (in the case of Chrome 1/60th of a second). As indicated by the extremely large standard deviations, the results of these tests are simply highly random. If I test the same framework multiple times with a high run count (15), the (average) result of these tests can still differ by ~40%.

The problem is that they have an impact on the slowdown geometric mean, which essentially introduces an additional random factor with every benchmark run. I cannot get any repeatable results with reasonable precision even with a large run count, because these two tests add too much noise. I have resorted to removing the results of these tests before generating the result table, but these tests do touch a surface of the frameworks that no other does.

It would be nice if we could somehow make these tests take longer (maybe perform more iterations), so the results are less affected by the frame rate.

**Comment by leeoniya** [comment]
also see https://github.com/krausest/js-framework-benchmark/issues/424

**Comment by krausest** [comment]
Closing this issue. Further discussion happens in #424 soon. Please join in there.

**Comment by krausest** [comment]
@ruphin I introduced CPU throttling for the benchmarks you mentioned. Would be very interesting to hear from you if you see more consistent results now.
