### ISSUE TITLE
Update to lighthouse 3

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#458]
It seems like Chrome 69 doesn't report a value for Consistently-interactive for lighthouse 2.9.
A first attempt to update to lighthouse 3 failed (can't make it read the trace-json files). 
Needs further investigation.

**Comment by krausest** [comment]
I'm not able to make lighthouse use the trace.json and devtoolslogs.json files. Maybe it needs an artifact.json file, but can't figure out how to make it work.
The only way I could make lighthouse 3 work is by ["using programmatically"](https://github.com/GoogleChrome/lighthouse/tree/master/docs#using-programmatically). What's good about it is that it allows throtteling which makes the startup much more relevant. The bad thing is that introduces a second way to start chrome. Still I think it should be the preferred way.

There are two issues left:
1. bootup-time reports 0 for many frameworks (e.g. domvm, domc, hyperapp, ...). 
I get that too when I run lighthouse from the command line `./node_modules/.bin/lighthouse http://localhost:8080/frameworks/keyed/domvm`
<img width="278" alt="bildschirmfoto 2018-09-11 um 21 39 01" src="https://user-images.githubusercontent.com/3374055/45383439-83630400-b60b-11e8-9dc3-6144a9b30400.png">

But in the chrome audit tab it reports a reasonable number:
<img width="299" alt="bildschirmfoto 2018-09-11 um 21 41 39" src="https://user-images.githubusercontent.com/3374055/45383445-86f68b00-b60b-11e8-925e-d4f8a929bee9.png">

For ember results the numbers and not zero and closer (but not really close...).
Command line ember:
<img width="313" alt="bildschirmfoto 2018-09-11 um 21 44 52" src="https://user-images.githubusercontent.com/3374055/45383690-3fbcca00-b60c-11e8-8f7f-ee0b9af7c894.png">
Devtools lighthouse audit:
<img width="323" alt="bildschirmfoto 2018-09-11 um 21 45 26" src="https://user-images.githubusercontent.com/3374055/45383721-52370380-b60c-11e8-81f5-fe2bfa858d58.png">


2. Chrome asks whether it should translate the page for some frameworks. Not sure if the popup has some influence on the measurement. Seems like others solved it by adding a prefs.json file (https://github.com/WPO-Foundation/wptagent/blob/master/internal/chrome_desktop.py#L148-L157). Didn't work on first attempt though.
<img width="1193" alt="bildschirmfoto 2018-09-11 um 21 33 46" src="https://user-images.githubusercontent.com/3374055/45383068-6aa61e80-b60a-11e8-8409-4d23b0727488.png">

**Comment by krausest** [comment]
Updated to lighthouse 3 - now with mobile simulation.
The differences are pretty clear by now (see also https://github.com/GoogleChrome/lighthouse/issues/6009), except for mainthread-work-breakdown, but results correspond to a command line invocation of lighthouse.

@leeoniya: Do the results look good to you?
@alexfmpe: Does it work for your CI approach?

**Comment by leeoniya** [comment]
the results look as expected.

> now with mobile simulation

so these numbers now represent startup metrics on mobile?

if so, it's a bit odd since the other tables have desktop numbers. eg, you'd never see both 400ms startup cost + 16ms swap rows perf. in general it's good to get better differentiation though.

**Comment by krausest** [comment]
Yes, only lighthouse number (i.e. the startup numbers) use the (lighthouse default) mobile simulation.
Running all benchmarks in mobile simulation would be great, but I currently have no idea how to achieve that.

**Comment by alexfmpe** [comment]
@krausest Can't tell at a glance - I can give it a go in a few days
