### ISSUE TITLE
setting `this.start` in angular 1.5?

### ISSUE THREAD

**Issue by paulirish** [krausest/js-framework-benchmark#48]
Looking at https://github.com/krausest/js-framework-benchmark/blob/master/angular-v1.5.8/src/HomeController.es6.js#L4 i see each part sets `this.start` to perf.now() but afaik this isn't used anywhere. 

is it neccessary? 

(Haven't looked to see if this is used in any other ones)

**Comment by krausest** [comment]
Hi Paul, this is used for console logging for all frameworks. The start time is picked up in stopMeasure and this is invoked with a setTimeout call to await the repaint.
The rationale behind that is explained [here](http://www.stefankrause.net/wp/?p=218) a bit more.

The main goal is to measure not just javascript execution duration, but also include rendering time. The webdriver-ts test driver uses the chrome timeline to extract the relevant events and measure duration from that. 
To get some feedback from running directly in the browser the duration is also approximately measured with that start / stopMeasure construction. I checked some time ago and it didn't influence the reported durations from the webdriver test driver.

**Comment by paulirish** [comment]
ah okay! that sounds pretty nice then. will have to check out how you're computing cost from the timeline files, as I've [done the same](https://github.com/paulirish/devtools-timeline-model).. :)
