### ISSUE TITLE
Ractive Add Test Optimization

### ISSUE THREAD

**Issue by benawhite** [krausest/js-framework-benchmark#49]
You can optimize the ractive test by using "array.push" rather than providing a completely new array for ractive to process.

```
add() {
        // this.data = this.data.concat(this.buildData(1000));
        this.data.push.apply(this.data, this.buildData(1000));
    }
```

**Comment by krausest** [comment]
I tried with both ractive versions (labeled "-2" in the screenshot). I'm afraid it doesn't make much of difference to me (little, but most likely not significant, faster for edge and slower for 0.7.3).
Did you see a larger effect?
<img width="406" alt="bildschirmfoto 2016-09-14 um 20 57 46" src="https://cloud.githubusercontent.com/assets/3374055/18525712/ede1bff0-7abd-11e6-856e-1bf1a793eacf.png">

**Comment by benawhite** [comment]
It may only have greater impact when the rows are more complex than the tests bing run here... e.g.  components/partials

**Comment by krausest** [comment]
Committed in 18c5c293c18a65336ea6268d55b2d5abb6e01eab
