### ISSUE TITLE
Feature request: add bundle size

### ISSUE THREAD

**Issue by PierBover** [krausest/js-framework-benchmark#493]
These benchmarks have become a reference in the JavaScript community.

While the main focus is performance, I think it would be a great idea to add the final bundle size to better judge every library/framework.

**Comment by ryansolid** [comment]
There is a total byte size metric. Or do you mean something different. That one measures the total size of transfered assets I believe. 

Do you mean JS package size including implementation, or library package size? Given bundling and code splitting the latter starts mattering less. The former is reflected in the total size all things being equal. With the variety of ways to bundle and serve out the functionality the wholistic measure is probably the best comparison.

**Comment by PierBover** [comment]
Oh wow I completely missed that!

Sorry, closing...

**Comment by MaxMilton** [comment]
It's not easily human readable or comparable but it is there. Perhaps we have some opportunities for improvements there.

**Comment by PierBover** [comment]
I think the reason is that there are no units in the numbers.

The same could be said for memory usage, although it's more clear since there is a big title that says:

> Memory allocation in MBs

It wouldn't hurt either if all results had its own unit (s, KB, MB, etc).
