### ISSUE TITLE
mithril v1.0 alpha bug

### ISSUE THREAD

**Issue by eshell** [krausest/js-framework-benchmark#51]
When I build and run the benchmark...

1. create 1000 rows (ok, logs run took xxx)
2. create 1000 rows again.  (bug, deletes old rows and creates next 1000 rows, but logs "delete took xxx". Then if I select, it deletes all the items. Or if I append, swap, or update, the log keeps saying "delete took xxx" instead of correct action)
2. (alternative). append, update, swap, select all work fine until I create a 2nd time.
3. once I hit clear, things go back to step 1.

i've been trying for a while to fix it, but i can't trace down how doing anything other than .remove() can trigger startMeasure with the name 'delete'.

https://youtu.be/pNpMYPMVduA

**Comment by krausest** [comment]
:frowning: I can confirm that your observation is right. Clicking create 1000 rows for the second times triggers the run method of the controller and then the remove method.
I renamed remove to delete in 37035163b8a86b8885229e48a879021bf059acc1  and now it seems to work and it is even _much_ faster (version -2 in the screenshot). Irritating...
<img width="290" alt="bildschirmfoto 2016-09-14 um 21 28 44" src="https://cloud.githubusercontent.com/assets/3374055/18526790/4bc2c2aa-7ac2-11e6-9a89-f681c4416e47.png">

**Comment by eshell** [comment]
Nice thanks!

**Comment by pygy** [comment]
the `onremove` attr defined on line 94 was interpreted as a lifecycle method. Components honour lifecycle hooks defined on both the component itself and its `attrs`.

**Comment by krausest** [comment]
I just checked - the bug you reported doesn't happen for mithril 0.2.5 and doesn't change the performance.

**Comment by pygy** [comment]
The hooks in v0.2.x are defined differently, so it's not surprising.

Thanks for the hard work on the benchmark. You may find it irritating, but I'm most happy to see the Mithril rewrite fare better. Pinging @lhorie

**Comment by pygy** [comment]
@krausest in the table you posted above, the ratio for the "select row" benchamrk is 1, even though Mithril takes three times as long as vanilla JS... "partial update" is off too.

**Comment by krausest** [comment]
Yes, but that is intentional. Anything faster than 16 msecs will be treated as lasting one frame (see #35).
