### ISSUE TITLE
Feature request: Add repository links 

### ISSUE THREAD

**Issue by GHNewbiee** [krausest/js-framework-benchmark#527]
It will make the access to each project easier; no need to search.

Tia

**Comment by krausest** [comment]
What would be the best place for it? In package.json?

**Comment by GHNewbiee** [comment]
IMHO, definitely on the result table/scoreboard, because it is mostly used. You read, you compare, you click on the project name.

**Comment by krausest** [comment]
Just noticed that this is fixed since a while.
