### ISSUE TITLE
Update Preact to latest 10 version

### ISSUE THREAD

**Issue by artemirq** [krausest/js-framework-benchmark#536]

**Comment by MaxMilton** [comment]
Probably better to wait until it hits GA.

**Comment by vuhg** [comment]
It does! https://github.com/preactjs/preact/releases/tag/10.0.0

**Comment by krausest** [comment]
I thought this should be easy, but I'm running into a issue with swap rows. It doesn't re-render and later on selecting the 2nd or 999th row moves the selected row (but not the other).

@artemirq @MaxMilton @vuhg I'm a bit uncertain whether this is really a preact bug. Can you please take a look at it?
I've created branch preact10 with the [updates](https://github.com/krausest/js-framework-benchmark/commit/c7b930244331da5334d85f1a5c72cfead51f9109).

If you just want to build preact this should be the fastest way:

1. Clone the repo `git clone https://github.com/krausest/js-framework-benchmark.git`
2. `cd js-framework-benchmark`
3. Checkout the branch `git checkout preact10`
4. Install http-server (and few others) `npm install`
5. Start http-server `npm start`
6. Go to preact `cd frameworks` `cd keyed` `cd preact` 
7. Build preact `npm install` `npm run build-prod`
8. Open the preact implementation: http://localhost:8080/frameworks/keyed/preact/index.html
9. Click 'Create 1,000 rows'
10. Click 'Swap rows'
11. Row 2 and row 999 should have been swapped, but aren't (it works an master for preact 8.4.2 - just checkout master `rm -rf node_modules dist package-lock.json` and start with #7 again)

**Comment by vuhg** [comment]
Hey krausest,

I log and see that data order is changed, but it doesn't change (render) visually.
But it does change (render) visually if i use `label` instead of `id` as key. Like following:
```jsx
<Row key={d.label} data={d} onClick={this.select} onDelete={this.delete} styleClass={d.id === this.state.store.selected ? 'danger':''}>
</Row>
```

As developit said on
https://stackoverflow.com/questions/42773892/wrong-components-rendered-by-preact/42775667#42775667,
`TL,DR: never use an array index (iteration index) as key. At best it's mimicking the default behavior (top-down child reordering), but more often it just pushes all diffing onto the last child.`

**Comment by ryansolid** [comment]
The `id` is not the `index`. It looks similar but it is newly generated with each batch and sticks with the data. For instance when there is a swap row the ids are no longer in ascending order. On a replace the ids go from being [n, n + 999] to [n + 1000, n + 1999] and so on. Each `id` is uniquely assigned, whereas the `label` is randomly constructed from a lookup table and is not guaranteed to be unique and cannot be used as a `key`. There is a whole second category of tests(non-keyed) that use no `key` expecting the fallback to the `index` as the behavior understanding the repercussions but the steps outlined here are not for those tests.

**Comment by vuhg** [comment]
Hey @krausest,
Update `preact` to latest version `10.0.1` will fix the keyed updates.
```
"dependencies": {
    "@babel/plugin-transform-react-jsx": "7.3.0",
    "preact": "10.0.1"
  }
```

**Comment by krausest** [comment]
Finally: https://krausest.github.io/js-framework-benchmark/current.html
