### ISSUE TITLE
Migrate reference platform  to linux and no longer to windows

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#544]
Since I bought a new laptop and it's not an apple it's time to move the reference platform to windows.
There are three steps:

1. Build and serve the frameworks on windows or in a docker container
2. Check if it's necessary to use throttlestep to get results with an acceptable variance and if so find sensible setting
3. Run the benchmark on windows

Each will be tracked in its own issue.

**Comment by krausest** [comment]
Windows is much more problematic than I thought.
On OSX the whole benchmark suite runs in about 200 seconds for vanillajs, on windows it takes 480 seconds. It takes ages for chromedriver to start navigation.

**Comment by krausest** [comment]
And what's even worse. The benchmarks run neither stable nor reliably. It seems like the benchmark's CPU throttling causes massive problems. I can't finish a complete round for the benchmark on windows.
Results e.g. for benchmark 03 vary too much to make sense:
observed values for vanillajs-keyed: 559.796, 708.833, 749.205, **1093.689**, **514.899**, 607.662, 668.354, 589.515, 575.817, 868.279. standardDeviation: 175.26953894150196,
or for svelte: 776.772, 1262.726, **1542.768**, 637.719, 623.964, **615.925**, 719.279, 747.875, 775.597, 753.553. standardDeviation: 307.0907364429391
No background processes to blame.

**Comment by ryansolid** [comment]
I have witnessed exactly the same whenever I run the benchmarks from windows (ie have WSL run the server and then build and run the benchmark from windows). When I was using x11 from WSL I didn't have this problem though, but I can't claim that I had all benchmarks running.

**Comment by krausest** [comment]
I was able to sucessfully complete a run on windows - in just 22 hours...
Results are [here](https://krausest.github.io/js-framework-benchmark/2019/table_win_190624.html)
Haven't carefully checked all results yet (e.g. re-run results with high variance)

**Comment by ryansolid** [comment]
Yeah this reminds me of some of the runs I have on Windows. It isn't even comparable variance issues. Like for 10k rows most libraries are around +-35-50 range. But I know that certain libraries are definitely faster than others in certain areas (I wrote them) and it feels like a roll of the die which numbers I get within a certain range. Like solid, ko-jsx, and mobx-jsx are not particularly different on variance but solid should be noticeably faster than both. There might be other factors at play. But my experience on Windows has been run stuff over and over until I find the best numbers I can get for each library. Not practical to do here. But comparing variance of results over a given run while sometimes give an indicator haven't necessarily been consistent to know where the results aren't where they should be.

**Comment by krausest** [comment]
So here are three runs for the same chrome/chromium and benchmark versions:
OSX, MacBook (~8 h run time): 
https://krausest.github.io/js-framework-benchmark/2019/table_osx_190624.html

Razer Blade 15, Windows (~20 h runt time):
https://krausest.github.io/js-framework-benchmark/2019/table_win_190624.html
Razer Blade 15, Linux (~8 h run time):
https://krausest.github.io/js-framework-benchmark/2019/table_lin_190625.html

Overall I'm quite happy with the results on the new machine. Observed variance seems to be generally no worse than on OSX (despite the i8750H being a hothead), but it's absolutely essential to run only on AC: Variance on battery is crazy (never an issue on the macbook). The performance difference between the old MacBook and the new Razer Blade isn't enough to justify the investment :smile: 

Windows behaves strange for benchmarks with a CPU slowdown, the effective slow down is not comparable with OSX or linux. For the others windows is a bit faster than Linux. 
When I look at the benchmarks without CPU slowdown results look rather stable to me:
OSX:
![osx](https://user-images.githubusercontent.com/3374055/60129615-b723aa80-9795-11e9-8842-55bb4a7c5b08.png)
Linux:
![Linux](https://user-images.githubusercontent.com/3374055/60129639-c145a900-9795-11e9-9d2a-060863e4d402.png)
Windows:
![Win](https://user-images.githubusercontent.com/3374055/60129649-c9054d80-9795-11e9-9ff0-791622d852d6.png)

I think it's about time to switch (especially since there's a battery recall for the macbook) and I'm currently really preferring Linux.
@ryansolid @leeoniya  @localvoid @ all Any objections?

**Comment by KyivJunta** [comment]
Did you experiment with Power Plan? There are cases when switching to Performance Power Plan gains viable stability and performance boost. Also consider security patches which Intel CPUs got in Windows 10, which, sometimes, makes Win 10 platform not so consistent in terms of raw CPU performance. Old good Linux will be more preferable in such a case.

**Comment by krausest** [comment]
@KyivJunta Yes, but mostly for cinebench, where I was able to get good results in conjunction with undervolting. When I checked this benchmark it didn‘t help for variance on battery though and first runs on windows had massive stability issues (mostly due to chromedriver before v75). Since variance is acceptable and it doesn’t crash anymore I didn‘t use any undervolting for the runs above.

**Comment by ryansolid** [comment]
Maybe there is just differences in the platforms. I'm always looking at relative scores between libraries in different runs and noticing when they change or not. It's been pretty consistent for the most part on MacOSX with exception when new versions of chrome change performance in certain areas. I always see a run and go oh that run is particularly good or poor for said library on this benchmark and kind of interpolate in my head. Like recently Sinuous partial update on the last run was probably worse than average even though the variance did not suggest as much. So when I look at Linux and Windows it's immediately different. I guess that just comes with the territory.  So this seems reasonable. Especially if you get Linux running in reasonable time range.

I will have to look into why Solid is getting punished so hard on the 10k rows on both non-macosx platforms. It doesn't make any sense to me. Historically it's about equal to ivi slotting in right under Surplus. Windows is just strange. How ko-jsx is so good on windows equally makes no sense. Maybe I've been just looking at micro-optimizations too long.

**Comment by localvoid** [comment]
> @krausest Any objections?

None.

> @KyivJunta There are cases when switching to Performance Power Plan gains viable stability and performance boost. Also consider security patches which Intel CPUs got in Windows 10, which, sometimes, makes Win 10 platform not so consistent in terms of raw CPU performance. Old good Linux will be more preferable in such a case.

Old good linux also has [CPU governors](https://www.kernel.org/doc/Documentation/cpu-freq/governors.txt) and [spectre/meltdown mitigations](https://access.redhat.com/articles/3311301).

--- 

If someone has time to add measuring [retired instruction counts](https://chromium-review.googlesource.com/c/chromium/src/+/1436079) to this benchmark, it could reduce noise ([Better Web Benchmarking](https://code.fb.com/web/browser-contributions/))

**Comment by leeoniya** [comment]
👍

**Comment by krausest** [comment]
New results are available for linux 5.2 with mitigations=off option. Wouldn't have thought that the difference might be that big.

**Comment by ryansolid** [comment]
@krausest  Whatever you did seems to fix the issue with Solid and proxies. Things are back to where they should be. (Solid Signals had a particularly bad 10k run since it should be faster than the Proxy version but results look a lot better)

**Comment by krausest** [comment]
After upgrading to kernel 5.2 I checked for vanillajs that the speed bump is really caused by the CPU security workarounds by toggling the migitations=off kernel parameter:
https://linuxreviews.org/HOWTO_make_Linux_run_blazing_fast_(again)_on_Intel_CPUs

**Comment by krausest** [comment]
I just updated to Chromium and was very surprised to see that vanillajs-keyed create 1,000 rows is now back to 105 msecs again. Just to make sure I didn't dream those numbers for chromium 75 I downgraded to Chromium 75 and indeed got about 85 msecs.
So please expect results to go up again!

And it looks like --disable-infobars doesn't work anymore for Chrome 76.
