### ISSUE TITLE
Add LiteralJS

### ISSUE THREAD

**Issue by Mikeysax** [krausest/js-framework-benchmark#545]
LiteralJS: https://literaljs.com/

Anyone up for adding LiteralJS for performance results?

**Comment by leeoniya** [comment]
does LiteralJS support keyed reconciliation?

**Comment by Mikeysax** [comment]
No, LiteralJS doesn't support keyed reconciliation.

**Comment by leeoniya** [comment]
you're welcome to submit a PR for a non-keyd LiteralJS impl

**Comment by Mikeysax** [comment]
Awesome, I would love to when I get more time. 
If someone else would like to, please post here, otherwise I will when get the chance.

**Comment by Mikeysax** [comment]
@leeoniya I've added a PR for LiteralJS nonkeyed.

**Comment by leeoniya** [comment]
thanks @Mikeysax ,

i think @krausest is in the middle of a macOS -> Windows transition and still working out the kinks in the build/test infra. it's not unusual for PRs to hang out for a week or two before review/merge. plus there's #304 to keep in mind.

**Comment by krausest** [comment]
Thanks - fixed with 3a66bc8344fcd76ef0ed81acfd267e650432ff5a
