### ISSUE TITLE
With native UI library testing?

### ISSUE THREAD

**Issue by brodybits** [krausest/js-framework-benchmark#547]
Such as React Native, NativeScript, [SyrJS](https://github.com/syrjs), Weex, etc., with and without higher-level state management libraries.

Perhaps similar to #63 - test on mobile devices?

I wonder how practical this would be:)

P.S. A quick look at the code that was added for some statistical testing, as requested in #196, triggers the following comment: I would say that I do not find proper benchmark testing so easy in general. I would not be surprised if this idea would prove to be completely impractical, not feasible.

**Comment by krausest** [comment]
I think that's out of scope of this benchmark. Taming chrome driver is already enough to fill my spare time 😄
