### ISSUE TITLE
[Sticky & fixed] It looks the performance logging options affect the performance of frameworks.

### ISSUE THREAD

**Issue by ismail-codar** [krausest/js-framework-benchmark#549]
I'm working on a new framework called [fidan](https://github.com/ismail-codar/fidan).
The actual result on the right according to the screenshot below. Create rows benchmark is slow.

When I investigated the cause of the slowdown I saw that it was related to https://github.com/krausest/js-framework-benchmark/blob/master/webdriver-ts/src/forkedBenchmarkRunner.ts#L342. If I change this line to`traceCategories: "devtools.timeline,blink.user_timing"`, I see the result on the right. Pretty fast.

I don't know why, but there seems to be something wrong.

Additional note: When I logging timings to the console from http://127.0.0.1:8080/frameworks/keyed/fidan, I see fast results similar to those on the left.

<img width="470" alt="fidan" src="https://user-images.githubusercontent.com/282104/56076815-d5584c00-5ddd-11e9-8320-b87954b68480.png">

**Comment by krausest** [comment]
That difference looks worrying!

As a first quick check I ran a single create rows benchmark for a few frameworks. I got the following results:
<img width="276" alt="Bildschirmfoto 2019-04-13 um 13 08 00" src="https://user-images.githubusercontent.com/3374055/56078874-2facd900-5ded-11e9-9c39-4c0780198bc7.png">
Could indeed be that the old code is slightly slower than with your change (but I need more measurements to make sure this isn't due to some background process and last published results are also a bit faster), but it's nowhere close to the difference you observe. 
What machine and platform are you running? 
Is the difference for other frameworks similar large on your machine?
Could you please post a PR for fidan such that I can take a look at the difference on my machine?

**Comment by ismail-codar** [comment]
For example, I saw that vanillajs was no different. But there is a big difference in my framework.  My framework is functional reactive style so maybe related to it or something else.  I will prepare PR. Thanks for the your great working.

**Comment by ismail-codar** [comment]
Hi @krausest  I just sent a PR. 
Please note: Running it from http://localhost:8080/frameworks/keyed/fidan/ looks fast (console logging) similiar to changing [this line](https://github.com/krausest/js-framework-benchmark/blob/master/webdriver-ts/src/forkedBenchmarkRunner.ts#L342) to `traceCategories: "devtools.timeline,blink.user_timing"`

**Comment by krausest** [comment]
I got the PR from İsmail and ran the create 1,000 rows benchmark for all frameworks. Here's the comparison:
Upper screenshot is results table from lighthouse's traceCategories, lower from İsmail's traceCategories:
<img width="1322" alt="Bildschirmfoto 2019-04-14 um 16 05 25" src="https://user-images.githubusercontent.com/3374055/56094053-f4370b00-5ecf-11e9-8b25-a5f48ac52794.png">

<img width="1334" alt="Bildschirmfoto 2019-04-14 um 16 07 16" src="https://user-images.githubusercontent.com/3374055/56094054-fb5e1900-5ecf-11e9-8019-6a0dc6ba52fa.png">

<img width="1320" alt="Bildschirmfoto 2019-04-14 um 16 08 20" src="https://user-images.githubusercontent.com/3374055/56094055-00bb6380-5ed0-11e9-814c-3d7131f192b6.png">

<img width="1358" alt="Bildschirmfoto 2019-04-14 um 16 09 17" src="https://user-images.githubusercontent.com/3374055/56094060-0b75f880-5ed0-11e9-8bb8-8d12f0fad88c.png">

Frameworks with a notable difference are:
* Marionette
* Svelte
* Fidan (not in the screenshot for lighthouse's traceCategories it's about 260 msecs vs. 180 msecs)

I'm not sure about Datum. Numbers differ, but not as much as for the others and std deviation was very high for the lighthouse traceCategories.

lighthouse's traceCategories are: -*, disabled-by-default-lighthouse, v8, v8.execute, blink.user_timing, blink.console, devtools.timeline, disabled-by-default-devtools.timeline, disabled-by-default-devtools.screenshot, disabled-by-default-devtools.timeline.stack
İsmail's traceCategories are: devtools.timeline,blink.user_timing

@paulfalgout @Rich-Harris Sorry @ismail-codar - seems like my selection of traceCategories penalised your frameworks. I'll update results soon. 

Any idea what's causing this issue?

**Comment by paulfalgout** [comment]
Marionette by itself looks the same, it's the jquery bundle that's so different.  So something with jquery I guess ¯\_(ツ)_/¯  Doesn't seem like jquery 3.4.0 addresses anything like that, so it might just be the way things are on that one.

**Comment by krausest** [comment]
Updates results have been posted. Thanks a lot for reporting this issue!
I'll leave it open for further comments and for others to notice!

**Comment by krausest** [comment]
It really seems as if svelte was badly penalised. New results for the keyed version (svelte was between datum and binding.scala in the old version):
<img width="914" alt="Bildschirmfoto 2019-04-14 um 22 07 24" src="https://user-images.githubusercontent.com/3374055/56098570-ce2a5e80-5f01-11e9-82a1-21cec3517556.png">
