### ISSUE TITLE
Add Elm

### ISSUE THREAD

**Issue by ZombieHippie** [krausest/js-framework-benchmark#55]
Is there any chance we can add Elm to this benchmark, I'd love to see another benchmark like [the creator's blog benchmark](http://elm-lang.org/blog/blazing-fast-html) in this suite of benchmarks!

Let me know if that seems appropriate or not :-)

**Comment by krausest** [comment]
If anyone sends me a PR I'll happily add it. It's just that I don't think I'm able to write it in idiomatic elm.

**Comment by jiyinyiyong** [comment]
To support Elm, one needs to install Elm, which I think can not be achieved with npm. And if it does, I think we can add framework on the ClojureScript side too.

**Comment by ZombieHippie** [comment]
Good suggestion! You can compile Elm without installing it globally just
like any other npm CLI tool. Either through npm scripts, or
node_modules/.bin/elm.cmd or whatever.
