### ISSUE TITLE
Raw results

### ISSUE THREAD

**Issue by PierBover** [krausest/js-framework-benchmark#582]
I was considering making some charts with the results of these benchmarks but apparently the results are only available in the `table.html` file.

@krausest would you accept a PR for adding a `results.json` in the repo?

**Comment by krausest** [comment]
Yes - I think so (but of course I need to take a look at it).

**Comment by krausest** [comment]
JFI - results are also in webdriver-ts/results/*.json (not committed) and in webdriver-ts-results/src/results.ts.

**Comment by PierBover** [comment]
So why not simply commit those JSON files?

**Comment by leeoniya** [comment]
@krausest it would definitely make life easier if the raw results were stored at least in a plain json file.

i've had to resort to parsing them out of `results.ts` and converting them back to `.json` files when building out [results-ui](https://github.com/krausest/js-framework-benchmark/tree/master/results-ui) and i can't say it was a particularly joyful experience.

**Comment by krausest** [comment]
I've committed a prototype for that. Please let me know if it helps.
the `npm run results` task calls createResultJS.ts which outputs now an additional `results.json` file in `webdriver-ts`. I've committed a first version of it (values are from a windows run - i.e. not identical with the values from the results table which is still on osx.). Please take a look at it.
It contains the name of the benchmark, framework and the raw values (and does currently not include mean, median and other statistics)

**Comment by PierBover** [comment]
Here it is if anyone wants to see it: https://raw.githubusercontent.com/krausest/js-framework-benchmark/master/webdriver-ts/results.json

For me that's perfect. Thanks @krausest I'll be closing this now.

**Comment by krausest** [comment]
You're welcome. I'd love to see those graphs - feel free to post a link when they're ready.

**Comment by leeoniya** [comment]
sweet!
