### ISSUE TITLE
Make rust based implementations work in the docker container

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#586]
@Pauan I've opened that issue for working on the rust based frameworks.

The ultimate goal is to perform the build in the docker containter (https://github.com/krausest/js-framework-benchmark/issues/546#issuecomment-488811952).
Here are the (erratic) steps I tried so far:
`npm install --save-dev rimraf webpack webpack-cli @wasm-tool/wasm-pack-plugin`  
Use rust-up to install rust (will be baked into the docker image at some point)
 `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
Is there a better way to get a specific version?
`source $HOME/.cargo/env`

Now rust seems to be installed:
```
[root@550cf95bb54a dominator]# rust -V
bash: rust: command not found
[root@550cf95bb54a dominator]# rustc -V
rustc 1.35.0 (3c235d560 2019-05-20)
[root@550cf95bb54a dominator]# 
```

Then try to build:
`npm run build-force`:
```
[root@550cf95bb54a dominator]# npm run build-prod-force

> js-framework-benchmark-dominator@1.0.0 build-prod-force /build/frameworks/keyed/dominator
> rimraf bundled-dist pkg && webpack

🧐  Checking for wasm-pack...

ℹ️  Installing wasm-pack 

wasm-pack error: undefined

ERROR in ./js/index.js
Module not found: Error: Can't resolve '../pkg/index.js' in '/build/frameworks/keyed/dominator/js'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! js-framework-benchmark-dominator@1.0.0 build-prod-force: `rimraf bundled-dist pkg && webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the js-framework-benchmark-dominator@1.0.0 build-prod-force script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-23T15_44_37_758Z-debug.log

```

**Comment by Pauan** [comment]
In the README I give the exact directions. You have to manually install wasm-pack from [here](https://rustwasm.github.io/wasm-pack/) (for example by using ` curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh `).

After rustup and wasm-pack are installed, you need to run these commands:

```sh
rustup toolchain install nightly
rustup override set nightly
npm install
npm run build-prod-force
```

And that should work.

It is possible to use rustup to download a specific version of the Rust toolchain. For example, rather than using `nightly` you can instead use `rustup toolchain install nightly-2019-06-23`

And then you need to use `rustup override set nightly-2019-06-23` to enable it.

**Comment by krausest** [comment]
Thanks - it worked when installed manually. Now I'll try to somehow integrate it into to the docker build (might take some days). I'll report back.

**Comment by krausest** [comment]
Thanks to @Pauan rust build work in the docker container.
Only non-keyed/stdwdeb still needs updating. I'll check the next few days if I can build it like the keyed version.

**Comment by Pauan** [comment]
Oops, I overlooked non-keyed/stdweb, I'll send a PR.

**Comment by krausest** [comment]
Great - thanks!
