### ISSUE TITLE
React one can be a little faster

### ISSUE THREAD

**Issue by jiyinyiyong** [krausest/js-framework-benchmark#60]
Didn't try but in theory by making the static part a component and mark `shouldComponentUpdate: -> false` will make it faster.
https://github.com/krausest/js-framework-benchmark/blob/master/react-v15.3.1/src/Main.jsx#L94

My Macbook Air is too slow to try...

**Comment by suhaotian** [comment]
如果单独拆出去，应该会快很多

**Comment by krausest** [comment]
I'm closing this one. Please submit a PR if it works in practice ;-)

**Comment by jiyinyiyong** [comment]
I have to say cloning and testing this whole repo is heavy work, I did it once but not confident about doing it again. Sorry no PR.
