### ISSUE TITLE
Add Microsoft's Blazor

### ISSUE THREAD

**Issue by elgunhuseynli** [krausest/js-framework-benchmark#605]
Microsoft officially released preview version of Blazor. Blazor is similar to ReactJS but runs on WebAssembly with C#. And I think Blazor should be much faster than other Web UI frameworks thanks to it WebAssembly nature.

Should we add some benchmarks for Blazor?

[blazor.net](https://blazor.net)
[demo](https://blazor-demo.github.io)

**Comment by ryansolid** [comment]
We already have a few Rust WASM ones on here. I know getting the build to work is more of a challenge, it would be great to have more WASM. It is definitely an area of interest. While when it comes to DOM, WASM is slower currently. It feels like the progress there is coming along rapidly. If someone feels comfortable enough they can submit a PR.

In terms of expectations and speed with WASM and the DOM I think this comment is particularly insightful. https://github.com/krausest/js-framework-benchmark/pull/589#issuecomment-511471224. Until we get to that point where WASM can match up I think it would be great to get more library implementations to understand tradeoffs etc.

**Comment by ryansolid** [comment]
@elgunhuseynli  Hey, looks like a preview build has just been merged: https://github.com/krausest/js-framework-benchmark/pull/723
Still super early days so wouldn't put too much weight in the performance numbers but you can see the results for keyed implementation here: https://krausest.github.io/js-framework-benchmark/current.html
