### ISSUE TITLE
 selenium.common.exceptions.WebDriverException: Message: invalid argument: unrecognized capability: chromeOptions

### ISSUE THREAD

**Issue by vynguyen0611** [krausest/js-framework-benchmark#627]
I encounter an issue: "selenium.common.exceptions.WebDriverException: Message: invalid argument: unrecognized capability: chromeOptions"

I have tried various chromedriver versions, including newer and older but same. I'm using Version 76.0.3809.100 (Official Build) (64-bit).

Please help me out.

**Comment by krausest** [comment]
Sorry, never seen that error. Can you please remove all globally installed chromedriver and webdriver versions? webdriver-ts installs the correct version locally.

Please try the following and post the results here:
```cd webdriver-ts```
```chromedriver --version```
(Should report something like "Command 'chromedriver' not found")
```./node_modules/.bin/chromedriver --version```

Can you please post a log file from  `npm bench`?

**Comment by krausest** [comment]
I'm closing older issues that won't get fixed.
