### ISSUE TITLE
How does this benchmark get consistent results?

### ISSUE THREAD

**Issue by luwes** [krausest/js-framework-benchmark#628]
I was wondering which parts of this benchmark make the results consistent?
Is it the forked child process? the chromedriver?

Asking because I set up a `js-framework-benchmark` lite which is quite variable at the moment. Can be seen at https://luwes.github.io/sinuous/bench/
It just uses Puppeteer because it seemed simpler for my purpose.

The idea was to have this bench run on every release and have each version compared to Vanilla JS and React for now, and have it nicely plotted out to make the most drastic visuals 😄

The code is very minimal, it matches most of the basic tests in this benchmark, only problem is that the `standardDeviation` can be quite large sometimes.

https://github.com/luwes/sinuous/tree/master/bench
(Feel free to use the code in anyway you like)

**Comment by krausest** [comment]
I'm on holidays right now so I could just take a short look at your code.
Is my assumption correct that you are trying to measure the duration of a benchmark by measuring the difference between two Performance.getMetrics().Timestamp values (https://github.com/luwes/sinuous/blob/master/bench/utils.js#L33-L40) from the test driver client?

If that's right you're depending on puppeter's latency for calls to chrome. The js-framework-benchmark measures duration right from chrome's timeline and thus avoids any dependency on test driver latency.
(Maybe a smaller issue: Is there a guarantee that chrome has finished painting and compositing before the benchmark's xpath condition is fulfilled? That's another importance principle of my benchmark: It measures duration from the initial click event to the end of the paint event.)

**Comment by krausest** [comment]
Just a second thought: Unless I'm completely mistaken you're including the check whether the benchmark finished in your measurement (like testTextContains). AFAIK puppeteer uses RAF-polling for those waitFor calls.

**Comment by luwes** [comment]
thanks @krausest! this is super useful info.

yes, it's the delta of those 2 `Performance.getMetrics().Timestamp` values.
I'll see if I can use the same performance timings as yours.

ah I see, I don't think the paint is ensured at the moment.
will look into the RAF polling as well. 
great things to look into!

**Comment by krausest** [comment]
Maybe you could try the Puppeteer's [TaskDuration metric](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagemetrics), but it seems pretty undocumented what it really measures.  Something that also kept me from using Angular Benchpress and other tools (I've blogged [about that some time ago](https://www.stefankrause.net/wp/?p=218) )

**Comment by luwes** [comment]
amazing results with using the timeline directly. 
https://luwes.github.io/sinuous/bench/

from 3 runs per lib/bench:

<img width="834" alt="Screen Shot 2019-08-29 at 10 09 26 AM" src="https://user-images.githubusercontent.com/360826/63947595-33ac6100-ca45-11e9-87ad-92775650fb3c.png">

only test 3 and 4 is strange, React outperforms Sinuous 😅. locally as well.
have to dig into why that is, I thought it could be the waitFor but it's really consistent. maybe something with the throttling, not sure.

**Comment by krausest** [comment]
Good to hear this helped. I think I can close this issue now.
