### ISSUE TITLE
Is it possible to run the tests on mobile devices?

### ISSUE THREAD

**Issue by datrinh** [krausest/js-framework-benchmark#63]
As the title states: I would like to run the benchmarks on my android phone. Is that possible?

**Comment by guanxi55nba** [comment]
It's a good idea. Is there anyone know how to do that ?

**Comment by axemclion** [comment]
You would need to change the options sent to Web driver to point it to a real device [in this line](https://github.com/krausest/js-framework-benchmark/blob/master/webdriver-ts/src/benchmarkRunner.ts#L63).
it should say 

```
"browsers": [{
		"browserName": "android"
}]
```

**Comment by krausest** [comment]
I'm closing some older issues that won't get fixed.
