### ISSUE TITLE
Strange (long) results for Select Row, Swap Rows  and Partial Update benchmarks

### ISSUE THREAD

**Issue by mmichlin66** [krausest/js-framework-benchmark#633]
Hi,

I am in the process of testing my library and I am comparing the results (locally) to preact. I noticed that when I do the Select Row tests manually - that is, using the Chrome's Performance tab - my library produces results in the 3-4 ms range and preact in the 4-5 ms range  - pretty consistently. This is also what is written to the console. However, when I ran the benchmark suite, my library showed times of around 60 ms and preact around 115 ms.

A similar issue occurs with the Swap Rows benchmark: 10 ms versus 40 ms for my library and 20 ms versus 70 ms for preact.

(Just to make sure, I read your article about what and how you measure, and, when doing manual tests, I take the time from the event firing up to the end of the first paint. Since my library uses requestAnimationFrame, this time covers two JS tasks. The time reported to the console even includes the third task - the processing of setTimeout( ..., 0).)

For the Partial Update benchmark, I also see the results differ dramatically (more than 10-fold) from the manual tests; however, I think the problem is in the test description: the description says "updating every 10th row for 1,000 rows", while the time correspond to a test with 10,000 rows. I also noticed that in one of the previous rounds (8th) the description indeed said "10,000" rows.

Thank you!

**Comment by ryansolid** [comment]
Some of the tests use CPU throttling. Most of the 10k tests except test 7 have reduced rows but upped throttling. The description in the results is current I believe (https://krausest.github.io/js-framework-benchmark/current.html). The README is probably out of date. If you are just running tests in the browser you won't have the slowdown applied.

**Comment by mmichlin66** [comment]
Thank you Ryan. I tried 4x slowdown in Chrome for the Swap Rows test. My results are worse than before of course, but still better than I got during the benchmark runs.

Well, I guess I will close the issue and will wait until the official runs.

Thank you again!

**Comment by krausest** [comment]
@michaelboulton It's exactly as Ryan explained. The description of the CPU throttling factor in the table is also correct (i.e. what's currently used in the code). But when I tried to migrate from OSX to Windows 10 I had the impression that the CPU throttling results vary a lot between OS. Looking forward to your PR.
@ryansolid Thanks for answering!
