### ISSUE TITLE
HTML is incorrect for some frameworks

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#634]
(Found out some time ago but didn't make it into a seperate issue, must check which frameworks are obsolete from those below)
Some frameworks do not create exactly the expected HTML output. To check whether the html is correct please run the keyed check:
``cd webdriver-ts```
and check the implementation
``npm run isKeyed keyed/angularjs```
- [x]  In keyed/plastiq aria-hidden=true is missing in third td
- [x]  In */rawact aria-hidden=true is missing in third td
- [ ]  In non-keyed/cyclejs aria-hidden=true is missing in third td
- [ ]  In non-keyed/stem aria-hidden=true is missing in third td

**Comment by ingdev** [comment]
i have some problems (HTML) with angular 8  too.

**Comment by krausest** [comment]
Dare to give some details?

**Comment by ingdev** [comment]
![image](https://user-images.githubusercontent.com/9503831/65457243-23f02480-de19-11e9-8c95-14009aa4b979.png)

**Comment by krausest** [comment]
Yes, this was reported in #532 (it doesn't compile. But if it would I swear the html would be correct :-)
I'm afraid not all implementations build on windows natively and angular is one of them...
You can use the docker build (see the wiki for instructions) or you can use WSL 2 which should work for building angular (the webdriver-ts should be built in native windows since it should installl the windows chromedriver to run the tests)

**Comment by ingdev** [comment]
thank you but , can i find angular version 7 please ?
