### ISSUE TITLE
Framework categorization: keyed or non-keyed.

### ISSUE THREAD

**Issue by mmichlin66** [krausest/js-framework-benchmark#637]
This is more of a question than an issue.

When I run `npm run check` (or `npm run isKeyed`) on my new framework ([mimbl](http://mmichlin66.github.io/mimbl/mimblAbout.html)) the tool reports that the framework is keyed for `remove-row` and non-keyed for `run` and `swap rows` benchmarks. The feature of my framework (and a key one) is that developers don't specify keys for components in lists; therefore, it should probably be categorized as non-keyed. However, internally the framework does use keys - keys are actually the component instances themselves - and thus it can efficiently match between items in the old and new lists. I don't know how your tool does it, but it does understand that in the "remove-row" benchmark the framework knows to remove a single specific row instead of changing 999 rows and removing the last one.

So my practical question is how I should categorize my framework. It seems that the tool is not happy with either. It also says that the framework results will appear as non-keyed, although when I run `npm run bench keyed/mimbl` it happily puts the results as keyed.

**Comment by krausest** [comment]
A keyed framework must be keyed for all operations, i.e. all three tested operations must be keyed. Non-keyed frameworks can do what they want, but it might be fastest if they are non-keyed in all cases.
I added some logging yesterday, maybe I should have added an error message for keyed and a warning message for non-keyed to make that clearer.

**Comment by mmichlin66** [comment]
That makes me wonder whether the keyed/non-keyed differentiation is an artificial one. One would assume that for each framework there should be a single solution best suited for the task t hand. I am of course not talking about taking advantage of knowing what the test is specifically doing (e.g. knowing that the `swap rows` benchmark swaps the 2nd row with the 999th one). I am talking about an idiomatic use of a framework.

To be honest, I am somewhat concerned that my framework is going to be categorized as non-keyed. This is because while writing non-keyed reconciliation is easier for frameworks' authors, its use may cause errors. In the description of [round 8](https://www.stefankrause.net/wp/?p=504) you write:

>From the framework perspective handling only non-keyed updates makes dom reconciliation much easier. If you want my opinion: Choose a framework that supports keyed updates.

What if you base the categorization on the keyed versus non-keyed frameworks only on the benchmarks that have real implications if keys are not used: e.g. `swap rows` and `add rows`?

**Comment by ryansolid** [comment]
What benchmarks would it not have real implications? As far as I see it the implications are always present and basically the same. Whenever a data node has the potential of grabbing a different DOM node, it is non-keyed, and the issues warned about can happen.

**Comment by mmichlin66** [comment]
Hmm... I think I understand the problem.

In my implementation, the keyed elements/components in the new list are always matched with the same-keyed elements/components in the old list; however, the remaining elements/components (either not keyed or with non-matching keys) are not necessarily removed but can be reused - provided they are of the same type. This gives a big boost in, for example, virtualized scenarios where, say during scrolling a table, some rows are added, some remain and some removed. The remaining rows will not be touched (because of the keys) but the removed rows could be re-used by the added ones (the DOM nodes are moved, but this might be cheaper than removing and adding new ones).

But I see that it can probably hinder some animations, although I need to think more about it.
