### ISSUE TITLE
Keyed/non-keyed status of "run" benchmark reported based on "swap rows" benchmark

### ISSUE THREAD

**Issue by mmichlin66** [krausest/js-framework-benchmark#638]
I was playing with keyed/non-keyed versions of my framework and I think I found a minor issue with reporting the status of the "run" benchmark in the `npm run check` tool.

I had the "run" benchmark behaving in a keyed way; that is, when I click the "Create 1,000 rows" for a second time, the previous 1,000 DOM nodes were deleted and the new ones were inserted. My "remove row" was also implemented as keyed. At the same time I had the "swap rows" behaving in a non-keyed way; that is, the two nodes were updated instead of being moved. In this state, when I ran the `check` tool, it reported the following:

>mimbl-v0.1.6-keyed is non-keyed for 'run benchmark' and keyed for 'remove row benchmark' non-keyed for 'swap rows benchmark' . It'll appear as non-keyed in the results

After I changed the "swap rows" benchmark to behave in a keyed way, the `check` tool reported all three benchmarks as keyed:

>mimbl-v0.1.6-keyed is keyed for 'run benchmark' and keyed for 'remove row benchmark' keyed for 'swap rows benchmark' . It'll appear as keyed in the results

I think the issue is just in how the status of the "run" benchmark" is reported - it probably prints the value from the "swap rows" benchmark and not from itself.

**Comment by krausest** [comment]
Yes, you're right. I think I fixed it recently https://github.com/krausest/js-framework-benchmark/commit/d226e79eeba634744ed68ca323a7d1f8bad85811 (See line 255 in the new rev). It reported non-keyed for 'run' when any keyed check failed. Are you on an older version or is there some other bug left?

**Comment by mmichlin66** [comment]
Yes, I synced more than 3 days ago, so it is probably already fixed. I'll re-check and close the issue. Thank you.

**Comment by mmichlin66** [comment]
Yes, this is fixed.
