### ISSUE TITLE
Webdriver doesn't start on Chrome 54

### ISSUE THREAD

**Issue by trueadm** [krausest/js-framework-benchmark#64]
Webdriver doesn't run, instead throwing an error: 

`SessionNotCreatedError: session not created exception`

If you update `chromedriver` to `2.24.1` this issue goes away but I can't get chromedriver to open a window. :/

**Comment by krausest** [comment]
Confirmed. chromedriver 2.24.1 is needed for chrome 54 (https://bugs.chromium.org/p/chromedriver/issues/detail?id=1451)

Bad thing is that I can't even get the slightly modified example from the homepage working:
```
var chromedriver = require('chromedriver');

var webdriver = require('selenium-webdriver'),
    By = webdriver.By,
    until = webdriver.until;

var driver = new webdriver.Builder()
    .forBrowser('chrome')
    .build();

driver.get('http://www.google.com/ncr');
driver.findElement(By.id('lst-ib')).sendKeys('webdriver');
driver.findElement(By.name('btnG')).click();
driver.wait(until.titleIs('webdriver - Google Search'), 1000);
driver.quit();
```

It opens the browser window on my MacBook, navigates to google, but it doesn't get past driver.get with chromedriver@2.24.1 and selenium-webdriver@2.53.3 (same with selenium-webdriver@3.0.0-beta-3)

The same happens with the webdriver-ts. It opens a windows on my machine, but doesn't get any further than loading the benchmark.

Have to investigate further...

**Comment by krausest** [comment]
This java version works with Chrome 54, selenium-chrome-driver 2.53.1, chromedriver 2.24.1
```
package net.stefankrause;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.*;

public class ChromeTest2 {
    public static void main(String[] args) throws Exception {
        System.setProperty("webdriver.chrome.driver", "node_modules/chromedriver/lib/chromedriver/chromedriver");

        WebDriver driver = new ChromeDriver();
        driver.get("http://www.google.com/ncr");
        WebElement searchBox = driver.findElement(By.id("lst-ib"));
        searchBox.sendKeys("ChromeDriver");
        searchBox.submit();
        Thread.sleep(5000);  
        driver.quit();
    }
}
```

Let's see if I have to reanimate the java test driver.

**Comment by trueadm** [comment]
any more luck on this? It's a bit frustrating as Chrome 54 brought in huge perf improvements in V8 (mainly with memory) and I wanted to see how that reflected.

**Comment by krausest** [comment]
Sorry, very hard to spot. Here's what I know so far:

1.  Selenium guys think it's a chromedriver bug: https://github.com/SeleniumHQ/selenium/issues/2924#issuecomment-253859285
2. I thought it was only related to the Javascript binding. I can't get any example to work with the javascript webdriver and chrome 54. The java binding seemed to work. Thus I improved webdriver-java. It works fine within IntelliJ. After finishing the work I had to realize that it hangs when run from the command line via maven (how crazy is that?)
3. Chromedriver 2.24.1, Chrome 54 and webdriver-ts work fine in my linux virtual box. Will have to check the Windows VM later.

Todos:
- Check Windows VM
- Create a chromedriver bug report

So currently I'm pretty clueless. BTW what system are you running on?

**Comment by krausest** [comment]
I added webdriver-java again and updated webdriver-ts to the new chromedriver.
It works on my Windows VM and Linux VM. Thus seems to be OSX specific. 
Maybe that explains the lack of other bug reports.

**Comment by krausest** [comment]
Here's the chromedriver bug report:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1551

**Comment by trueadm** [comment]
@krausest nice work in tracking down that it's to do with OSX (I'm also on OSX), which sucks!

**Comment by krausest** [comment]
can you try to set `export LANG=”en_US.UTF-8″`prior to running the tests? Seems to work for me. https://bugs.chromium.org/p/chromedriver/issues/detail?id=1552#c35
Maybe that explains why ran within IntelliJ.

**Comment by trueadm** [comment]
Works fine for me now. Thanks mate.
