### ISSUE TITLE
"npm run check" expects 1 node added and 1 removed for "swap rows" benchmark

### ISSUE THREAD

**Issue by mmichlin66** [krausest/js-framework-benchmark#640]
I am curious why the `check` tool expects nodes to be removed and added while the data items are clearly moved (swapped) in the "swap rows" benchmark. My framework detects that the data item IDs (keys) have been moved and not deleted, and moves the DOM nodes accordingly; however, the `check` tool reports:

>Keyed test for swap failed. Expected at least 1 added and 1 removed TR, but there were 0 added and 0 removed
mimbl-v0.1.6-keyed is keyed for 'run benchmark' and keyed for 'remove row benchmark' and non-keyed for 'swap rows benchmark' . It'll appear as non-keyed in the results

and categorizes my framework as non-keyed.

Since the data items are not deleted I would expect that the keyed frameworks will be encouraged to not add/remove but to move the corresponding DOM nodes.

Am I missing something?

**Comment by krausest** [comment]
First of all: The test doesn't define what's right or not. It's job is to identify implementations that claim be to keyed but aren't. It had to be fixed a few times in the past....

In its current implementation the test uses a MutationObserver to check the behaviour. For all keyed implementations moving the node in the swap operation causes (one or) two MutationRecords that have in sum one added and one removed row. I get that behaviour also when the node is actually moved via appendChild or insertBefore.

If you're sure that your implemenation is keyed please submit it and I'll see if I have to fix my keyed test 😃

**Comment by mmichlin66** [comment]
Fair enough - I hope to submit somewhere next week. Thank you.

**Comment by mmichlin66** [comment]
My bad - turns out I changed and debugged development version and ran `check` on the unchanged production version. Sorry for wasting your time!
