### ISSUE TITLE
Add Flutter Web

### ISSUE THREAD

**Issue by leocanela** [krausest/js-framework-benchmark#687]
Flutter is Google’s UI toolkit for building natively compiled applications for mobile, desktop and for the web. Although it's still in really early beta, it would be interesting to see how it stacks up against slower frameworks. 
More info: [Flutter Web](https://flutter.dev/web)

**Comment by ryansolid** [comment]
If anyone is interested go for it. 😄 This repo is driven off community submissions. @krausest basically maintains and runs the benchmarks but many of the implementations are written by library writers, or community members. With the exception to Vanilla or a few of the larger libraries including React/Angular/Vue variations which these people find useful for comparison you will find that almost all submitted by the community. That being said the benchmarks are tricky so knowing the ins and outs of the library or having assistance from contributors is probably essential to making a good implementation.

**Comment by krausest** [comment]
Closing all issues that ask for some implementation - but please feel free to submit an PR for it!
