### ISSUE TITLE
Fix dojo non-keyed

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#742]
For some reason select row is broken for dojo in the non-keyed version.
Fixing the versions doesn't help.
@agubler Can you please take a look at it or should be just remove the non-keyed version?

**Comment by agubler** [comment]
@krausest I can take a quick look as I update to the latest release.

**Comment by agubler** [comment]
can you assign it to me?

**Comment by agubler** [comment]
@krausest Also in the latest result table, Dojo's results seems to be empty/blank

**Comment by krausest** [comment]
Thanks! I'll updated the keyed results soon. For the non-keyed version I need an update first.

The keyed version of dojo currently has issue #694, which means it doesn't swap rows, but remove and add a row instead. Is there a way to fix it. Otherwise I'll have to move the keyed version to the non-keyed section at some point in time.

**Comment by agubler** [comment]
@krausest I'd have to have a look at that, my gut feel is that it won't be possible currently.

**Comment by krausest** [comment]
BTW results for dojo keyed are available again.

**Comment by agubler** [comment]
Thanks @krausest, I'll probably get round to the updates and fixing the current non-keyed impl at the weekend. Hope that's okay.

**Comment by krausest** [comment]
Of course! It’s a strange case. I’m pretty sure the implementation used to work fine. Most of the time locking the caret versions helps, but here it doesn‘t.
