### ISSUE TITLE
pux build stopped working

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#747]
```
> js-framework-benchmark-pux@1.0.0 build-prod /data/stefan/Source/Javascript/js-framework-benchmark/frameworks/non-keyed/pux
> pulp browserify --optimise --to output/bundle.js

/data/stefan/Source/Javascript/js-framework-benchmark/frameworks/non-keyed/pux/node_modules/purescript/vendor/purs: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```
Happens with node 10, 12 and 14. Updating with ncu doesn't heal it.

**Comment by krausest** [comment]
Same for thermite
```
* Browserifying project in /build/frameworks/non-keyed/thermite
* Building project in /build/frameworks/non-keyed/thermite
* Build successful.
* Browserifying...
* ERROR: Cannot read property 'call' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! js-framework-benchmark-thermite@1.0.0 build-prod: `pulp browserify --optimise --to output/bundle.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the js-framework-benchmark-thermite@1.0.0 build-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-04T18_42_20_999Z-debug.log
child_process.js:650
    throw err;
    ^

Error: Command failed: npm run build-prod

```

**Comment by krausest** [comment]
@thomashoneyman Can you please take a look at it? I'd like to use node v14 for building, but I'm struggling to make it work.

**Comment by thomashoneyman** [comment]
@krausest I would actually recommend that Pux and Thermite be removed from the benchmarks. 

Pux has been in maintenance mode for quite some time, and Thermite was always an experimental library. In retrospect I don't think they should have been added and that they misrepresent PureScript's performance (Halogen, for example, is much more performant and even its virtual DOM is written in PureScript; others, like purescript-hedwig, are much faster still).

I was new to PureScript at the time, but now with more experience I'd suggest removing them from the benchmarks.
