### ISSUE TITLE
Inconsistency in implementation of 10th row updates

### ISSUE THREAD

**Issue by mixonic** [krausest/js-framework-benchmark#76]
Howdy. I was looking at a few implementations to see how differences are normalized and noticed some significant differences in how the "every 10th row" code is implemented:

* [Inferno implementation](https://github.com/krausest/js-framework-benchmark/blob/master/inferno-v1.0.0-beta5/src/store.es6.js#L23-L25)
* [Ember implementation](https://github.com/krausest/js-framework-benchmark/blob/master/ember-v2.6.1/app/services/rows.js#L41-L48)

The Inferno implementation mutates the array, where the Ember one rebuilds the entire set of data. Which is the intended implementation?

Further, it seems like the data generation itself should perhaps not be included in the benchmarked values (though if the items in the array are part of a change-tracking solution like Ember objects or MobX it seems unfair to exclude that work, so maybe not).

**Comment by krausest** [comment]
Hi, your ember contributions are very welcome - my ember is not that good.

I'd leave the store implemenation up to the framework - each has its own requirements for reacting on data change. 
Unless I'm completely mistaken e.g. aurelia and vue wouldn't even re-render with the inferno code - though the code feels very right for react-like libraries. 
So you can choose whatever works best for ember (we've discussed a few rules in https://github.com/krausest/js-framework-benchmark/issues/9).

The benchmark is intended to measure end-to-end (and for that purpose include browser render time) and thus I'd like to include the duration for updating the model too - despite the different implementations.
