### ISSUE TITLE
Feature Request: Make it possible to filter frameworks by language/technology

### ISSUE THREAD

**Issue by utkarshkukreti** [krausest/js-framework-benchmark#795]
I think it would be useful to be able to have a filter to compare the performance of e.g. only Rust or only WASM libraries or only Virtual DOM libraries.

Some categories I think that would be useful to have:

1. Language: JS + TS, Rust, Haskell, PureScript, ReasonML + OCaml, Scala, Elm, possibly more.

2. WASM or not.

3. Virtual DOM or not.

What do you think about having this in the results page besides the "Which languages?" dropdown?

**Comment by krausest** [comment]
I'm afraid I won't add that filter. If someone wanted to create a PR for it I'll merge it if the categories are well defined.
