### ISSUE TITLE
Add app startup time in dev mode

### ISSUE THREAD

**Issue by cc-ebay** [krausest/js-framework-benchmark#817]
App loading time is important for the users.

But some frameworks do not have a great development experiences related to time that it takes to startup of the app from scratch or how long it takes to see see on the screen the effect of a change in the code.  It would be great to have a measure of "cold app load time" and "update time after a code change".
Adding if the framework supports some kind of "hot-reloading" can also be useful

**Comment by krausest** [comment]
Both would be very interesting and might be major reasons to decide for or against a framework, but I consider them out of scope for this benchmark.
