### ISSUE TITLE
ws prefers gzipped bundle if there is one

### ISSUE THREAD

**Issue by andyhasit** [krausest/js-framework-benchmark#829]
I occasionally gzip the production bundle of the framework I am developing, as well as those of several other frameworks, to see their sizes gzipped:

    cd dist
    gzip -fk main.js
    ls -lh

That command leaves two files in the dist directory:

    dist/main.js
    dist/main.js.gz

I don't usually bother deleting the gzipped file as there is no need.

But I just discovered that the webserver (`ws`) chooses `main.js.gz` over `main.js` if it exists.

Unless this is a very recent change, this means:
 
1. Every time I updated the repo, installed the new versions of a frameworks and run tests, I have in fact been re-testing whatever version I had at the time I last gzipped the bundle for that framework, which could be months ago.
2. Every time I changed my own code and re-run tests (or even just loaded the page in the browser) I have actually been re-testing whatever went into the last bundle I gzipped, which could be anything between a few minutes or days ago.

Given a lot of people interested in performance are also interested in bundle sizes, and might be tempted to do the same, I think we should change this behaviour. If we can't, then we should warn about it as it invalidates your local tests, and given you expect variance anyway, it's very hard to spot.

I couldn't find anything about gzip in [here](https://github.com/websockets/ws/search?q=gz).

**Comment by andyhasit** [comment]
I had a big dig over at [websockets/ws](https://github.com/websockets/ws) and couldn't determine where or how it decides to serve a `main.js.gz` instead of `main.js`, nor can I see anything which does that in this repo, which makes me think it's a dependency of [websockets/ws](https://github.com/websockets/ws) which causes this behaviour...

I know how to enable this behaviour on nginx, and I know that some node servers (like [Koa](https://github.com/koajs/static)) have a flag for this. But as far as I can tell from it's [websocket-server.js](https://github.com/websockets/ws/blob/master/lib/websocket-server.js) file, it uses the [http](https://nodejs.org/api/http.html) module for static content, and [http](https://nodejs.org/api/http.html) definitely doesn't do that by default (I tested that, partly to see if it might be Chrome headers).

I am wondering if the simpler solution would be to warn (or abort?) the benchmark if a `.gz` file is found in the `/dist` directory? This would protect us should we ever switch to a different server.

If you think this is a good solution I can do a PR for that, and would added it to the isKeyed check too. And let's hope no existing webpack actually creates a gzipped output.

People who want to check gzip sizes can still do so, so long as they dump the `.gz` files elsewhere. I could even add a command which gzipz the main.js/index.js for every framework which has one and dumps them all in a new gitignored directory for those who are interested.

In fact, I thought of suggesting bundle sizes as an extra metric in the table, but this has probably been discussed, and there are several difficulties with that that I can see:

- We'd need to standardise the bundle name (to main.js or index.js)
- Some frameworks might produce chunks, or do it differently?
- Framework developers would presumably want to be informed that this is being measured, and that's potentially going to add hassle as everyone tries to be the smallest.

**Comment by ryansolid** [comment]
The second point is the tricky one. Not only because of code splitting. Libraries would try to avoid any additional imports in a benchmark measuring loading speed. But a number libraries put their templates in the index.html file. I know we like to compare bundle sizes but even measuring total JS size won't be comparable.

**Comment by andyhasit** [comment]
@ryansolid of course, why didn't I think. Code in the template renders that metric useless (no pun intended) so for that and the other reasons I think we can drop that idea.

**Comment by krausest** [comment]
A PR for the isKeyed check would be nice.
