### ISSUE TITLE
Vue.js measurements missing?

### ISSUE THREAD

**Issue by boussou** [krausest/js-framework-benchmark#9]
I don't want to create a pull request for that
;-)

'use strict';

var Vue = require('vue');
var {Store} = require('./store');

var store = new Store();

var startTime;
var lastMeasure;
var startMeasure = function(name) {
    startTime = performance.now();
    lastMeasure = name;
}
var stopMeasure = function() {
    var last = lastMeasure;
    if (lastMeasure) {
        window.setTimeout(function () {
            lastMeasure = null;
            var stop = performance.now();
            console.log(last+" took "+(stop-startTime));
        }, 0);
    }
}

new Vue({
    el: '#main',
    data: {
        rows: store.data,
        selected: store.selected
    },
    methods: {
        add() {
            startMeasure("add");
            store.add();
            this.rows = store.data;
            this.selected = store.selected;
            stopMeasure();
        },
        remove(item) {
            startMeasure("remove");
            store.delete(item.id);
            this.rows = store.data;
            this.selected = store.selected;
            stopMeasure();
        },
        select(item) {
          startMeasure("select");
            store.select(item.id);
            this.rows = store.data;
            this.selected = store.selected;
            stopMeasure();
        },
        run() {
            startMeasure("run");
            store.run();
            this.rows = store.data;
            this.selected = store.selected;
            stopMeasure();
        },
        update() {
          startMeasure("update");
            store.update();
            this.rows = store.data;
            this.selected = store.selected;
            stopMeasure();
        },
        runLots() {
          startMeasure("runLots");
            store.runLots();
            this.rows = store.data;
            this.selected = store.selected;
            stopMeasure();
        },
        clear() {
          startMeasure("clear");
            store.clear();
            this.rows = store.data;
            this.selected = store.selected;
            stopMeasure();
        },
        swapRows() {
          startMeasure("swapRows");
            store.swapRows();
            this.rows = store.data;
            this.selected = store.selected;
            stopMeasure();
        }
    }
})

**Comment by krausest** [comment]
Fixed - thanks. Please note that these calls are only a hack to estimate the duration. The values reported by the benchmark are extracted from the timeline. Still it's a good check whether the reported numbers are plausible.

**Comment by leeoniya** [comment]
@krausest 

same with plastiq

**Comment by leeoniya** [comment]
also, as i'm doing the domvm version i'm noticing not all implementations are equal. some are missing `lbl` and `remove` classes, others `tbody`. Some of these can impact perf quite a lot when we're talking thousands of nodes. i'm getting roughly 2x vanilla, btw.

**Comment by boussou** [comment]
@krausest  - That call is useful as you said. I went looking a it just to check it had no impact on results. 
Now I am It can't.

**Comment by krausest** [comment]
@leeoniya: You're right. They should be equal unless absolutely needed by the framework e.g. for cycle.js where I needed some additional information in the dom.
tbody was missing for  angular, aurelia and vue which is fixed now.
.lbl and .remove are only used in vanilla.js. I needed them to discern the clicks on the columns when the event bubble up. It should be a disadvantage for vanillajs but I didn't find a better way.

**Comment by leeoniya** [comment]
@krausest thanks i'll keep you posted if i spot anything else.

you should also standardize `store.js` as it is not identical across libs. similar to dbmonster it should just be a require rather than copied and manhandled per lib. right?

**Comment by krausest** [comment]
@leeoniya: I thought about that but rejected it. sCU comes with a cost for the store as it must be immutable. Some frameworks favor or force immutable stores (react and cycle.js) others are faster with a mutable store (angular 2). I'd like to leave that to each framwork. 
In a actual program I'd adapt my style to match my needs and the framework best. 

Each program should use the same strings and the same random function on the fly (and yes, maybe a fixed PRNG would be better) when creating rows and anything else can be optimized for each framework. Let's see how soon that rule turns out to be too weak ;-)

**Comment by krausest** [comment]
Closing the issue. The latest aurelia implementation needs a very special store due to it's update mechanism.

**Comment by leeoniya** [comment]
fair enough, though i think it should be outlined exactly what is expected. is it simply visual congruence? can all libs implement their own data structures? as long as the UI behavior is the same, the generated DOM shape or classes don't matter? can we ditch bootstrap to boost performance [1]? can someone do a webgl/canvas implementation that looks the same?

There are a lot of things to consider here that affect the results in major ways. Without guidelines for DOM shape, data structure, event handler requirements, etc, the results are mostly meaningless :/

[1] https://github.com/trueadm/inferno/issues/223#issuecomment-224158649

**Comment by krausest** [comment]
Ok - I see, maybe we need more rules.
1. Bootstrap and the parent css must be used as in vanilla-js.
2. The same visual appearance as in vanilla-js must be achived.
3. The DOM structure must be the same as in vanilla-js, except for arbitrary omission or addition of data attributes or addition of other non visual attributes. Webgl/Canvas/Native implementations are accepted and marked as "alternatives".
4. Each program should use the same strings and the same random function on the fly (and yes, maybe a fixed PRNG would be better) when creating rows and anything else can be optimized for each framework.
5. All implementations must be approved by arbitrary decision of the maintainer (that is me).

Maybe I'll refine #5 ;-)

**Comment by leeoniya** [comment]
more questions:

- for "swap rows", is it necessary that the physical DOM nodes be swapped or merely that the resulting DOM be correct?
- `aria-hidden` is not visual, is it required? (that's 1000 setAttribute calls that can be saved)
- vanillajs does event delegation rather than attaching 1000 click handlers, i assume this is acceptable if the lib supports it.
- must selected row highlighting be maintained during other actions? vanilla impl clears the selection (but this may be a bug).

once i know exactly what's "legal" i will do a pull request with my domvm impl :)

**Comment by krausest** [comment]
- For swap rows only the resulting DOM must be correct.
- aria-hidden must be present
I just answered the other two questions on issue 17, just for the sake of completeness:
- event delegation is fine
- row highlighting must be preserved except for clear, create, remove

I'm looking forward your pull request - I'm very excited to see domvm in action!
