### ISSUE TITLE
Building webdriver-ts doesn't work (Property 'config' does not exist on type 'unknown'.)

### ISSUE THREAD

**Issue by lefetmeofefet** [krausest/js-framework-benchmark#919]
![image](https://user-images.githubusercontent.com/13165085/128730622-c916e517-b50a-4ae4-a530-ab6bf17c737d.png)

Steps to reproduce:
* git clone
* cd webdriver-ts
* npm ci
* npm run build-prod

This has happened both on my Windows 10 PC, and a fresh Ubuntu 20.04.2.0 VM.
Have a good day :)

**Comment by krausest** [comment]
Thanks for the heads up. I mistakenly updated typescript. Should be fixed now.

**Comment by lefetmeofefet** [comment]
Works perfectly. Thanks!
