### ISSUE TITLE
Add vue 2.6 and vue 3.2

### ISSUE THREAD

**Issue by ibrahimBeladi** [krausest/js-framework-benchmark#920]
Add vue 2.6 and vue 3.2 (and keep vue 3.1) in order to compare there performances.

**Comment by krausest** [comment]
We had vue 2.6 and vue 3.0 (called vue-next then) in older runs. I don't think we should add 2.6 again. Here are the old results: 
https://krausest.github.io/js-framework-benchmark/2020/table_chrome_83.0.4103.106.html
Vue 3 was a big step forward.

And we've got a PR for vue 3.2 that will (hopefully) be merged soon:
https://github.com/krausest/js-framework-benchmark/pull/921
