### ISSUE TITLE
Incorrect timing

### ISSUE THREAD

**Issue by yisar** [krausest/js-framework-benchmark#932]
https://github.com/yisar/js-framework-benchmark/tree/master/frameworks/keyed/fre

When I run the benchmark of fre, the time of select rows exceeds 1s. There must be a problem here, because when I operate in chrome, select rows only takes 20ms.
My chrome:

![微信图片_20210829104200](https://user-images.githubusercontent.com/12951461/131236470-9da94bc5-c13d-4cb1-b06a-7bf52f47d433.png)

![image](https://user-images.githubusercontent.com/12951461/131238431-ac2a5299-18ff-4dd3-9adb-c6cedc7dc489.png)

The benchmark:

![image](https://user-images.githubusercontent.com/12951461/131236498-b77d0ab6-7d37-4e59-8d74-1c52785ec4fb.png)

There must be an error. It can't be so slow unless it's blocked.

In addition, fre is a framework with Time slicing. It seems that the current benchmark is not friendly, maybe.

https://github.com/yisar/fre/issues/271#issuecomment-907577159
https://github.com/krausest/js-framework-benchmark/issues/498#issuecomment-907719164

Can you take a look?

**Comment by LXSMNSYC** [comment]
20ms on normal run (with no CPU throttle) is slow (in comparison, Solid and compostate-jsx only takes <1ms). Most of the VDOM libraries fail on this test since it requires rebuilding the entire VDOM of the table rather than updating the selected row.

**Comment by yisar** [comment]
@LXSMNSYC You're right. In this case, the fine-grained update of solidjs with in-place mutation can be completed in 1ms, but I mean, whether it's 20ms or 1ms, humans can't perceive it, and chasing 1ms is of little significance.

Fre also has the defect of VDOM, that is, it needs to traverse the whole list, which is a problem of all VDOM frameworks, because the mental model of immediate mode is like this.

**Comment by LXSMNSYC** [comment]
> whether it's 20ms or 1ms, humans can't perceive it
Well the thing is, the benchmarks are for stress testing and not for normal user interaction. Almost every framework/libraries in the benchmarks have no noticeable differences in performance, well at least on human perception.

IMO it would better if you can compare the benchmarks against similar libraries (for instance, Preact and React).

Another thing is that the select row test has been in many discussions before. IIRC the final decision was to run the test on x16 throttling.

**Comment by ryansolid** [comment]
@yisar are you running on M1 apple chips? They have an issue with applied slowdowns when running in the chrome driver. I need to turn off slowdown on my main development computer since it is so absurdly long. Do other implementations have the same issue on your computer?

**Comment by yisar** [comment]
@ryansolid No, other frameworks work well. 
I'm not sure what I missed. It's also possible that the test program deliberately magnified fre's defects.
As long as the reason can be found, there is a way to optimize the test case.

**Comment by yisar** [comment]
> IIRC the final decision was to run the test on x16 throttling.

It is possible to amplify fre's defects here because fre does not use `memo` technology.

**Comment by LXSMNSYC** [comment]
I suggest that you look into the diff/patch implementation of fre

**Comment by ryansolid** [comment]
Ok, well 20ms with no slowdown I think is still indicator of something. Can try to turn off slowdowns to confirm that. I comment out https://github.com/krausest/js-framework-benchmark/blob/master/webdriver-ts/src/benchmarks.ts#L92 and rebuild to run with no throttling.

**Comment by yisar** [comment]
@ryansolid You're right. It's really caused by slowdown. If so, I must use memo technology.

**Comment by yisar** [comment]
@ryansolid @LXSMNSYC 

![image](https://user-images.githubusercontent.com/12951461/131241649-b0c2cf39-4c38-4ef8-a165-a888393a239e.png)

You're right. It's true that the slowdown magnifies fre's defects, but even if there is no slowdown, fre's update is still a bit slow... Of course, Time slicing itself will slow down as a whole, but at least the current result is expected.

**Comment by LXSMNSYC** [comment]
It seems that the partial update is slower than React, which usually indicates that the patch algo is slower. If you can optimize that part, I'm sure that the rest of patch-related tests would perform well.

**Comment by yisar** [comment]
@LXSMNSYC Yes, yes, this part can be optimized. It needs to diff props in the reconcile stage. I didn't do this now 😭 :

**Comment by krausest** [comment]
I suggest you create a PR (we can still decide when to merge this PR) and then we can take a look at it together. The implementation on https://github.com/yisar/js-framework-benchmark/tree/master/frameworks/keyed/fre seems to have no remove button and thus my build process fails.

**Comment by yisar** [comment]
@krausest pr is here https://github.com/krausest/js-framework-benchmark/pull/933
