### ISSUE TITLE
Consider switching to puppeteer from chromedriver?

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#947]
:heavy_check_mark: Looks like #916 is hard to fix with selenium/chromedriver since there's no API to dispose a element reference. Puppeteer has such an dispose method.

:heavy_check_mark: Puppeteer also has a nice api to get a timeline trace that can be loaded in the chrome performance tab which would be very welcome to allow a better understanding of the reported values.

:heavy_check_mark: Puppeteer-core supports nicely the M1 mac, for which I haven't found a smooth path for chromedriver yet

:heavy_check_mark: For chromedriver I have to disable site isolation on M1, which is not needed for puppeteer

So I was pretty enthusiastic migrating to puppeteer which went mostly nice (handlich shadow dom is always ugly and e.g. calling click in the browser context didn't work for all frameworks, I had to call click on the element handle).

I've pushed a branch for puppeteer that should work on OSX and Linux.

However I have a few issues that currently prohibit replacing chromedriver with puppeteer.

- [ ]  Overall values from puppeteer are a bit slower than from chromedriver. Seems like the tracing functionality comes with additional costs.  (I could live with if all frameworks were similarly slower)

- [ ]  Some frameworks are hit really badly by running the trace in puppeteer, see the screenshot below (left chromedriver, right puppeteer on OSX):
<img width="1082" alt="Bildschirmfoto 2021-10-03 um 21 36 53" src="https://user-images.githubusercontent.com/3374055/135768910-a9e68cd0-23fb-4e6b-b832-d385841034e6.png">
And the same for Linux:

<img width="1080" alt="Bildschirmfoto 2021-10-05 um 21 22 55" src="https://user-images.githubusercontent.com/3374055/136089264-ce18b1d0-70b9-442d-a60f-9382746b0ad0.png">
We had similar behaviour with #549 with chromedriver which also impacted svelte. For chromedriver it was sufficient to reduce the trace categories, but it didn't help with puppeteer.

(I used only slow down factors that can be selected in the chrome performance tab thus some benchmarks are almost too fast to measure.)

Results for:
- OSX and chromedriver: https://krausest.github.io/js-framework-benchmark/2021/table_chrome_94_osx_chromedriver.html
- OSX and puppeteer: https://krausest.github.io/js-framework-benchmark/2021/table_chrome_94_osx_puppeteer.html
- linux and chromedriver: https://krausest.github.io/js-framework-benchmark/2021/table_chrome_94_linux_chromedriver.html
- linux and puppeteer: https://krausest.github.io/js-framework-benchmark/2021/table_chrome_94_linux_puppeteer.html

So currently switching to puppeteer is not the solution we're looking for!

**Comment by yisar** [comment]
How about playwright?

**Comment by krausest** [comment]
Playwright seems to offer nothing like page.metrics() in pupeeteer, so I can only compare clientTracing values:
```
┌─────────┬─────────────┬────────────────────┬───────────────────┬────────────────────┬──────────────┐
│ (index) │  framework  │   clientTracing    │  clientNoTracing  │      timeline      │ clientFactor │
├─────────┼─────────────┼────────────────────┼───────────────────┼────────────────────┼──────────────┤
│    0    │ 'vanillajs' │ '84.012 (10.039)'  │ '84.425 (12.673)' │  '82.759 (9.951)'  │   '0.995'    │
│    1    │  'svelte'   │ '105.012 (10.583)' │ '93.487 (7.233)'  │ '103.986 (10.252)' │   '1.123'    │
└─────────┴─────────────┴────────────────────┴───────────────────┴────────────────────┴──────────────┘
```
So playwright looks similar to puppeteer, svelete might be about 12% slower when tracing (whereas vanillajs is not slower)

**Comment by krausest** [comment]
But playwright sometimes gives me different (much closer) results:
```
┌─────────┬─────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────┐
│ (index) │  framework  │   clientTracing   │  clientNoTracing  │     timeline      │ clientFactor │
├─────────┼─────────────┼───────────────────┼───────────────────┼───────────────────┼──────────────┤
│    0    │ 'vanillajs' │ '84.963 (10.799)' │ '84.075 (10.440)' │ '84.455 (11.104)' │   '1.011'    │
│    1    │  'svelte'   │ '102.988 (8.807)' │ '99.100 (13.426)' │ '101.736 (9.176)' │   '1.039'    │
└─────────┴─────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────┘
```
Needs more investigation...

**Comment by krausest** [comment]
I'm closing this issue, since chrome 100 forced me to switch away from chromedriver.
