### ISSUE TITLE
Consider running the benchmarks from within browserless

### ISSUE THREAD

**Issue by unlikelyzero** [krausest/js-framework-benchmark#951]
I'm currently exploring the area of browser based performance tooling and so I naturally stumbled into this repo! First, let me just say that this is really interesting work and I appreciate it that you've made it open and available for the js community.

At present, I'm trying to create a common interface for repeatable, automated, and browser-based performance tests. I found https://github.com/browserless/chrome to be a great way to drive performance tests in a `hermetic` environment. It exposes the CDP Interface for playwright, puppeteer, and webdriver-based protocols. Given that it's containerized, I can also control CPU and Memory limits so that the performance tests more easily transfer between host machines.

The `prom-client` packaging also exposes most of the browser to report on CPU statistics which is something I've struggled to measure any other way.

Have you considered using browserless in your benchmarks?

**Comment by krausest** [comment]
Actually I didn't. For most benchmarks here it's necessary to prepare the page and then run the action that should be measured (i.e. the preparation should be excluded). This kind of measurement can be achieved well with chrome's timeline events. What benefits would you see for browserless and in what way might it help?
