### ISSUE TITLE
Update all results

### ISSUE THREAD

**Issue by Atry** [krausest/js-framework-benchmark#97]
There may be some wrong in the result. `binding.scala-v10.0.1_06_remove-one-1k` should not be as slow as the [result](https://cdn.rawgit.com/krausest/js-framework-benchmark/097ee1c3fe15ee519af82ac1cb6e240d62a665f0/webdriver-ts/table.html).

On my computer, `binding.scala-v10.0.1_06_remove-one-1k` is 10 times faster than vanillajs_06_remove-one-1k !

```
after initialized  06_remove-one-1k 0 binding.scala-v10.0.1
after run  06_remove-one-1k 0 binding.scala-v10.0.1
result binding.scala-v10.0.1_06_remove-one-1k [ { type: 'click', ts: 138156995841, dur: 348, end: 138156996189 },
  { type: 'paint', ts: 138157055751, dur: 1099, end: 138157056850 },
  { type: 'gc', ts: 138156900336, mem: 36.346763610839844 } ]
```

```
after initialized  06_remove-one-1k 0 vanillajs
after run  06_remove-one-1k 0 vanillajs
result vanillajs_06_remove-one-1k [ { type: 'click', ts: 138258041670, dur: 3743, end: 138258045413 },
  { type: 'paint', ts: 138258123467, dur: 1444, end: 138258124911 },
  { type: 'gc', ts: 138258135172, mem: 41.954978942871094 } ]
```

I suspect that `vanillajs_06_remove-one-1k` benchmark was running on a different Chrome version, which is the cause of the difference.

(Moved from #94)

**Comment by krausest** [comment]
The results are indeed mixed between chrome 54 and 55. But on chrome 55 I get the following results:

result binding.scala-v10.0.1_06_remove-one-1k 46.861 61.166 **55.160333333333334** 5.725320388900131
result vanillajs_06_remove-one-1k 46.408 72.83 **60.121** 11.491577640457669
result vanillajs-keyed_06_remove-one-1k 47.374 57.637 **51.74533333333334** 3.873861409785103

The avg is marked **bold**.

Can't see an error as big as you describe (and I can't imagine there's a way to be 10x faster than vanillajs in this benchmark).

**Comment by Atry** [comment]
I meant that the `binding.scala-v10.0.1_06_remove-one-1k`'s JavaScript executing is 10x faster than `vanillajs_06_remove-one-1k`. However, the `remove-one-1k`'s DOM rendering consumes the same time on all frameworks, which cause the overall time closer.

**Comment by krausest** [comment]
This is why this benchmark measures duration including rendering. I'm not too much interested in the pure javascript duration. I currently can't see a mistake. Results will be updated with an official (and multiple checked) run when I update my blog.
