### ISSUE TITLE
Add AstroJS to the list

### ISSUE THREAD

**Issue by dennisfrijlink** [krausest/js-framework-benchmark#971]
Astro is a fresh but familiar approach to building websites. Astro combines decades of proven performance best practices with the DX improvements of the component-oriented era. Use your favorite JavaScript framework and automatically ship the bare-minimum amount of JavaScript—by default.

**Comment by ryansolid** [comment]
Adding Astro doesn't make sense here. It is a server rendering technology that allows you to use existing frameworks for islands of interactivity. Those frameworks are the ones presented here.

This benchmark tests performance of client-side rendering JavaScript in these frameworks. That is something Astro doesn't do itself. For the sake of this demo you would have a single Astro Island, that would after loading work identical to if Astro wasn't present. So there is no relevant comparison to be had.
