### ISSUE TITLE
"npm start" fails to create web server

### ISSUE THREAD

**Issue by foo123** [krausest/js-framework-benchmark#993]
I installed latest version from master (Chrome 98 results, 04/02/2022) (have ran previous versions of benchmark without problem)

I have windows 7 64bit, node v13.6.0 npm 6.13.4.

Have done:

`npm ci` on root folder

then 

`npm start` to start web server.

But I get following error:

```
> js-framework-benchmark@1.0.0 start C:\nikos\work\_nikos\open_source\git\js\js-framework-benchmark
> ws -c lws.config.js --static.maxage 1 -d .

Error: No valid exports main found for 'C:\nikos\work\_nikos\open_source\git\js\js-framework-benchmark\node_modules\koa'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Lws._getRequestHandler (C:\nikos\work\_nikos\open_source\git\js\js-framework-benchmark\node_modules\lws\index.js:170:17)
    at Lws.useMiddlewareStack (C:\nikos\work\_nikos\open_source\git\js\js-framework-benchmark\node_modules\lws\index.js:159:36)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! js-framework-benchmark@1.0.0 start: `ws -c lws.config.js --static.maxage 1 -d .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the js-framework-benchmark@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by foo123** [comment]
It seems I cannot run this release of the benchmarks on node < 14.15, since some modules (eg lighthouse) require it. My alternative is to use previous release, but then chromedriver is outdated

**Comment by foo123** [comment]
I made the following alterations after debugging the issue:

1. Upgraded `node` to 13.14.0 (seems 13.6 is buggy)
2.  Downgraded `lighthouse` module to @9.0.0 (newer versions require features of higher node versions). Now web server works correctly and most benchmarks run, except mem benchmarks.
3. Added manually Chrome binary path to `wedriver-ts/src/puppeteerAccess.ts` since puppeteer memory benchmarks are failing to launch chrome binary (still working on this).

**Comment by krausest** [comment]
I just checked on the reference docker / linux platform. Currently the docker image uses v14.17.0. A full rebuild works fine in the docker image. The linux machine uses v16.13.0 to start the web server.

I'm currently trying to update the docker image to v16.13.0, currently I'm seeing issues for binding.scala and react-focal hangs (!) during the build. I'll get back to this soon.

**Comment by krausest** [comment]
Just for information: I updated the docker build to v16.13.2 and had to fix a few frameworks. It builds now nicely with node v16.13.2 in the docker container.

**Comment by foo123** [comment]
For what is worth, keyed/angular framework fails to install correctly (win 7, node 13.14.0) ie `npm ci` fails (`cb not called` Error).

Since I am on win 7 at the moment, canot use node higher than what is supported on win 7. Trying to fix that as well, since I want to run angular benchmarks.

**Comment by foo123** [comment]
I solved tha angular issue by using [NVS node version switcher](https://github.com/jasongin/nvs) on my win7 box and switching to a previous node version supported both by angular and win7 (node v.12.20.*)
